/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/price/selling-prices": {
    /**
     * 売価検索API
     * @description 検索パラメータのうち、countryId、countryCodeのいずれかと、sellingPriceCategoryId、sellingPriceCategoryCodeのいずれかと、salesDateがそれぞれ必須。総件数や取得件数は親のカウントである。
     */
    get: operations["getSellingPrices"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description 取得制限数
     * @default 100000
     * @example 20
     */
    Limit: number;
    /**
     * @description 取得開始位置
     * @default 0
     * @example 0
     */
    Offset: number;
    /**
     * @description 今回取得件数
     * @example 20
     */
    Count: number;
    /**
     * @description 総件数
     * @example 10000
     */
    TotalResults: number;
    /**
     * @description 次回データ存在有無
     * @example true
     */
    HasMore: boolean;
    SellingPriceGetResponse: {
      /**
       * Format: int64
       * @description 売価ID
       * @example 6100000000000009
       */
      sellingPriceId?: number;
      /**
       * Format: int64
       * @description 販売対象ID
       * @example 6100000000000009
       */
      salesTargetId?: number;
      /**
       * Format: date
       * @description 適用開始年月日
       * @example 2024-01-01
       */
      applicationStartDate?: string;
      /**
       * @description 売価（税抜き）
       * @example 198.12
       */
      sellingPriceExcludingTax?: number | null;
      /**
       * @description 通貨コード
       * @example USD
       */
      currencyCode?: string;
      /**
       * Format: int32
       * @description 削除フラグ
       */
      deletedFlag?: number;
      /**
       * @description 更新者ID
       * @example USER123456
       */
      updatedUserId?: string;
      /**
       * Format: date-time
       * @description 更新日時
       * @example 2024-01-01T11:11:00
       */
      updatedDatetime?: string;
      sellingPriceCategory?: {
        /**
         * Format: int64
         * @description 売価分類ID
         * @example 10000012
         */
        sellingPriceCategoryId?: number;
        /**
         * @description 売価分類コード
         * @example 01
         */
        sellingPriceCategoryCode?: string;
        /**
         * @description 売価分類名
         * @example lens option
         */
        sellingPriceCategoryName?: string;
      };
      country?: {
        /**
         * Format: int64
         * @description 国ID
         * @example 91000000001
         */
        countryId?: number;
        /**
         * @description 国コード（alpha-2)
         * @example US
         */
        countryCodeAlpha2?: string;
        /**
         * @description 国コード（alpha-3)
         * @example USA
         */
        countryCodeAlpha3?: string;
        /**
         * @description 国名
         * @example America
         */
        countryName?: string;
      };
    };
    SellingPricesGetResponse: {
      offset?: components["schemas"]["Offset"];
      count?: components["schemas"]["Count"];
      limit?: components["schemas"]["Limit"];
      totalResults?: components["schemas"]["TotalResults"];
      hasMore?: components["schemas"]["HasMore"];
      records?: components["schemas"]["SellingPriceGetResponse"][];
    };
    CommonErrorResponse: {
      code: string;
      message: string;
      details?: Record<string, never>;
    };
  };
  responses: {
    /** @description Too Many Requests */
    TooManyRequests: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
  };
  parameters: {
    /**
     * @description <BFFシステムコード>_\<UUID>
     * @example bff_usgjpic_ab623ca6-b1e4-3796-a761-ca05605da64a
     */
    JinsTraceID: string;
    /**
     * @description jins-trace-idに紐付く呼出し枝番
     * @example 1
     */
    JinsTraceIdBranchNo?: string;
    /**
     * @description UI側でユーザを識別できるIDを格納
     * @example U00001
     */
    UserID: string;
    /**
     * @description 国コード
     * @example US
     */
    CountryCodeAlpha2?: string;
    /** @description 国ID */
    CountryId?: number;
    /**
     * @description 検索条件
     *
     * ※このリクエストパラーメータはJSON形式の文字列で値を入力してください。
     *
     * JSON必須項目に関して
     *
     * (※)はいずれかが必須になります。
     *
     *  // を使用したコメントはOASの定義上わかりやすくするために記載しているため、実際のリクエストには記載不要になります。
     *
     *  値を設定しない項目は記載不要になります。
     *
     * ```
     * {
     *     "searchTargetList": [ // 検索対象リスト
     *         {
     *             "sellingPriceCategoryCode": "XXXX", // 売価分類コード(※)
     *             "sellingPriceCategoryId": 2, // 売価分類ID（※）
     *             "salesTargetId": 1 // 販売対象ID
     *         },
     *         {
     *             "sellingPriceCategoryCode": "XXXX", // 売価分類コード(※)
     *             "salesTargetId": 1 // 販売対象ID
     *         },
     *         {
     *             "sellingPriceCategoryId": 2, // 売価分類ID（※）
     *             "salesTargetId": 1 // 販売対象ID
     *         }
     *     ]
     * }
     * ```
     *
     * @example  {"searchTargetList": [ { "sellingPriceCategoryCode": "XXXX", "sellingPriceCategoryId": 2, "salesTargetId": 1 }, { "sellingPriceCategoryCode": "XXXX", "salesTargetId": 1 }, { "sellingPriceCategoryId": 2, "salesTargetId": 1 } ] }
     */
    query: string;
    /** @description 販売年月日 */
    SalesDate: string;
    /**
     * @description ソートキー
     * 昇順降順はコロン区切り
     * 複数の場合はカンマ区切り
     * スペースは挟まない
     *
     * @example sellingPriceCategoryCode:ASC,sellingPriceCategoryId:DESC
     */
    SortKey?: string;
    /**
     * @description 取得制限数
     * @example 20
     */
    Limit?: components["schemas"]["Limit"];
    /**
     * @description 取得開始位置
     * @example 0
     */
    Offset?: components["schemas"]["Offset"];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * 売価検索API
   * @description 検索パラメータのうち、countryId、countryCodeのいずれかと、sellingPriceCategoryId、sellingPriceCategoryCodeのいずれかと、salesDateがそれぞれ必須。総件数や取得件数は親のカウントである。
   */
  getSellingPrices: {
    parameters: {
      query: {
        countryCodeAlpha2?: components["parameters"]["CountryCodeAlpha2"];
        countryId?: components["parameters"]["CountryId"];
        query: components["parameters"]["query"];
        salesDate: components["parameters"]["SalesDate"];
        sortKey?: components["parameters"]["SortKey"];
        limit?: components["parameters"]["Limit"];
        offset?: components["parameters"]["Offset"];
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["UserID"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SellingPricesGetResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["CommonErrorResponse"];
        };
      };
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
