/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/staff/authentication": {
    /**
     * スタッフ認証API
     * @description スタッフIDとパスワードで認証を行う。
     */
    get: operations["authenticateStaff"];
  };
  "/staff/staff/{staffId}": {
    /**
     * スタッフ情報取得API
     * @description スタッフ情報を取得する。
     */
    get: operations["getStaff"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description スタッフ認証APIレスポンス */
    AuthenticationResponse: {
      /**
       * @description トークン
       * @example abcdefgh12345678
       */
      token?: string;
    };
    CommonErrorResponse: {
      code: string;
      message: string;
      details?: Record<string, never>;
    };
    /**
     * @description スタッフ情報取得APIレスポンス
     * @example {
     *   "staffId": "JINS12345",
     *   "staffName": "Jon Staff"
     * }
     */
    StaffGetResponse: {
      /** @description スタッフID */
      staffId?: string;
      /** @description スタッフ名 */
      staffName?: string;
    };
  };
  responses: {
    /** @description Unauthorized */
    Unanthorized: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Not Found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Too Many Requests */
    TooManyRequests: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
  };
  parameters: {
    /**
     * @description アプリケーションノード間のトレーサビリティを確保するためのID
     * @example 2389c607-f5ed-4789-95a3-efd78be1e8d9
     */
    JinsTraceID: string;
    /**
     * @description jins-trace-idに紐付く呼出し枝番
     * @example 1
     */
    JinsTraceIdBranchNo?: string;
    /**
     * @description UI側でユーザを識別できるIDを格納
     * @example U00001
     */
    JinsUserID: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * スタッフ認証API
   * @description スタッフIDとパスワードで認証を行う。
   */
  authenticateStaff: {
    parameters: {
      query: {
        /**
         * @description スタッフID
         * @example JINS12345
         */
        staffId: string;
        /**
         * @description パスワード
         * @example ABCD1234
         */
        password: string;
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AuthenticationResponse"];
        };
      };
      400: components["responses"]["Unanthorized"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * スタッフ情報取得API
   * @description スタッフ情報を取得する。
   */
  getStaff: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
      path: {
        /**
         * @description スタッフID
         * @example JINS12345
         */
        staffId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["StaffGetResponse"];
        };
      };
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
