/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/status": {
    /** health check */
    get: operations["status"];
  };
  "/dummy": {
    /** dummy function to call external API */
    get: operations["dummy"];
  };
  "/validator/eyesightcombi": {
    /**
     * 度数組合せチェックAPI
     * @description 度数の組合せを確認し、組合せが妥当かを返却する
     */
    post: operations["postEyesightCombi"];
  };
  "/validator/eyepointmeasure": {
    /**
     * アイポイント測定チェックAPI
     * @description アイポイントが必須であれば必須チェックを実施して結果を返却する
     */
    post: operations["postEyepointMeasure"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description 度数組合せチェックAPIレスポンス */
    EyesightCombiPostResponse: {
      /**
       * @description 左処理結果コード
       * @example 1
       */
      resCodeLeft?: number;
      /**
       * @description 左処理結果メッセージ
       * @example 加入度数(ADD)が設定されていません。
       */
      resMessageLeft?: string;
      /**
       * @description 右処理結果コード
       * @example 1
       */
      resCodeRight?: number;
      /**
       * @description 右処理結果メッセージ
       * @example 加入度数(ADD)が設定されていません。
       */
      resMessageRight?: string;
    };
    /** @description アイポイント測定チェックAPIレスポンス */
    EyepointMeasurePostResponse: {
      /**
       * @description 左処理結果コード
       * @example 1
       */
      resCodeLeft?: number;
      /**
       * @description 左処理結果メッセージ
       * @example 加入度数(ADD)が設定されていません。
       */
      resMessageLeft?: string;
      /**
       * @description 右処理結果コード
       * @example 1
       */
      resCodeRight?: number;
      /**
       * @description 右処理結果メッセージ
       * @example 加入度数(ADD)が設定されていません。
       */
      resMessageRight?: string;
    };
    /** @description 度数組合せチェックAPIリクエスト */
    EyesightCombiPostRequest: {
      sphericalPowerLeft: components["schemas"]["SphericalPower"];
      astigmatismPrescriptionLeft: components["schemas"]["AstigmatismPrescription"];
      addPowerLeft?: components["schemas"]["AddPower"];
      sphericalPowerRight: components["schemas"]["SphericalPower"];
      astigmatismPrescriptionRight: components["schemas"]["AstigmatismPrescription"];
      addPowerRight?: components["schemas"]["AddPower"];
      lensPint: components["schemas"]["LensPint"];
      salesColorNameId?: components["schemas"]["SalesColorNameId"];
      salesLensSpecId?: components["schemas"]["SalesLensSpecId"];
      focusCategoryId?: components["schemas"]["FocusCategoryId"];
      progressiveCategoryId?: components["schemas"]["ProgressiveCategoryId"];
      refractiveIndexNameId?: components["schemas"]["RefractiveIndexNameId"];
      countryCodeAlpha2: components["schemas"]["CountryCodeAlpha2"];
    };
    /** @description アイポイント測定チェックAPIリクエスト */
    EyepointMeasurePostRequest: {
      eyePointLeft?: components["schemas"]["EyePoint"];
      sphericalPowerLeft: components["schemas"]["SphericalPower"];
      astigmatismPrescriptionLeft: components["schemas"]["AstigmatismPrescription"];
      addPowerLeft?: components["schemas"]["AddPower"];
      eyePointRight?: components["schemas"]["EyePoint"];
      sphericalPowerRight: components["schemas"]["SphericalPower"];
      astigmatismPrescriptionRight: components["schemas"]["AstigmatismPrescription"];
      addPowerRight?: components["schemas"]["AddPower"];
      lensPint: components["schemas"]["LensPint"];
      /**
       * Format: int64
       * @description 販売用カラー名称ID
       * @example 123
       */
      salesColorNameId: number;
      /**
       * Format: int64
       * @description 販売用レンズ仕様ID
       * @example 123
       */
      salesLensSpecId: number;
      /**
       * Format: int64
       * @description 焦点分類ID
       * @example 123
       */
      focusCategoryId: number;
      /**
       * Format: int64
       * @description 累進分類ID
       * @example 123
       */
      progressiveCategoryId: number;
      /**
       * Format: int64
       * @description 屈折率名称ID
       * @example 123
       */
      refractiveIndexNameId: number;
      countryCodeAlpha2: components["schemas"]["CountryCodeAlpha2"];
    };
    /**
     * @description SPH（球面度数）
     * @example 123.12
     */
    SphericalPower: number;
    /**
     * @description CYL（乱視度数）
     * @example 123.12
     */
    AstigmatismPrescription: number;
    /**
     * @description E.P（アイポイント）
     * @example 123.12
     */
    EyePoint: number | null;
    /**
     * @description ADD（加入度数）
     * @example 1234.12
     */
    AddPower: number | null;
    /**
     * @description レンズピント
     * @example 1
     */
    LensPint: string;
    /**
     * Format: int64
     * @description 販売用カラー名称ID
     * @example 123
     */
    SalesColorNameId: number | null;
    /**
     * Format: int64
     * @description 販売用レンズ仕様ID
     * @example 123
     */
    SalesLensSpecId: number | null;
    /**
     * Format: int64
     * @description 焦点分類ID
     * @example 123
     */
    FocusCategoryId: number | null;
    /**
     * Format: int64
     * @description 累進分類ID
     * @example 123
     */
    ProgressiveCategoryId: number | null;
    /**
     * Format: int64
     * @description 屈折率名称ID
     * @example 123
     */
    RefractiveIndexNameId: number | null;
    /**
     * @description 販売国コード(国コード(alpha-2))
     * @example US
     */
    CountryCodeAlpha2: string;
    ApplicationError: {
      /**
       * Format: uuid
       * @description アプリケーションノード間のトレーサビリティを確保するためのID
       */
      "Jins-Trace-ID": string;
      /**
       * Format: date-time
       * @description エラー発生時刻
       */
      timestamp: string;
      /** @description エラーコード */
      code: string;
      /** @description システム名 */
      systemName: string;
      /** @description エラーメッセージ */
      message: string;
      /** @description エラー詳細 */
      details: string;
    };
  };
  responses: {
    /** @description Bad Request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Not Found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Conflict */
    Conflict: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Too Many Requests */
    TooManyRequests: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
  };
  parameters: {
    /** @description POST us/v1/jins/oauth/token で取得したOAuthのBearerトークン。<br>許可された値: Bearer {access_token} */
    Authorization: string;
    /** @description リソース・コンテンツのアプリケーション・メディアタイプ。<br>許可された値:application/json */
    "Content-Type": "application/json";
    /** @description リソース・コンテンツのアプリケーション・メディアタイプ。<br>許可された値:application/json */
    Accept: "application/json";
    /** @description 各アプリ・システムに対して環境ごとに払い出されたAPI認証キー */
    "X-API-KEY": string;
    /** @description 言語指定<br>デフォルト値:en<br>許可された値:en */
    "Accept-Language"?: "en";
    /** @description 取得開始位置<br>レスポンスヘッダで返却された X-Cursor の値を指定 */
    "X-Cursor"?: string;
    /**
     * @description アプリケーションノード間のトレーサビリティを確保するためのID
     * @example 2389c607-f5ed-4789-95a3-efd78be1e8d9
     */
    JinsTraceID: string;
    /**
     * @description jins-trace-idに紐付く呼出し枝番
     * @example 1
     */
    JinsTraceIdBranchNo?: string;
    /**
     * @description UI側でユーザを識別できるIDを格納
     * @example 00028
     */
    StaffID: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** health check */
  status: {
    responses: {
      /** @description success */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description failure */
      400: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  /** dummy function to call external API */
  dummy: {
    responses: {
      /** @description success */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description failure */
      400: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  /**
   * 度数組合せチェックAPI
   * @description 度数の組合せを確認し、組合せが妥当かを返却する
   */
  postEyesightCombi: {
    parameters: {
      header: {
        "Jins-Trace-ID": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        staffID: components["parameters"]["StaffID"];
      };
    };
    /** @description 度数組合せチェックリクエストボディ */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["EyesightCombiPostRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["EyesightCombiPostResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * アイポイント測定チェックAPI
   * @description アイポイントが必須であれば必須チェックを実施して結果を返却する
   */
  postEyepointMeasure: {
    parameters: {
      header: {
        "Jins-Trace-ID": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        staffID: components["parameters"]["StaffID"];
      };
    };
    /** @description アイポイント測定チェックリクエストボディ */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["EyepointMeasurePostRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["EyepointMeasurePostResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
