/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/warranty/warranties": {
    /** 保証書登録API */
    post: operations["postWarranties"];
  };
  "/warranty/warranties/{warrantyNumber}": {
    /**
     * 保証情報取得API
     * @description 保証書番号をキーに保証書・保証対象テーブルのレコードを取得する
     */
    get: operations["findWarranties"];
    /** 保証書更新API */
    put: operations["putWarranties"];
    /** 保証書削除API */
    delete: operations["deleteWarranties"];
    /** 保証書論理削除API */
    patch: operations["patchWarranties"];
  };
  "/warranty/warranty-histories": {
    /**
     * 保証履歴情報取得API
     * @description 保証書番号をキーに保証履歴テーブルのレコードを取得する（保証書番号、受付番号どちらかを指定しなければならない）
     */
    get: operations["findWarrantyHistories"];
    /** 保証履歴登録API */
    post: operations["postWarrantyHistories"];
  };
  "/warranty/warranty-histories/{receptionNumber}": {
    /** 保証履歴更新API */
    put: operations["putWarrantyHistories"];
  };
  "/warranty/powers": {
    /** 度数・処方箋登録API */
    post: operations["postPowers"];
  };
  "/warranty/powers/{powerId}": {
    /** 度数・処方箋削除API */
    delete: operations["deletePowers"];
  };
  "/warranty/powers-by-id/{powerId}": {
    /** 度数・処方箋情報取得API */
    get: operations["getPowers"];
    /** 度数・処方箋論理削除API */
    patch: operations["patchPowers"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description 商品タイプ（＝交換部位コード）
     * |コード|内容|備考|
     * |:---|:---|:---|
     * |000|All|L1での呼び名はSet ※JINS-Hubで使用|
     * |001|Frame|※JINS-Hubで使用|
     * |002|Lens Both|※JINS-Hubで使用|
     * |003|Lens Left||
     * |004|Lens Right||
     * <br>
     */
    itemType: string;
    /** @description 保証対象 */
    WarrantyItem: {
      itemType?: components["schemas"]["itemType"];
      /**
       * Format: date
       * @description 購入日（未使用）
       */
      purchaseDate?: string;
      /**
       * Format: date-time
       * @description 保証開始日
       */
      warrantyStartDate?: string | null;
      /** @description 保証書発行元チャネル */
      channel?: string;
    };
    /**
     * @description 保証書登録APIリクエスト
     * @example {
     *   "jinsAccountId": "adxgekljjo",
     *   "warrantyNumber": "241201US000001-1",
     *   "orderNumber": "USA123456",
     *   "receptionNumber": "241201US000001",
     *   "isExchangeLens": false,
     *   "powerId": 1234561234561234700,
     *   "storeCode": "83005",
     *   "customerName": "Yamada",
     *   "phoneNumber": "07011112222",
     *   "lensColorName": "Clear",
     *   "receiptDatetime": "2025-04-25T13:16:01",
     *   "frameItemCode": "MCF-17S-028-128",
     *   "lensNameCode": "LHK0000-M04M04M",
     *   "caseItemName": "Japan Gray Case",
     *   "warrantyItems": [
     *     {
     *       "itemType": "001",
     *       "purchaseDate": "2024-12-01",
     *       "warrantyStartDate": null,
     *       "channel": "S"
     *     },
     *     {
     *       "itemType": "003",
     *       "purchaseDate": "2024-12-01",
     *       "warrantyStartDate": null,
     *       "channel": "S"
     *     },
     *     {
     *       "itemType": "004",
     *       "purchaseDate": "2024-12-01",
     *       "warrantyStartDate": null,
     *       "channel": "S"
     *     }
     *   ]
     * }
     */
    WarrantiesPostRequest: {
      /** @description JINSアカウントID */
      jinsAccountId?: string | null;
      /** @description 保証書番号 */
      warrantyNumber?: string;
      /** @description オーダー番号 */
      orderNumber?: string;
      /** @description 受付番号 */
      receptionNumber?: string;
      /** @description レンズ交換フラグ */
      isExchangeLens?: boolean | null;
      /**
       * Format: int64
       * @description 度数ID
       */
      powerId?: number | null;
      /** @description 店舗コード */
      storeCode?: string;
      /** @description 顧客名 */
      customerName?: string;
      /** @description 電話番号 */
      phoneNumber?: string;
      /** @description レンズカラー名称 */
      lensColorName?: string | null;
      /**
       * Format: date-time
       * @description 受付日時
       */
      receiptDatetime?: string | null;
      /** @description フレームコード */
      frameItemCode?: string | null;
      /** @description レンズコード */
      lensNameCode?: string | null;
      /** @description ケース名 */
      caseItemName?: string | null;
      /** @description 保証対象 */
      warrantyItems?: components["schemas"]["WarrantyItem"][];
    };
    CommonErrorResponse: {
      code: string;
      message: string;
      details?: Record<string, never>;
    };
    /** @description 保証書情報 */
    warrantyItemInfo: {
      /**
       * Format: int64
       * @description 保証対象ID
       */
      warrantyItemId?: number;
      /** @description 保証書番号 */
      warrantyNumber?: string;
      /**
       * Format: date-time
       * @description 購入日
       */
      purchaseDate?: string;
      /**
       * Format: date-time
       * @description 保証開始日
       */
      warrantyStartDate?: string;
      /** @description 保証書発行元チャネル */
      channel?: string;
      /**
       * Format: int64
       * @description 店舗ID
       */
      storeId?: number;
      /** @description 店舗コード */
      storeCode?: string;
      itemType?: components["schemas"]["itemType"];
      /** @description 交換回数 */
      exchangeCount?: number;
      /** @description 削除フラグ */
      deletedFlag?: number;
      /** @description 楽観ロック用バージョン番号 */
      optimisticLockVerNo?: number;
    };
    /** @description 保証情報 */
    warrantyInfo: {
      /** @description 保証書番号 */
      warrantyNumber?: string;
      /** @description 受付番号 */
      receptionNumber?: string;
      /** @description オーダー番号 */
      orderNumber?: string;
      /** @description レンズ交換フラグ */
      isExchangeLens?: boolean;
      /**
       * Format: int64
       * @description 度数情報
       */
      powerId?: number;
      /**
       * Format: int64
       * @description 店舗ID
       */
      storeId?: number;
      /** @description 店舗コード */
      storeCode?: string;
      /** @description レンズコートコード */
      lensCoatCode?: string;
      /** @description レンズ加工情報コード */
      lensProcessingCode?: string;
      /** @description レンズカラーコード */
      lensColorName?: string;
      /** @description レンズタイプ */
      lensType?: string;
      /** @description 交換回数 */
      exchangeCount?: number;
      /** @description 削除フラグ */
      deletedFlag?: number;
      /** @description 楽観ロック用バージョン番号 */
      optimisticLockVerNo?: number;
      warrantyItems?: components["schemas"]["warrantyItemInfo"][];
    };
    /**
     * @description 保証情報取得APIレスポンス
     * @example {
     *   "warrantyInfo": {
     *     "warrantyNumber": "241201US000001-1",
     *     "receptionNumber": "241201US000001",
     *     "orderNumber": "USA123456",
     *     "isExchangeLens": false,
     *     "powerId": 1234561234561234700,
     *     "storeId": 1143416,
     *     "storeCode": "83005",
     *     "lensCoatCode": null,
     *     "lensProcessingCode": null,
     *     "lensColorName": null,
     *     "lensType": null,
     *     "exchangeCount": 1,
     *     "deletedFlag": 0,
     *     "optimisticLockVerNo": 1,
     *     "warrantyItems": [
     *       {
     *         "warrantyItemId": 1,
     *         "warrantyNumber": "2241201US000001-1",
     *         "purchaseDate": "2024-12-01T00:00:00",
     *         "warrantyStartDate": "2024-12-25T13:00:00",
     *         "channel": "S",
     *         "storeId": 1143416,
     *         "storeCode": "83005",
     *         "itemType": "003",
     *         "exchangeCount": 1,
     *         "deletedFlag": 0,
     *         "optimisticLockVerNo": 3
     *       },
     *       {
     *         "warrantyItemId": 2,
     *         "warrantyNumber": "2241201US000001-1",
     *         "purchaseDate": "2024-12-01T00:00:00",
     *         "warrantyStartDate": "2024-12-25T13:00:00",
     *         "channel": "S",
     *         "storeId": 1143416,
     *         "storeCode": "83005",
     *         "itemType": "002",
     *         "exchangeCount": 2,
     *         "deletedFlag": 0,
     *         "optimisticLockVerNo": 3
     *       }
     *     ]
     *   }
     * }
     */
    WarrantiesResponse: {
      warrantyInfo?: components["schemas"]["warrantyInfo"];
    };
    /** @description 保証書更新APIリクエスト */
    WarrantiesPutRequest: {
      /**
       * Format: date-time
       * @description 保証開始日
       * @example 2024-12-25T13:00:00
       */
      warrantyStartDate?: string | null;
    };
    /** @description 保証書論理削除APIリクエスト */
    WarrantyPatchRequest: {
      /**
       * @description 削除フラグ
       * @example 1
       */
      deletedFlag?: number;
      /**
       * @description 楽観ロック用バージョン番号
       * @example 1
       */
      optimisticLockVerNo?: number;
    };
    /** @description 保証履歴情報 */
    WarrantyHistories: {
      /**
       * Format: int64
       * @description 来客情報
       */
      visitorId?: number;
      /** @description 受付番号 */
      receptionNumber?: string;
      /** @description オーダー番号 */
      orderNumber?: string;
      /**
       * Format: date-time
       * @description 引換証出力日時
       */
      claimTicketCreatedAt?: string;
      /** @description 加工箱番号 */
      boxNo?: string;
      /** @description 保証書番号 */
      warrantyNumber?: string;
      /** @description 元受付番号 */
      previousReceptionNumber?: string;
      /** @description 元商品グループCD */
      previousItemgroupCode?: string;
      /**
       * Format: date-time
       * @description 受付日時
       */
      receiptDatetime?: string;
      /** @description 備考 */
      note?: string;
      /** @description 店舗スタッフ社員番号 */
      retailStoreStaffNo?: string;
      /** @description 受け渡し店舗スタッフ社員番号 */
      deliveryStoreStaffNo?: string;
      /**
       * Format: int64
       * @description 購入店舗ID
       */
      retailStoreId?: number;
      /**
       * Format: int64
       * @description 受け渡し店舗ID
       */
      deliveryStoreId?: number;
      /** @description 購入店舗コード */
      retailStoreCode?: string;
      /** @description 受け渡し店舗コード */
      deliveryStoreCode?: string;
      /** @description 保証対象アイテム */
      warrantyItemIdList?: number[];
      /** @description 保証箇所 */
      warrantyItemCodeList?: string[];
      /** @description 保証交換回数 */
      exchangedCount?: number;
      /**
       * Format: date-time
       * @description 保証書出力日時
       */
      warrantyCreatedAt?: string;
      /** @description レンズ交換 */
      lensExchange?: boolean;
      /** @description レンズ交換券フラグ */
      isExchangeLensTicket?: boolean;
      /** @description 会計-POS連携フラグ */
      isPosAccounting?: boolean;
      /** @description レンズ発注-SFDC連携フラグ */
      isSfdcLensOrder?: boolean;
      /** @description レンズ着-SFDC連携フラグ */
      isSfdcLensArrive?: boolean;
      /** @description 測定方法コード値 */
      measurementCode?: string;
      /** @description 署名画像ファイルURL */
      signatureFileUrl?: string;
      /** @description 署名ファイル名 */
      signatureFileName?: string;
      /** @description レンズ発注フラグ */
      isLensOrder?: boolean;
      /** @description 製作備考 - コード値 */
      codeProductionNote?: string[];
      /** @description 印刷用度数測定方法 */
      measurementTypeForPrint?: string;
      /** @description レンズ持ち込みフラグ */
      isFrameBringIn?: boolean;
      /** @description レンズ再発注フラグ */
      isLensReorder?: boolean;
      /** @description 配送先住所 */
      shippingAddress?: string;
      /**
       * Format: date
       * @description 配送日
       */
      shippingDate?: string;
      /** @description 配送方法コード */
      shippingMethodCode?: string;
      /** @description 配送先郵便番号 */
      shippingPostalCode?: string;
      /** @description CRMフラグ */
      crmFlag?: boolean;
      /**
       * Format: date
       * @description お渡し日
       */
      handOverDate?: string;
      /** @description お渡し方法 */
      handOverMethod?: string;
      /** @description 交換部位 */
      replacementPart?: string;
      /** @description 保証種類 */
      replacementType?: string;
      /** @description 交換理由 */
      replacementReason?: string;
      /** @description 保証回数加算フラグ */
      exchangeCountIncrementFlag?: boolean;
      /**
       * Format: int64
       * @description 交換店舗ID
       */
      replacementStoreId?: number;
      /** @description 交換店舗コード */
      replacementStoreCode?: string;
      /** @description 保証交換ステータスコード */
      replacementStatusCode?: string;
      /** @description 削除フラグ */
      deletedFlag?: number;
      /** @description 楽観ロック用バージョン番号 */
      optimisticLockVerNo?: number;
    };
    /**
     * @description 保証履歴取得APIレスポンス
     * @example {
     *   "warrantyHistories": [
     *     {
     *       "visitorId": null,
     *       "receptionNumber": "241201US000008",
     *       "orderNumber": null,
     *       "claimTicketCreatedAt": null,
     *       "boxNo": null,
     *       "warrantyNumber": "241201US000001-1",
     *       "previousReceptionNumber": "241201US000007",
     *       "previousItemgroupCode": "241201US000007-1",
     *       "receiptDatetime": "2025-12-25T13:16:01",
     *       "note": null,
     *       "retailStoreStaffNo": "jins-user-id",
     *       "deliveryStoreStaffNo": null,
     *       "retailStoreId": 1143416,
     *       "deliveryStoreId": 1143416,
     *       "retailStoreCode": "83005",
     *       "deliveryStoreCode": "83005",
     *       "warrantyItemIdList": null,
     *       "warrantyItemCodeList": null,
     *       "exchangedCount": 1,
     *       "warrantyCreatedAt": "2025-12-25T13:16:01",
     *       "lensExchange": true,
     *       "isExchangeLensTicket": null,
     *       "isPosAccounting": null,
     *       "isSfdcLensOrder": null,
     *       "isSfdcLensArrive": null,
     *       "measurementCode": null,
     *       "signatureFileUrl": null,
     *       "signatureFileName": null,
     *       "isLensOrder": null,
     *       "codeProductionNote": null,
     *       "measurementTypeForPrint": null,
     *       "isFrameBringIn": null,
     *       "isLensReorder": null,
     *       "shippingAddress": null,
     *       "shippingDate": null,
     *       "shippingMethodCode": null,
     *       "shippingPostalCode": null,
     *       "crmFlag": false,
     *       "handOverDate": null,
     *       "handOverMethod": null,
     *       "replacementPart": "004",
     *       "replacementType": "001",
     *       "replacementReason": "002",
     *       "exchangeCountIncrementFlag": true,
     *       "replacementStoreId": 1143416,
     *       "replacementStoreCode": "83005",
     *       "replacementStatusCode": "010",
     *       "deletedFlag": 0,
     *       "optimisticLockVerNo": 1
     *     },
     *     {
     *       "visitorId": null,
     *       "receptionNumber": "241201US000009",
     *       "orderNumber": null,
     *       "claimTicketCreatedAt": null,
     *       "boxNo": null,
     *       "warrantyNumber": "241201US000001-1",
     *       "previousReceptionNumber": "241201US000008",
     *       "previousItemgroupCode": "241201US000001-1",
     *       "receiptDatetime": "2025-12-25T13:16:01",
     *       "note": null,
     *       "retailStoreStaffNo": "jins-user-id",
     *       "deliveryStoreStaffNo": null,
     *       "retailStoreId": 1143416,
     *       "deliveryStoreId": 1143416,
     *       "retailStoreCode": "83005",
     *       "deliveryStoreCode": "83005",
     *       "warrantyItemIdList": null,
     *       "warrantyItemCodeList": null,
     *       "exchangedCount": 1,
     *       "warrantyCreatedAt": "2025-12-25T13:16:01",
     *       "lensExchange": true,
     *       "isExchangeLensTicket": null,
     *       "isPosAccounting": null,
     *       "isSfdcLensOrder": null,
     *       "isSfdcLensArrive": null,
     *       "measurementCode": null,
     *       "signatureFileUrl": null,
     *       "signatureFileName": null,
     *       "isLensOrder": null,
     *       "codeProductionNote": null,
     *       "measurementTypeForPrint": null,
     *       "isFrameBringIn": null,
     *       "isLensReorder": null,
     *       "shippingAddress": null,
     *       "shippingDate": null,
     *       "shippingMethodCode": null,
     *       "shippingPostalCode": null,
     *       "crmFlag": false,
     *       "handOverDate": null,
     *       "handOverMethod": null,
     *       "replacementPart": "004",
     *       "replacementType": "001",
     *       "replacementReason": "002",
     *       "exchangeCountIncrementFlag": true,
     *       "replacementStoreId": 1143416,
     *       "replacementStoreCode": "83005",
     *       "replacementStatusCode": "010",
     *       "deletedFlag": 0,
     *       "optimisticLockVerNo": 1
     *     }
     *   ]
     * }
     */
    WarrantyHistoriesResponse: {
      warrantyHistories?: components["schemas"]["WarrantyHistories"][];
    };
    /** @description 保証履歴登録APIリクエスト */
    WarrantyHistoriesPostRequest: {
      /**
       * @description 保証書番号
       * @example 241230US000001-1
       */
      warrantyNumber?: string;
      /**
       * @description 受付番号
       * @example 241230US000001
       */
      receptionNumber?: string;
      /**
       * @description 交換種別
       * @example 002
       */
      replacementType?: string;
      /**
       * @description 交換部位
       * @example 002
       */
      replacementPart?: string;
      /**
       * @description 交換理由
       * @example 002
       */
      replacementReason?: string;
      /**
       * @description 交換回数カウント可否
       * @example false
       */
      exchangeCountIncrementFlag?: boolean;
      /**
       * Format: int64
       * @description 交換受付店舗ID
       * @example 83005
       */
      replacementStoreId?: number | null;
      /**
       * Format: date-time
       * @description 交換受付日時
       */
      receiptDatetime?: string | null;
      /**
       * @description JINSアカウントID
       * @example adxgekljjo
       */
      jinsAccountId?: string | null;
    };
    /**
     * @description 保証交換ステータスコード
     * |コード|意味|
     * |:---|:---|
     * |000|初期登録|
     * |010|一次保存|
     * |011|交換中|
     * |020|交換済|
     * <br>
     *
     * @example 020
     */
    replacementStatusCode: string;
    /** @description 保証書更新用オブジェクト */
    WarrantyForUpdate: {
      /** @description 保証書番号 */
      warrantyNumber?: string;
      /** @description 交換回数 */
      exchangeCount?: number;
      /** @description 削除フラグ */
      deletedFlag?: number;
      /** @description 楽観ロック用バージョン番号 */
      optimisticLockVerNo?: number | null;
    };
    /** @description 保証対象更新用オブジェクト */
    WarrantyItemForUpdate: {
      itemType?: components["schemas"]["itemType"];
      /** @description 交換回数 */
      exchangeCount?: number;
      /** @description 削除フラグ */
      deletedFlag?: number;
      /** @description 楽観ロック用バージョン番号 */
      optimisticLockVerNo?: number | null;
    };
    /**
     * @description 保証履歴更新APIリクエスト
     * @example {
     *   "replacementStatusCode": "011",
     *   "frameItemCode": "MCF-17S-028-128",
     *   "lensNameCode": "LHK0000-M04M04M",
     *   "caseItemName": "Japan Gray Case",
     *   "deletedFlag": 0,
     *   "optimisticLockVerNo": 1,
     *   "warranty": {
     *     "warrantyNumber": "20250103US00001-2",
     *     "exchangeCount": 1,
     *     "deletedFlag": 0,
     *     "optimisticLockVerNo": 1
     *   },
     *   "warrantyItems": [
     *     {
     *       "itemType": "003",
     *       "exchangeCount": 1,
     *       "deletedFlag": 0,
     *       "optimisticLockVerNo": 1
     *     },
     *     {
     *       "itemType": "004",
     *       "exchangeCount": 1,
     *       "deletedFlag": 0,
     *       "optimisticLockVerNo": 1
     *     }
     *   ]
     * }
     */
    WarrantyHistoriesPutRequest: {
      replacementStatusCode?: components["schemas"]["replacementStatusCode"];
      /** @description フレームコード */
      frameItemCode?: string | null;
      /** @description レンズコード */
      lensNameCode?: string | null;
      /** @description ケース名 */
      caseItemName?: string | null;
      /** @description 削除フラグ */
      deletedFlag?: number;
      /** @description 楽観ロック用バージョン番号 */
      optimisticLockVerNo?: number | null;
      warranty?: components["schemas"]["WarrantyForUpdate"];
      /** @description 保証対象更新情報 */
      warrantyItems?: components["schemas"]["WarrantyItemForUpdate"][];
    };
    /**
     * @description 度数登録方法
     * |コード|名称（日本語）|名称（英語）|
     * |:---|:---|:---|
     * |001|測定|measurement|
     * |002|処方箋|prescription|
     * |003|JB|JB|
     * |004|度数不要|not necessary|
     * |005|JINSアプリ|JINS app|
     * |006|手動入力|Manual enter|
     */
    registrationMethodCode: string | null;
    /**
     * @description 度数・処方箋登録APIリクエスト
     * @example {
     *   "powerId": 0,
     *   "addLeft": 0,
     *   "addRight": 0,
     *   "axisLeft": 0,
     *   "axisRight": 0,
     *   "baseVLeft": "BO",
     *   "baseVRight": "BI",
     *   "baseHLeft": "BU",
     *   "baseHRight": "BD",
     *   "cylLeft": 8.75,
     *   "cylRight": 8.75,
     *   "pdLeft": 0,
     *   "pdRight": 0,
     *   "prism01Left": 0,
     *   "prism01Right": 0,
     *   "prism02Left": 0,
     *   "prism02Right": 0,
     *   "sphLeft": -0.5,
     *   "sphRight": -0.25,
     *   "eyepointLeft": 2,
     *   "eyepointRight": 2,
     *   "vision": 1,
     *   "perspectiveTypeCode": "2",
     *   "prismFlag": true,
     *   "powerItem": {
     *     "prescriptionId": 1,
     *     "channel": "Physical Store",
     *     "custmeName": "AShley Jins",
     *     "jinsAccountId": "12345678",
     *     "expirationDate": "2025-03-25T15:00:00",
     *     "prescriptionFileName": "aaa",
     *     "registrationMethodCode": "006"
     *   }
     * }
     */
    PowersPostRequest: {
      /**
       * Format: int64
       * @description 度数ID
       */
      powerId?: number | null;
      /** @description 加入度数(L)、累進レンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      addLeft?: number | null;
      /** @description 加入度数(R)、累進レンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      addRight?: number | null;
      /** @description AXS(L)、小数点なし。プラス・マイナス表記なし。 */
      axisLeft?: number | null;
      /** @description AXS(R)、小数点なし。プラス・マイナス表記なし。 */
      axisRight?: number | null;
      /** @description ベースV_L、プリズムレンズで必須(BU/BD) */
      baseVLeft?: string | null;
      /** @description ベースV_R、プリズムレンズで必須(BU/BD) */
      baseVRight?: string | null;
      /** @description ベースH_L、プリズムレンズで必須(BI/BO) */
      baseHLeft?: string | null;
      /** @description ベースH_R、プリズムレンズで必須(BI/BO) */
      baseHRight?: string | null;
      /** @description CYL(L)、小数点以下2桁まで。プラス・マイナス表記あり。 */
      cylLeft?: number | null;
      /** @description CYL(R)、小数点以下2桁まで。プラス・マイナス表記あり。 */
      cylRight?: number | null;
      /** @description PD(L)、小数点以下2桁まで。プラス・マイナス表記なし。 */
      pdLeft?: number | null;
      /** @description PD(R)、小数点以下2桁まで。プラス・マイナス表記なし。 */
      pdRight?: number | null;
      /** @description プリズム01_L、プリズムレンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      prism01Left?: number | null;
      /** @description プリズム01_R、プリズムレンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      prism01Right?: number | null;
      /** @description プリズム02_L、プリズムレンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      prism02Left?: number | null;
      /** @description プリズム02_R、プリズムレンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      prism02Right?: number | null;
      /** @description SPH(L)、小数点以下2桁まで。プラス・マイナス表記あり。 */
      sphLeft?: number | null;
      /** @description SPH(R)、小数点以下2桁まで。プラス・マイナス表記あり。 */
      sphRight?: number | null;
      /** @description アイポイント(L)、小数点以下1桁まで、プラス・マイナス表記あり。 */
      eyepointLeft?: number | null;
      /** @description アイポイント(R)、小数点以下1桁まで、プラス・マイナス表記あり。 */
      eyepointRight?: number | null;
      /** @description 矯正両目視力(maxLength仮)(9-11スコープではNull) */
      vision?: number | null;
      /** @description 遠中近区分コード */
      perspectiveTypeCode?: string | null;
      /** @description プリズムレンズかどうかを判定するフラグ */
      prismFlag?: boolean | null;
      /** @description 処方箋情報 */
      powerItem?: {
        /**
         * Format: int64
         * @description 処方箋ID
         */
        prescriptionId?: number | null;
        /** @description 処方箋登録元チャネル */
        channel?: string;
        /** @description 顧客名 */
        customerName?: string;
        /** @description JINSアカウントID */
        jinsAccountId?: string;
        /**
         * Format: date-time
         * @description 処方箋有効期限
         */
        expirationDate?: string | null;
        /** @description 処方箋ファイル名 */
        prescriptionFileName?: string | null;
        registrationMethodCode?: components["schemas"]["registrationMethodCode"];
      };
    };
    /** @description 度数・処方箋登録APIレスポンス */
    PowersPostResponse: {
      /**
       * @description 度数ID
       * @example 1111
       */
      powerId?: number;
      /**
       * @description 処方箋ID
       * @example 2222
       */
      prescriptionId?: number;
    };
    /**
     * @description 度数・処方箋取得APIレスポンス
     * @example {
     *   "powerId": 0,
     *   "addLeft": 0,
     *   "addRight": 0,
     *   "axisLeft": 0,
     *   "axisRight": 0,
     *   "baseVLeft": "BO",
     *   "baseVRight": "BI",
     *   "baseHLeft": "BU",
     *   "baseHRight": "BD",
     *   "cylLeft": 8.75,
     *   "cylRight": 8.75,
     *   "pdLeft": 0,
     *   "pdRight": 0,
     *   "prism01Left": 0,
     *   "prism01Right": 0,
     *   "prism02Left": 0,
     *   "prism02Right": 0,
     *   "sphLeft": -0.5,
     *   "sphRight": -0.25,
     *   "eyepointLeft": 2,
     *   "eyepointRight": 2,
     *   "vision": 1,
     *   "perspectiveTypeCode": "2",
     *   "prismFlag": true,
     *   "PowerItem": {
     *     "prescriptionId": 1,
     *     "channel": "Physical Store",
     *     "custmeName": "AShley Jins",
     *     "jinsAccountId": "12345678",
     *     "expirationDate": "2025-03-25T15:00:00",
     *     "prescriptionFileName": "aaa",
     *     "registrationMethodCode": "006"
     *   }
     * }
     */
    PowersGetResponse: {
      /**
       * Format: int64
       * @description 度数ID
       */
      powerId?: number | null;
      /** @description 加入度数(L)、累進レンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      addLeft?: number | null;
      /** @description 加入度数(R)、累進レンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      addRight?: number | null;
      /** @description AXS(L)、小数点なし。プラス・マイナス表記なし。 */
      axisLeft?: number | null;
      /** @description AXS(R)、小数点なし。プラス・マイナス表記なし。 */
      axisRight?: number | null;
      /** @description ベースV_L、プリズムレンズで必須(BU/BD) */
      baseVLeft?: string | null;
      /** @description ベースV_R、プリズムレンズで必須(BU/BD) */
      baseVRight?: string | null;
      /** @description ベースH_L、プリズムレンズで必須(BI/BO) */
      baseHLeft?: string | null;
      /** @description ベースH_R、プリズムレンズで必須(BI/BO) */
      baseHRight?: string | null;
      /** @description CYL(L)、小数点以下2桁まで。プラス・マイナス表記あり。 */
      cylLeft?: number | null;
      /** @description CYL(R)、小数点以下2桁まで。プラス・マイナス表記あり。 */
      cylRight?: number | null;
      /** @description PD(L)、小数点以下2桁まで。プラス・マイナス表記なし。 */
      pdLeft?: number | null;
      /** @description PD(R)、小数点以下2桁まで。プラス・マイナス表記なし。 */
      pdRight?: number | null;
      /** @description プリズム01_L、プリズムレンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      prism01Left?: number | null;
      /** @description プリズム01_R、プリズムレンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      prism01Right?: number | null;
      /** @description プリズム02_L、プリズムレンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      prism02Left?: number | null;
      /** @description プリズム02_R、プリズムレンズで必須、小数点以下2桁まで。プラス・マイナス表記なし。 */
      prism02Right?: number | null;
      /** @description SPH(L)、小数点以下2桁まで。プラス・マイナス表記あり。 */
      sphLeft?: number | null;
      /** @description SPH(R)、小数点以下2桁まで。プラス・マイナス表記あり。 */
      sphRight?: number | null;
      /** @description アイポイント(L)、小数点以下1桁まで、プラス・マイナス表記あり。 */
      eyepointLeft?: number | null;
      /** @description アイポイント(R)、小数点以下1桁まで、プラス・マイナス表記あり。 */
      eyepointRight?: number | null;
      /** @description 矯正両目視力(maxLength仮)(9-11スコープではNull) */
      vision?: number | null;
      /** @description 遠中近区分コード */
      perspectiveTypeCode?: string | null;
      /** @description プリズムレンズかどうかを判定するフラグ */
      prismFlag?: boolean | null;
      /** @description 処方箋情報 */
      PowerItem?: {
        /**
         * Format: int64
         * @description 処方箋ID
         */
        prescriptionId?: number | null;
        /** @description 処方箋登録元チャネル */
        channel?: string | null;
        /** @description 顧客名 */
        customerName?: string | null;
        /** @description JINSアカウントID */
        jinsAccountId?: string | null;
        /**
         * Format: date-time
         * @description 処方箋有効期限
         */
        expirationDate?: string | null;
        /** @description 処方箋ファイル名 */
        prescriptionFileName?: string | null;
        registrationMethodCode?: components["schemas"]["registrationMethodCode"];
      };
    };
    /** @description 度数・処方箋論理削除APIリクエスト */
    PowerPatchRequest: {
      /**
       * @description 削除フラグ
       * @example 1
       */
      deletedFlag?: number;
      /**
       * @description 楽観ロック用バージョン番号
       * @example 1
       */
      optimisticLockVerNo?: number;
    };
  };
  responses: {
    /** @description Bad Request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Not Found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Too Many Requests */
    TooManyRequests: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Conflict */
    Conflict: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
  };
  parameters: {
    /**
     * @description アプリケーションノード間のトレーサビリティを確保するためのID
     * @example 2389c607-f5ed-4789-95a3-efd78be1e8d9
     */
    JinsTraceID: string;
    /**
     * @description jins-trace-idに紐付く呼出し枝番
     * @example 1
     */
    JinsTraceIdBranchNo?: string;
    /**
     * @description UI側でユーザを識別できるIDを格納
     * @example U00001
     */
    JinsUserID: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** 保証書登録API */
  postWarranties: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
    };
    /** @description 保証書登録APIのリクエストボディ */
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarrantiesPostRequest"];
      };
    };
    responses: {
      /** @description OK */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * 保証情報取得API
   * @description 保証書番号をキーに保証書・保証対象テーブルのレコードを取得する
   */
  findWarranties: {
    parameters: {
      query?: {
        /** @description 削除レコード取得フラグ */
        deleteFlag?: boolean;
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
      path: {
        /** @description 保証書番号 */
        warrantyNumber: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["WarrantiesResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 保証書更新API */
  putWarranties: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
      path: {
        /** @description 保証書番号 */
        warrantyNumber: string;
      };
    };
    /** @description 保証書更新APIのリクエストボディ */
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarrantiesPutRequest"];
      };
    };
    responses: {
      /** @description OK */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 保証書削除API */
  deleteWarranties: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
      path: {
        /** @description 保証書番号 */
        warrantyNumber: string;
      };
    };
    responses: {
      /** @description OK */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 保証書論理削除API */
  patchWarranties: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
      path: {
        /** @description 保証書番号 */
        warrantyNumber: string;
      };
    };
    /** @description 保証書論理削除APIのリクエストボディ */
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarrantyPatchRequest"];
      };
    };
    responses: {
      /** @description OK */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * 保証履歴情報取得API
   * @description 保証書番号をキーに保証履歴テーブルのレコードを取得する（保証書番号、受付番号どちらかを指定しなければならない）
   */
  findWarrantyHistories: {
    parameters: {
      query?: {
        /** @description 保証書番号 */
        warrantyNumber?: string;
        /** @description 受付番号 */
        receptionNumber?: string;
        /** @description 保証交換ステータスコード(複数指定の場合、カンマ区切り) */
        replacementStatusCode?: string;
        /** @description 削除レコード取得フラグ */
        deleteFlag?: boolean;
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["WarrantyHistoriesResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 保証履歴登録API */
  postWarrantyHistories: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
    };
    /** @description 保証履歴登録APIのリクエストボディ */
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarrantyHistoriesPostRequest"];
      };
    };
    responses: {
      /** @description OK */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 保証履歴更新API */
  putWarrantyHistories: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
      path: {
        /** @description 受付番号 */
        receptionNumber: string;
      };
    };
    /** @description 保証履歴更新APIのリクエストボディ */
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarrantyHistoriesPutRequest"];
      };
    };
    responses: {
      /** @description OK */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 度数・処方箋登録API */
  postPowers: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
    };
    /** @description 度数・処方箋登録APIのリクエストボディ */
    requestBody: {
      content: {
        "application/json": components["schemas"]["PowersPostRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PowersPostResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 度数・処方箋削除API */
  deletePowers: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
      path: {
        /** @description 度数ID */
        powerId: number;
      };
    };
    responses: {
      /** @description OK */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 度数・処方箋情報取得API */
  getPowers: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
      path: {
        /** @description 度数ID */
        powerId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PowersGetResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 度数・処方箋論理削除API */
  patchPowers: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["JinsUserID"];
      };
      path: {
        /** @description 度数ID */
        powerId: number;
      };
    };
    /** @description 度数・処方箋論理削除APIのリクエストボディ */
    requestBody: {
      content: {
        "application/json": components["schemas"]["PowerPatchRequest"];
      };
    };
    responses: {
      /** @description OK */
      204: {
        content: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
