const PresenterTypes = {
  IStatusPresenter: Symbol.for("IStatusPresenter"),
  INotFoundPresenter: Symbol.for("INotFoundPresenter"),
  IDummyPresenter: Symbol.for("IDummyPresenter"),
  IReceptionsPresenter: Symbol.for("IReceptionsPresenter"),
  IReceptionInfoPresenter: Symbol.for("IReceptionInfoPresenter"),
  IStoreByCodePresenter: Symbol.for("IStoreByCodePresenter"),
  IItemCaseInfoPresenter: Symbol.for("IItemCaseInfoPresenter"),
  IItemSalesColorInfoPresenter: Symbol.for("IItemSalesColorInfoPresenter"),
  IItemSalesLensSpecInfoPresenter: Symbol.for("IItemSalesLensSpecInfoPresenter"),
  IItemSalesLensAttributesInfoPresenter: Symbol.for("IItemSalesLensAttributesInfoPresenter"),
  IReceptionEventPresenter: Symbol.for("IReceptionEventPresenter"),
  IReceptionEventCancelPresenter: Symbol.for("IReceptionEventCancelPresenter"),
  IReceptionTicketPresenter: Symbol.for("IReceptionTicketPresenter"),
  ICartInfoPresenter: Symbol.for("ICartInfoPresenter"),
  IOrderInfoPresenter: Symbol.for("IOrderInfoPresenter"),
  IDeliveriesCheckPresenter: Symbol.for("IDeliveriesCheckPresenter"),
  IDeliveriesPresenter: Symbol.for("IDeliveriesPresenter"),
  IPrescriptionsInfoPresenter: Symbol.for("IPrescriptionsInfoPresenter"),
  IOrdersPresenter: Symbol.for("IOrdersPresenter"),
  IStaffLoginPresenter: Symbol.for("IStaffLoginPresenter"),
  ICallManagementInfoPresenter: Symbol.for("ICallManagementInfoPresenter"),
  ICallManagementUpdatePresenter : Symbol.for("ICallManagementUpdatePresenter"),
  IItemGroupPostPresenter: Symbol.for("IItemGroupPostPresenter"),
  IItemGroupDeletePresenter: Symbol.for("IItemGroupDeletePresenter"),
  IOrderSearchPresenter: Symbol.for("IOrderSearchPresenter"),
  IOrderCancelPresenter: Symbol.for("IOrderCancelPresenter"),
  IProcessesListPresenter: Symbol.for("IProcessesListPresenter"),
  IReceptionEventCustomerPresenter: Symbol.for("IReceptionEventCustomerPresenter"),
  IOrderStatusUpdatePresenter: Symbol.for("IOrderStatusUpdatePresenter"),
  ICallingStatusUpdatePresenter: Symbol.for("ICallingStatusUpdatePresenter"),
  IWarrantyReplacementsPostPresenter: Symbol.for("IWarrantyReplacementsPostPresenter"),
  IWarrantiesInfoPresenter: Symbol.for("IWarrantiesInfoPresenter"),
  IJobTicketsPresenter: Symbol.for("IJobTicketsPresenter"),
  IReceptionsSearchPresenter: Symbol.for("IReceptionsSearchPresenter")
};

export { PresenterTypes };
