/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/location/locations": {
    /**
     * ロケーションマスタ検索API
     * @description 必須のクエリパラメータは存在しません。<br> クエリパラメータを指定しない場合は、すべての検索結果が返されます。 総件数や取得件数は親のカウントです。
     */
    get: operations["getLocations"];
  };
  "/location/location-major-classes": {
    /**
     * ロケーション大分類マスタ検索API
     * @description 必須のクエリパラメータは存在しません。<br> クエリパラメータを指定しない場合は、すべての検索結果が返されます。
     */
    get: operations["getLocationMajorClasses"];
  };
  "/location/location-minor-classes": {
    /**
     * ロケーション小分類マスタ検索API
     * @description 必須のクエリパラメータは存在しません。<br> クエリパラメータを指定しない場合は、すべての検索結果が返されます。 総件数や取得件数は親のカウントです。
     */
    get: operations["getLocationMinorClasses"];
  };
  "/location/countries": {
    /** 国マスタ検索API */
    get: operations["getCountries"];
  };
  "/location/stores-attributes": {
    /**
     * 店舗属性マスタ検索API
     * @description 必須のクエリパラメータは存在しません。<br> クエリパラメータを指定しない場合は、すべての検索結果が返されます。 総件数や取得件数は親のカウントです。
     */
    get: operations["getStoresAttributes"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description 取得制限数
     * @default 100000
     * @example 20
     */
    Limit: number;
    /**
     * @description 取得開始位置
     * @default 0
     * @example 0
     */
    Offset: number;
    /**
     * @description 今回取得件数
     * @example 20
     */
    Count: number;
    /**
     * @description 総件数
     * @example 10000
     */
    TotalResults: number;
    /**
     * @description 次回データ存在有無
     * @example true
     */
    HasMore: boolean;
    LocationGetResponse: {
      /**
       * Format: int64
       * @description ロケーションID
       * @example 1143001
       */
      locationId?: number;
      /**
       * @description ロケーション区分
       * @example 6001
       */
      locationDivision?: string | null;
      /**
       * @description ロケーションコード
       * @example 89001
       */
      locationCode?: string;
      /**
       * @description ロケーション名
       * @example JINS Valley Fair
       */
      locationName?: string;
      /**
       * @description 郵便番号
       * @example 95050
       */
      postalCode?: string | null;
      /**
       * @description 住所1
       * @example 2855 Stevens Creek Boulevard
       */
      address1?: string | null;
      /**
       * @description 住所2
       * @example Santa Clara
       */
      address2?: string | null;
      /**
       * @description 住所3
       * @example CA 95050
       */
      address3?: string | null;
      /**
       * @description 住所4
       * @example Level 2, next to Old Navy
       */
      address4?: string | null;
      /**
       * @description 緯度
       * @example 37.325137
       */
      latitude?: number | null;
      /**
       * @description 経度
       * @example -121.946243
       */
      longitude?: number | null;
      /**
       * @description タイムゾーン
       * @example America/Los_Angeles
       */
      timezone?: string | null;
      /**
       * @description 電話番号（代表）
       * @example 1 (609) 681-2485
       */
      primaryPhoneNumber?: string | null;
      /**
       * Format: date
       * @description 開業日<br>※現地時間
       * @example 2024-01-01
       */
      openingDate?: string | null;
      /**
       * Format: date
       * @description 閉業日<br>※現地時間
       * @example 2024-01-31
       */
      closingDate?: string | null;
      /**
       * Format: Int32
       * @description 削除フラグ
       */
      deletedFlag?: number;
      /**
       * @description 更新者ID
       * @example Usa00001
       */
      updatedUserId?: string;
      /**
       * Format: date-time
       * @description 更新日時
       * @example 2024-01-01T11:11:00
       */
      updatedDatetime?: string;
      locationMajorClass?: {
        /**
         * Format: int64
         * @description ロケーション大分類ID
         * @example 100001
         */
        locationMajorClassId?: number;
        /**
         * @description ロケーション大分類コード
         * @example 1
         */
        locationMajorClassCode?: string;
        /**
         * @description ロケーション大分類名
         * @example Store
         */
        locationMajorClassName?: string;
        /**
         * Format: int32
         * @description 表示順
         * @example 1
         */
        displayOrder?: number;
      };
      locationMinorClass?: {
        /**
         * Format: int64
         * @description ロケーション小分類ID
         * @example 10011
         */
        locationMinorClassId?: number;
        /**
         * @description ロケーション小分類コード
         * @example 1
         */
        locationMinorClassCode?: string;
        /**
         * @description ロケーション小分類名
         * @example Regular store
         */
        locationMinorClassName?: string;
        /**
         * Format: int32
         * @description 在庫保有フラグ
         */
        inventoryHoldingFlag?: number | null;
        /**
         * Format: int32
         * @description 受付業務可能フラグ
         */
        receptionFlag?: number | null;
        /**
         * Format: int32
         * @description 測定業務可能フラグ
         */
        examFlag?: number | null;
        /**
         * Format: int32
         * @description 会計業務可能フラグ
         */
        checkoutFlag?: number | null;
        /**
         * Format: int32
         * @description 加工業務可能フラグ
         */
        processingFlag?: number | null;
        /**
         * Format: int32
         * @description 調整・お渡し業務可能フラグ
         */
        adjustmentPickupFlag?: number | null;
        /**
         * Format: int32
         * @description コンタクト販売可能フラグ
         */
        contactLensSalesFlag?: number | null;
        /**
         * Format: int32
         * @description 保証業務可能フラグ
         */
        warrantyFlag?: number | null;
        /**
         * Format: int32
         * @description 表示順
         * @example 1
         */
        displayOrder?: number;
      };
      country?: {
        /**
         * Format: int64
         * @description 国ID
         * @example 91000000001
         */
        countryId?: number;
        /**
         * @description 国コード(alpha-2)
         * @example JP
         */
        countryCodeAlpha2?: string;
        /**
         * @description 国コード(alpha-3)
         * @example JPN
         */
        countryCodeAlpha3?: string | null;
        /**
         * @description 国名
         * @example Japan
         */
        countryName?: string;
      };
    };
    LocationsGetResponse: {
      offset?: components["schemas"]["Offset"];
      count?: components["schemas"]["Count"];
      limit?: components["schemas"]["Limit"];
      totalResults?: components["schemas"]["TotalResults"];
      hasMore?: components["schemas"]["HasMore"];
      records?: components["schemas"]["LocationGetResponse"][];
    };
    CommonErrorResponse: {
      code: string;
      message: string;
      details?: Record<string, never>;
    };
    LocationMajorClassGetResponse: {
      /**
       * Format: int64
       * @description ロケーション大分類ID
       * @example 100001
       */
      locationMajorClassId?: number;
      /**
       * @description ロケーション大分類コード
       * @example 1
       */
      locationMajorClassCode?: string;
      /**
       * @description ロケーション大分類名
       * @example Store
       */
      locationMajorClassName?: string;
      /**
       * Format: int32
       * @description 表示順
       */
      displayOrder?: number;
      /**
       * Format: Int32
       * @description 削除フラグ
       */
      deletedFlag?: number;
      /**
       * @description 更新者ID
       * @example Usa00001
       */
      updatedUserId?: string;
      /**
       * Format: date-time
       * @description 更新日時
       * @example 2024-01-01T11:11:00
       */
      updatedDatetime?: string;
    };
    LocationMajorClassesGetResponse: {
      offset?: components["schemas"]["Offset"];
      count?: components["schemas"]["Count"];
      limit?: components["schemas"]["Limit"];
      totalResults?: components["schemas"]["TotalResults"];
      hasMore?: components["schemas"]["HasMore"];
      records?: components["schemas"]["LocationMajorClassGetResponse"][];
    };
    LocationMinorClassGetResponse: {
      /**
       * Format: int64
       * @description ロケーション小分類ID
       * @example 10011
       */
      locationMinorClassId?: number;
      /**
       * @description ロケーション小分類コード
       * @example 1
       */
      locationMinorClassCode?: string;
      /**
       * @description ロケーション小分類名
       * @example Regular store
       */
      locationMinorClassName?: string;
      /**
       * Format: Int32
       * @description 在庫保有フラグ
       */
      inventoryHoldingFlag?: number | null;
      /**
       * Format: Int32
       * @description 受付業務可能フラグ
       */
      receptionFlag?: number | null;
      /**
       * Format: Int32
       * @description 測定業務可能フラグ
       */
      examFlag?: number | null;
      /**
       * Format: Int32
       * @description 会計業務可能フラグ
       */
      checkoutFlag?: number | null;
      /**
       * Format: Int32
       * @description 加工業務可能フラグ
       */
      processingFlag?: number | null;
      /**
       * Format: Int32
       * @description 調整・お渡し業務可能フラグ
       */
      adjustmentPickupFlag?: number | null;
      /**
       * Format: Int32
       * @description コンタクト販売可能フラグ
       */
      contactLensSalesFlag?: number | null;
      /**
       * Format: Int32
       * @description 保証業務可能フラグ
       */
      warrantyFlag?: number | null;
      /**
       * Format: int32
       * @description 表示順
       * @example 1
       */
      displayOrder?: number;
      /**
       * Format: Int32
       * @description 削除フラグ
       */
      deletedFlag?: number;
      /**
       * @description 更新者ID
       * @example Usa00001
       */
      updatedUserId?: string;
      /**
       * Format: date-time
       * @description 更新日時
       * @example 2024-01-01T11:11:00
       */
      updatedDatetime?: string;
      locationMajorClass?: {
        /**
         * Format: int64
         * @description ロケーション大分類ID
         * @example 100001
         */
        locationMajorClassId?: number;
        /**
         * @description ロケーション大分類コード
         * @example 1
         */
        locationMajorClassCode?: string;
        /**
         * @description ロケーション大分類名
         * @example Store
         */
        locationMajorClassName?: string;
        /**
         * Format: int32
         * @description 表示順
         * @example 1
         */
        displayOrder?: number;
      };
    };
    LocationMinorClassesGetResponse: {
      offset?: components["schemas"]["Offset"];
      count?: components["schemas"]["Count"];
      limit?: components["schemas"]["Limit"];
      totalResults?: components["schemas"]["TotalResults"];
      hasMore?: components["schemas"]["HasMore"];
      records?: components["schemas"]["LocationMinorClassGetResponse"][];
    };
    /**
     * Format: int64
     * @description 国ID
     * @example 123
     */
    CountryId: number;
    CountryGetResponse: {
      countryId?: components["schemas"]["CountryId"];
      /** @description 国コード(alpha-2) */
      countryCodeAlpha2?: string;
      /** @description 国コード(alpha-3) */
      countryCodeAlpha3?: string | null;
      /** @description 国名 */
      countryName?: string;
      /**
       * @description 更新者ID
       * @example GHIJKL123456
       */
      updatedUserId?: string;
      /**
       * Format: date-time
       * @description 更新日時
       * @example 2024-01-01T11:11:00
       */
      updatedDatetime?: string;
    };
    CountriesGetResponse: {
      offset?: components["schemas"]["Offset"];
      count?: components["schemas"]["Count"];
      limit?: components["schemas"]["Limit"];
      totalResults?: components["schemas"]["TotalResults"];
      hasMore?: components["schemas"]["HasMore"];
      records?: components["schemas"]["CountryGetResponse"][];
    };
    StoreAttributesGetResponse: {
      /**
       * Format: int64
       * @description 店舗属性ID
       * @example 123
       */
      storeAttributesId?: number;
      /**
       * @description 開店時間（月曜）
       * @example 10:00
       */
      openTimeMon?: string | null;
      /**
       * @description 開店時間（火曜）
       * @example 10:00
       */
      openTimeTue?: string | null;
      /**
       * @description 開店時間（水曜）
       * @example 10:00
       */
      openTimeWed?: string | null;
      /**
       * @description 開店時間（木曜）
       * @example 10:00
       */
      openTimeThu?: string | null;
      /**
       * @description 開店時間（金曜）
       * @example 10:00
       */
      openTimeFri?: string | null;
      /**
       * @description 開店時間（土曜）
       * @example 10:00
       */
      openTimeSat?: string | null;
      /**
       * @description 開店時間（日曜）
       * @example 11:00
       */
      openTimeSun?: string | null;
      /**
       * @description 開店時間（祝日）
       * @example 11:00
       */
      openTimeHol?: string | null;
      /**
       * @description 閉店時間（月曜）
       * @example 21:00
       */
      closeTimeMon?: string | null;
      /**
       * @description 閉店時間（火曜）
       * @example 21:00
       */
      closeTimeTue?: string | null;
      /**
       * @description 閉店時間（水曜）
       * @example 21:00
       */
      closeTimeWed?: string | null;
      /**
       * @description 閉店時間（木曜）
       * @example 21:00
       */
      closeTimeThu?: string | null;
      /**
       * @description 閉店時間（金曜）
       * @example 21:00
       */
      closeTimeFri?: string | null;
      /**
       * @description 閉店時間（土曜）
       * @example 21:00
       */
      closeTimeSat?: string | null;
      /**
       * @description 閉店時間（日曜）
       * @example 19:00
       */
      closeTimeSun?: string | null;
      /**
       * @description 閉店時間（祝日）
       * @example 19:00
       */
      closeTimeHol?: string | null;
      /**
       * Format: Int32
       * @description ピックアップロッカー保有フラグ
       */
      pickupLockerHoldingFlag?: number | null;
      /**
       * Format: Int32
       * @description 削除フラグ
       */
      deletedFlag?: number;
      /**
       * @description 更新者ID
       * @example Usa00001
       */
      updatedUserId?: string;
      /**
       * Format: date-time
       * @description 更新日時
       * @example 2024-01-01T11:11:00
       */
      updatedDatetime?: string;
      location?: {
        /**
         * Format: int64
         * @description ロケーションID
         * @example 1143001
         */
        locationId?: number;
        /**
         * @description ロケーションコード
         * @example 89001
         */
        locationCode?: string;
        /**
         * @description ロケーション名
         * @example JINS Valley Fair
         */
        locationName?: string;
        /**
         * Format: int64
         * @description ロケーション小分類ID
         * @example 10011
         */
        locationMinorClassId?: number;
        /**
         * Format: int64
         * @description 国ID
         * @example 91000000001
         */
        countryId?: number;
        /**
         * @description 郵便番号
         * @example 95050
         */
        postalCode?: string | null;
        /**
         * @description 住所1
         * @example 2855 Stevens Creek Boulevard
         */
        address1?: string | null;
        /**
         * @description 住所2
         * @example Santa Clara
         */
        address2?: string | null;
        /**
         * @description 住所3
         * @example CA 95050
         */
        address3?: string | null;
        /**
         * @description 住所4
         * @example Level 2, next to Old Navy
         */
        address4?: string | null;
        /**
         * @description 緯度
         * @example 37.325137
         */
        latitude?: number | null;
        /**
         * @description 経度
         * @example -121.946243
         */
        longitude?: number | null;
        /**
         * @description タイムゾーン
         * @example America/Los_Angeles
         */
        timezone?: string | null;
        /**
         * @description 電話番号（代表）
         * @example 1 (609) 681-2485
         */
        primaryPhoneNumber?: string | null;
        /**
         * Format: date
         * @description 開業日
         * @example 2024-01-01
         */
        openingDate?: string | null;
        /**
         * Format: date
         * @description 閉業日
         * @example 2024-01-31
         */
        closingDate?: string | null;
      };
    };
    StoresAttributesGetResponse: {
      offset?: components["schemas"]["Offset"];
      count?: components["schemas"]["Count"];
      limit?: components["schemas"]["Limit"];
      totalResults?: components["schemas"]["TotalResults"];
      hasMore?: components["schemas"]["HasMore"];
      records?: components["schemas"]["StoreAttributesGetResponse"][];
    };
  };
  responses: {
    /** @description Bad Request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Too Many Requests */
    TooManyRequests: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Not Found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Conflict */
    Conflict: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
  };
  parameters: {
    /**
     * @description <BFFシステムコード>_\<UUID>
     * @example bff_usgjpic_ab623ca6-b1e4-3796-a761-ca05605da64a
     */
    JinsTraceID: string;
    /**
     * @description jins-trace-idに紐付く呼出し枝番
     * @example 1
     */
    JinsTraceIdBranchNo?: string;
    /**
     * @description UI側でユーザを識別できるIDを格納
     * @example U00001
     */
    UserID: string;
    /**
     * @description ロケーションIDリスト
     * @example 123,124
     */
    LocationIdList?: number[];
    /**
     * @description ロケーションコードリスト
     * @example aaa-abcdefg,bbb-abcdefg
     */
    LocationCodeList?: string[];
    /**
     * @description ロケーション大分類コードリスト
     * @example aaa-abcdefg,bbb-abcdefg
     */
    LocationMajorClassCodeList?: string[];
    /**
     * @description ロケーション小分類コードリスト
     * @example aaa-abcdefg,bbb-abcdefg
     */
    LocationMinorClassCodeList?: string[];
    /**
     * @description 在庫保有フラグ
     * @example 1
     */
    InventoryHoldingFlag?: number;
    /**
     * @description 受付業務可能フラグ
     * @example 1
     */
    ReceptionFlag?: number;
    /**
     * @description 測定業務可能フラグ
     * @example 1
     */
    ExamFlag?: number;
    /**
     * @description 会計業務可能フラグ
     * @example 1
     */
    CheckoutFlag?: number;
    /**
     * @description 加工業務可能フラグ
     * @example 1
     */
    ProcessingFlag?: number;
    /**
     * @description 調整・お渡し業務可能フラグ
     * @example 1
     */
    AdjustmentPickupFlag?: number;
    /**
     * @description コンタクト販売可能フラグ
     * @example 1
     */
    ContactLensSalesFlag?: number;
    /**
     * @description 保証業務可能フラグ
     * @example 1
     */
    WarrantyFlag?: number;
    /**
     * @description 国コード(alpha-2)
     * @example JP
     */
    CountryCodeAlpha2?: string;
    /**
     * @description 削除レコード取得フラグ<br> true:削除されたレコードも含めて返します。<br> false:削除されていないレコードのみを返します。
     * @example true
     */
    DeletedGetFlag?: boolean;
    /**
     * @description ソートキー<br> 昇順降順はコロン区切り<br> 複数の場合はカンマ区切り<br> スペースは挟まない
     * @example locationId:ASC
     */
    SortKey?: string;
    /**
     * @description 取得制限数
     * @example 1000000
     */
    Limit?: components["schemas"]["Limit"];
    /**
     * @description 取得開始位置
     * @example 0
     */
    Offset?: components["schemas"]["Offset"];
    /**
     * @description ロケーション大分類IDリスト
     * @example 123,124
     */
    LocationMajorClassIdList?: number[];
    /**
     * @description ソートキー<br>
     * 昇順降順はコロン区切り<br>
     * 複数の場合はカンマ区切り<br>
     * スペースは挟まない
     *
     * @example locationMajorClassCode:ASC
     */
    "parameters-SortKey"?: string;
    /**
     * @description ロケーション小分類IDリスト
     * @example 123,124
     */
    LocationMinorClassIdList?: number[];
    /**
     * @description ロケーション小分類コードリスト
     * @example aa,bb
     */
    "parameters-LocationMinorClassCodeList"?: string[];
    /**
     * @description ソートキー<br> 昇順降順はコロン区切り<br> 複数の場合はカンマ区切り<br> スペースは挟まない
     * @example locationMinorClassCode:ASC
     */
    "components-parameters-SortKey"?: string;
    /**
     * @description 国IDリスト
     * @example 123,124
     */
    CountryIdList?: number[];
    /**
     * @description 国コード(Alpha-2)リスト
     * @example JP,US
     */
    CountryCodeAlpha2List?: string[];
    /**
     * @description 国コード(Alpha-3)リスト
     * @example JPN,USA
     */
    CountryCodeAlpha3List?: string[];
    /**
     * @description ソートキー
     * 昇順降順はコロン区切り
     * 複数の場合はカンマ区切り
     * スペースは挟まない
     *
     * @example countryId:ASC
     */
    "countries_components-parameters-SortKey"?: string;
    /**
     * @description 店舗属性IDリスト
     * @example 123,124
     */
    StoreAttributesIdList?: number[];
    /**
     * @description ソートキー 昇順降順はコロン区切り<br> 複数の場合はカンマ区切り<br> スペースは挟まない
     * @example storeAttributesId:ASC
     */
    "stores-attributes_components-parameters-SortKey"?: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * ロケーションマスタ検索API
   * @description 必須のクエリパラメータは存在しません。<br> クエリパラメータを指定しない場合は、すべての検索結果が返されます。 総件数や取得件数は親のカウントです。
   */
  getLocations: {
    parameters: {
      query?: {
        locationIdList?: components["parameters"]["LocationIdList"];
        locationCodeList?: components["parameters"]["LocationCodeList"];
        locationMajorClassCodeList?: components["parameters"]["LocationMajorClassCodeList"];
        locationMinorClassCodeList?: components["parameters"]["LocationMinorClassCodeList"];
        inventoryHoldingFlag?: components["parameters"]["InventoryHoldingFlag"];
        receptionFlag?: components["parameters"]["ReceptionFlag"];
        examFlag?: components["parameters"]["ExamFlag"];
        checkoutFlag?: components["parameters"]["CheckoutFlag"];
        processingFlag?: components["parameters"]["ProcessingFlag"];
        adjustmentPickupFlag?: components["parameters"]["AdjustmentPickupFlag"];
        contactLensSalesFlag?: components["parameters"]["ContactLensSalesFlag"];
        warrantyFlag?: components["parameters"]["WarrantyFlag"];
        countryCodeAlpha2?: components["parameters"]["CountryCodeAlpha2"];
        deletedGetFlag?: components["parameters"]["DeletedGetFlag"];
        sortKey?: components["parameters"]["SortKey"];
        limit?: components["parameters"]["Limit"];
        offset?: components["parameters"]["Offset"];
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["UserID"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["LocationsGetResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * ロケーション大分類マスタ検索API
   * @description 必須のクエリパラメータは存在しません。<br> クエリパラメータを指定しない場合は、すべての検索結果が返されます。
   */
  getLocationMajorClasses: {
    parameters: {
      query?: {
        locationMajorClassIdList?: components["parameters"]["LocationMajorClassIdList"];
        locationMajorClassCodeList?: components["parameters"]["LocationMajorClassCodeList"];
        sortKey?: components["parameters"]["parameters-SortKey"];
        limit?: components["parameters"]["Limit"];
        offset?: components["parameters"]["Offset"];
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["UserID"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["LocationMajorClassesGetResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * ロケーション小分類マスタ検索API
   * @description 必須のクエリパラメータは存在しません。<br> クエリパラメータを指定しない場合は、すべての検索結果が返されます。 総件数や取得件数は親のカウントです。
   */
  getLocationMinorClasses: {
    parameters: {
      query?: {
        locationMinorClassIdList?: components["parameters"]["LocationMinorClassIdList"];
        locationMinorClassCodeList?: components["parameters"]["parameters-LocationMinorClassCodeList"];
        locationMajorClassIdList?: components["parameters"]["LocationMajorClassIdList"];
        locationMajorClassCodeList?: components["parameters"]["LocationMajorClassCodeList"];
        inventoryHoldingFlag?: components["parameters"]["InventoryHoldingFlag"];
        receptionFlag?: components["parameters"]["ReceptionFlag"];
        examFlag?: components["parameters"]["ExamFlag"];
        checkoutFlag?: components["parameters"]["CheckoutFlag"];
        processingFlag?: components["parameters"]["ProcessingFlag"];
        adjustmentPickupFlag?: components["parameters"]["AdjustmentPickupFlag"];
        contactLensSalesFlag?: components["parameters"]["ContactLensSalesFlag"];
        warrantyFlag?: components["parameters"]["WarrantyFlag"];
        sortKey?: components["parameters"]["components-parameters-SortKey"];
        limit?: components["parameters"]["Limit"];
        offset?: components["parameters"]["Offset"];
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["UserID"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["LocationMinorClassesGetResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 国マスタ検索API */
  getCountries: {
    parameters: {
      query?: {
        countryIdList?: components["parameters"]["CountryIdList"];
        countryCodeAlpha2List?: components["parameters"]["CountryCodeAlpha2List"];
        countryCodeAlpha3List?: components["parameters"]["CountryCodeAlpha3List"];
        sortKey?: components["parameters"]["countries_components-parameters-SortKey"];
        limit?: components["parameters"]["Limit"];
        offset?: components["parameters"]["Offset"];
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["UserID"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CountriesGetResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * 店舗属性マスタ検索API
   * @description 必須のクエリパラメータは存在しません。<br> クエリパラメータを指定しない場合は、すべての検索結果が返されます。 総件数や取得件数は親のカウントです。
   */
  getStoresAttributes: {
    parameters: {
      query?: {
        storeAttributesIdList?: components["parameters"]["StoreAttributesIdList"];
        locationIdList?: components["parameters"]["LocationIdList"];
        locationCodeList?: components["parameters"]["LocationCodeList"];
        sortKey?: components["parameters"]["stores-attributes_components-parameters-SortKey"];
        limit?: components["parameters"]["Limit"];
        offset?: components["parameters"]["Offset"];
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-trace-id-branch-no"?: components["parameters"]["JinsTraceIdBranchNo"];
        "jins-user-id": components["parameters"]["UserID"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["StoresAttributesGetResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
