/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/status": {
    /** health check */
    get: operations["status"];
  };
  "/api/dummy": {
    /** dummy function to call external API */
    get: operations["dummy"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ApplicationError: {
      /**
       * Format: uuid
       * @description アプリケーションノード間のトレーサビリティを確保するためのID
       */
      "Jins-Trace-ID": string;
      /**
       * Format: date-time
       * @description エラー発生時刻
       */
      timestamp: string;
      /** @description エラーコード */
      code: string;
      /** @description システム名 */
      systemName: string;
      /** @description エラーメッセージ */
      message: string;
      /** @description エラー詳細 */
      details: string;
    };
  };
  responses: never;
  parameters: {
    /** @description POST us/v1/jins/oauth/token で取得したOAuthのBearerトークン。<br>許可された値: Bearer {access_token} */
    Authorization: string;
    /** @description リソース・コンテンツのアプリケーション・メディアタイプ。<br>許可された値:application/json */
    "Content-Type": "application/json";
    /** @description リソース・コンテンツのアプリケーション・メディアタイプ。<br>許可された値:application/json */
    Accept: "application/json";
    /** @description 各アプリ・システムに対して環境ごとに払い出されたAPI認証キー */
    "X-API-KEY": string;
    /** @description 言語指定<br>デフォルト値:en<br>許可された値:en */
    "Accept-Language"?: "en";
    /** @description 取得開始位置<br>レスポンスヘッダで返却された X-Cursor の値を指定 */
    "X-Cursor"?: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** health check */
  status: {
    responses: {
      /** @description success */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description failure */
      400: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  /** dummy function to call external API */
  dummy: {
    responses: {
      /** @description success */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description failure */
      400: {
        content: {
          "application/json": string;
        };
      };
    };
  };
}
