/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/inventory/inventories": {
    /**
     * 在庫検索API
     * @description 必須のクエリパラメータは存在しません。<br>
     * クエリパラメータを指定しない場合は、すべての検索結果が返されます。
     */
    get: operations["getInventories"];
    /**
     * 在庫更新API
     * @description 在庫更新API
     */
    post: operations["postInventories"];
  };
  "/inventory/rfid-inventories": {
    /** 在庫更新API */
    post: operations["postInventories"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Format: int64
     * @description 在庫数量
     * @example 20
     */
    Quantity: number;
    /**
     * @description 取得制限数
     * @default 1000000
     * @example 20
     */
    Limit: number;
    /**
     * @description 取得開始位置
     * @default 0
     * @example 0
     */
    Offset: number;
    /**
     * @description 今回取得件数
     * @example 20
     */
    Count: number;
    /**
     * @description 総件数
     * @example 10000
     */
    TotalResults: number;
    /**
     * @description 次回データ存在有無
     * @example true
     */
    HasMore: boolean;
    /**
     * Format: int64
     * @description ロケーションID
     * @example 100
     */
    LocationId: number;
    /**
     * @description ロケーションコード
     * @example 83003
     */
    LocationCode: string;
    /**
     * @description ロケーション名
     * @example Valley Fair
     */
    LocationName: string;
    /**
     * Format: int64
     * @description 商品ID
     * @example 1143516
     */
    ItemId: number;
    /**
     * @description 商品コード
     * @example UCF-24A-105-394
     */
    ItemCode: string;
    /**
     * @description 商品名
     * @example UCF-24A-105-394
     */
    ItemName: string;
    /**
     * Format: int32
     * @description 販売ステータスID
     * @example 2
     */
    SalesStatusId: number;
    /**
     * @description 販売ステータス名
     * @example For sale
     */
    SalesStatusName: string;
    /**
     * Format: int32
     * @description 商品ステータスID
     * @example 2
     */
    ItemStatusId: number;
    /**
     * @description 商品ステータス名
     * @example Good quality item
     */
    ItemStatusName: string;
    /**
     * @description 更新ユーザID
     * @example inventoryUser
     */
    UpdatedUserId: string;
    /**
     * Format: date-time
     * @description 更新日時
     * @example 2024-09-13T00:00:00
     */
    UpdatedDatetime: string;
    /**
     * Format: int64
     * @description 楽観ロックバージョン番号
     * @example 1
     */
    OptimisticLockVerNo: number;
    /** @description 在庫テーブルレコード（コード、名称付与） */
    InventoryRecord: {
      locationId?: components["schemas"]["LocationId"];
      locationCode?: components["schemas"]["LocationCode"];
      locationName?: components["schemas"]["LocationName"];
      itemId?: components["schemas"]["ItemId"];
      itemCode?: components["schemas"]["ItemCode"];
      itemName?: components["schemas"]["ItemName"];
      salesStatusId?: components["schemas"]["SalesStatusId"];
      salesStatusName?: components["schemas"]["SalesStatusName"];
      itemStatusId?: components["schemas"]["ItemStatusId"];
      itemStatusName?: components["schemas"]["ItemStatusName"];
      inventoryQuantity?: components["schemas"]["Quantity"];
      updatedUserId?: components["schemas"]["UpdatedUserId"];
      updatedDatetime?: components["schemas"]["UpdatedDatetime"];
      optimisticLockVerNo?: components["schemas"]["OptimisticLockVerNo"];
    };
    /** @description 在庫検索APIレスポンス */
    InventoriesGetResponse: {
      limit?: components["schemas"]["Limit"];
      offset?: components["schemas"]["Offset"];
      count?: components["schemas"]["Count"];
      totalResults?: components["schemas"]["TotalResults"];
      hasMore?: components["schemas"]["HasMore"];
      records?: components["schemas"]["InventoryRecord"][];
    };
    CommonErrorResponse: {
      code: string;
      message: string;
      details?: Record<string, never>;
    };
    /**
     * Format: int32
     * @description 在庫操作イベントID
     * @example 1
     */
    EventId: number;
    /**
     * @description ロケーションID or ロケーションコード
     * @example 83003
     */
    Location: string;
    /**
     * @description 商品ID or 商品コード
     * @example UCF-24A-105-394
     */
    Item: string;
    /** @description 在庫イベント対象 */
    InventoryEventTarget: {
      item: components["schemas"]["Item"];
      quantity: components["schemas"]["Quantity"];
      optimisticLockVerNo?: components["schemas"]["OptimisticLockVerNo"];
    };
    /** @description 在庫イベント制御オプション */
    InventoryEventOptions: {
      /** @default true */
      allowNegativeInventory?: boolean;
      /** @default true */
      useCode?: boolean;
    };
    /** @description 在庫イベント */
    InventoryEvent: {
      eventId: components["schemas"]["EventId"];
      location: components["schemas"]["Location"];
      targets: components["schemas"]["InventoryEventTarget"][];
      options: components["schemas"]["InventoryEventOptions"];
    };
    /** @description 在庫更新APIリクエスト */
    InventoriesPostRequest: {
      events?: components["schemas"]["InventoryEvent"][];
    };
    ProcessedItemInfo: {
      itemId?: components["schemas"]["ItemId"];
      quantity?: components["schemas"]["Quantity"];
    };
    InventoryEventResult: {
      eventId?: components["schemas"]["EventId"];
      locationId?: components["schemas"]["LocationId"];
      processed?: components["schemas"]["ProcessedItemInfo"][];
    };
    /** @description 在庫更新APIレスポンス */
    InventoriesPostResponse: {
      results?: components["schemas"]["InventoryEventResult"][];
    };
    /**
     * Format: int64
     * @description ロケーションID
     * @example 123
     */
    "schemas-LocationId": number;
    /**
     * Format: int64
     * @description 商品ID
     * @example 12345678
     */
    "schemas-ItemId": number;
    /**
     * Format: int32
     * @description RFIDイベントID
     * @example 2
     */
    RfidEventId: number;
    /**
     * Format: int32
     * @description 販売ステータスID
     * @example 1
     */
    "schemas-SalesStatusId": number;
    /**
     * Format: int32
     * @description 商品ステータスID
     * @example 0
     */
    "schemas-ItemStatusId": number;
    /**
     * Format: int64
     * @description 出庫元ロケーションID
     * @example 123456
     */
    IssueSourceLocationId: number;
    /**
     * Format: int32
     * @description 数量
     * @example 5
     */
    "schemas-Quantity": number;
    RfidInventoryPostRequest: {
      locationId: components["schemas"]["schemas-LocationId"];
      itemId: components["schemas"]["schemas-ItemId"];
      rfidEventId: components["schemas"]["RfidEventId"];
      salesStatusId: components["schemas"]["schemas-SalesStatusId"];
      itemStatusId: components["schemas"]["schemas-ItemStatusId"];
      issueSourceLocationId?: components["schemas"]["IssueSourceLocationId"];
      quantity: components["schemas"]["schemas-Quantity"];
    };
    /** @description 在庫更新APIのリクエストボディ */
    RfidInventoriesPostRequest: {
      records: components["schemas"]["RfidInventoryPostRequest"][];
    };
    /** @description 在庫更新のレスポンス要素 */
    RfidInventoryPostResponse: {
      locationId?: components["schemas"]["schemas-LocationId"];
      itemId?: components["schemas"]["schemas-ItemId"];
      rfidEventId?: components["schemas"]["RfidEventId"];
      salesStatusId?: components["schemas"]["schemas-SalesStatusId"];
      itemStatusId?: components["schemas"]["schemas-ItemStatusId"];
      issueSourceLocationId?: components["schemas"]["IssueSourceLocationId"];
      quantity?: components["schemas"]["schemas-Quantity"];
    };
    /** @description 在庫更新のエラーレスポンス要素 */
    RfidInventoriesPostErrorResponse: {
      /**
       * @description エラーコード
       * @example E1_001
       */
      errorCode?: string;
      records?: components["schemas"]["RfidInventoryPostResponse"][];
    };
    /** @description 在庫更新のマルチステータスレスポンスボディ */
    RfidInventoriesPostResponse: {
      /**
       * @description 成功件数
       * @example 15
       */
      successCount?: number;
      successDetails?: components["schemas"]["RfidInventoryPostResponse"][];
      /**
       * @description エラー件数
       * @example 3
       */
      errorCount?: number;
      errorDetails?: components["schemas"]["RfidInventoriesPostErrorResponse"][];
    };
  };
  responses: {
    /** @description Bad Request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Too Many Requests */
    TooManyRequests: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Not Found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Conflict */
    Conflict: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
  };
  parameters: {
    /**
     * @description <BFFシステムコード>_\<UUID>
     * @example bff_usgjpic_ab623ca6-b1e4-3796-a761-ca05605da64a
     */
    JinsTraceID: string;
    /**
     * @description UI側でユーザを識別できるIDを格納
     * @example U00001
     */
    UserID: string;
    /**
     * @description ロケーションIDリスト(完全一致)
     * @example 123456,123457,123458
     */
    LocationIdList?: number[];
    /**
     * @description ロケーションコードリスト（完全一致）
     * @example 84999, 85000, 85001
     */
    LocationCodeList?: string[];
    /**
     * @description 商品IDリスト（完全一致）
     * @example 123456,123457,123458
     */
    ItemIdList?: number[];
    /**
     * @description 商品コードリスト（完全一致）
     * @example MFA-AA-1234, MFA-BB-4567
     */
    ItemCodeList?: string[];
    /**
     * @description 販売ステータスIDリスト
     * @example 2,3
     */
    SalesStatusIdList?: number[];
    /**
     * @description 商品ステータスIDリスト
     * @example 2,3
     */
    ItemStatusIdList?: number[];
    /**
     * @description 在庫数量（最小値）
     * @example 0
     */
    QuantityMin?: components["schemas"]["Quantity"];
    /**
     * @description 在庫数量（最大値）
     * @example 0
     */
    QuantityMax?: components["schemas"]["Quantity"];
    /**
     * @description ソートキー
     * 昇順降順はコロン区切り
     * 複数の場合はカンマ区切り
     * スペースは挟まない
     *
     * @example locationCode:ASC, itemCode:ASC
     */
    SortKey?: string;
    /**
     * @description 取得制限数
     * @example 1000000
     */
    Limit?: components["schemas"]["Limit"];
    /**
     * @description 取得開始位置
     * @example 0
     */
    Offset?: components["schemas"]["Offset"];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * 在庫検索API
   * @description 必須のクエリパラメータは存在しません。<br>
   * クエリパラメータを指定しない場合は、すべての検索結果が返されます。
   */
  getInventories: {
    parameters: {
      query?: {
        locationIdList?: components["parameters"]["LocationIdList"];
        locationCodeList?: components["parameters"]["LocationCodeList"];
        itemIdList?: components["parameters"]["ItemIdList"];
        itemCodeList?: components["parameters"]["ItemCodeList"];
        salesStatusIdList?: components["parameters"]["SalesStatusIdList"];
        itemStatusIdList?: components["parameters"]["ItemStatusIdList"];
        quantityMin?: components["parameters"]["QuantityMin"];
        quantityMax?: components["parameters"]["QuantityMax"];
        sortKey?: components["parameters"]["SortKey"];
        limit?: components["parameters"]["Limit"];
        offset?: components["parameters"]["Offset"];
      };
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-user-id": components["parameters"]["UserID"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["InventoriesGetResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** 在庫更新API */
  postInventories: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-user-id": components["parameters"]["UserID"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RfidInventoriesPostRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["RfidInventoriesPostResponse"];
        };
      };
      /** @description Multi-Status */
      207: {
        content: {
          "application/json": components["schemas"]["RfidInventoriesPostResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
