/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/oms/_calculate-amount": {
    /**
     * 価格・税計算のAPIです。
     * @description 価格・税計算のAPI です。
     */
    post: operations["calculateAmount"];
  };
  "/oms/glass-lines/_delivery-completed-by-item-group-code/{itemGroupCode}": {
    /**
     * 注文メガネ行ステータス更新のAPIです。
     * @description 商品グループコードで注文メガネ行ステータスをお渡し完了に更新するAPIです。
     */
    post: operations["updateGlassLinesStatusReadyForDelivery_1"];
  };
  "/oms/glass-lines/_ready-for-delivery-by-item-group-code/{itemGroupCode}": {
    /**
     * 注文メガネ行ステータス更新のAPIです。
     * @description 商品グループコードで注文メガネ行ステータスをお渡し準備完了に更新するAPIです。
     */
    post: operations["updateGlassLinesStatusReadyForDelivery"];
  };
  "/oms/orders/_payment-completed-by-reception/{receptionNumber}": {
    /**
     * 注文ステータス更新のAPIです。
     * @description 受付番号で注文ステータスを支払い完了に更新するAPIです。
     */
    post: operations["updateOrderStatusPaymentCompletedByReception"];
  };
  "/oms/orders/_place-order-by-cart/{cartId}": {
    /**
     * 注文確定API
     * @description カート内の商品の注文確定を行うAPIです。
     */
    post: operations["placeOrderByCart"];
  };
  "/oms/orders/{orderCode}/_cancel": {
    /**
     * 注文キャンセルAPI
     * @description 注文のキャンセルを行うAPIです。
     */
    post: operations["cancelOrder"];
  };
  "/oms/orders/{orderCode}/_payment-completed": {
    /**
     * 注文ステータス更新のAPIです。
     * @description 注文番号で注文ステータスを支払い完了に更新するAPIです。
     */
    post: operations["updateOrderStatusPaymentCompleted"];
  };
  "/oms/orders/{orderCode}/glass-lines/{glassLineCode}/_cancel": {
    /**
     * 注文部分キャンセルAPI
     * @description 注文の部分キャンセルを行うAPIです。
     */
    post: operations["cancelGlassLine"];
  };
  "/oms/returns": {
    /**
     * 注文返品API
     * @description 返品情報を登録します。
     */
    post: operations["returnOrder"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description 割引メガネ行商品 */
    CalculateAmountDiscountGlassLineReadDto: {
      /** @description 割引価格 */
      discountPrice: number;
      /** @description 割引対象価格 */
      discountablePrice: number;
      /** @description メガネ行コード */
      glassLineCode: string;
      /** @description 商品コード */
      itemCode: string;
      /** @description 商品ID */
      itemId: number;
      /** @description 販売用商品種別リスト */
      salesItemCategories?: components["schemas"]["CalculateAmountSalesItemCategoryReadDto"][];
    };
    /** @description 割引情報 */
    CalculateAmountDiscountLineReadDto: {
      /** @description 割引額 */
      discountAmount?: number;
      /** @description 割引コード */
      discountCode: string;
      /** @description 割引メガネ行商品 */
      discountGlassLineItems?: components["schemas"]["CalculateAmountDiscountGlassLineReadDto"][];
      /** @description 割引率(%) */
      discountRatePercentage?: number;
      /** @description 割引タイプ */
      discountType: string;
      /** @description 割引対象金額 */
      discountableAmount?: number;
    };
    /** @description 割引情報 */
    CalculateAmountDiscountLineWriteDto: {
      /** @description 割引コード */
      discountCode: string;
      /** @description 指定された割引額 */
      specifiedDiscountAmount?: number;
    };
    /** @description 手数料メガネ行 */
    CalculateAmountFeeGlassLineReadDto: {
      /** @description メガネ行コード */
      glassLineCode: string;
    };
    /** @description 手数料メガネ行 */
    CalculateAmountFeeGlassLineWriteDto: {
      /** @description メガネ行コード */
      glassLineCode: string;
    };
    /** @description 手数料情報 */
    CalculateAmountFeeLineReadDto: {
      /** @description 手数料金額 */
      feeAmount: number;
      /** @description 手数料コード */
      feeCode: string;
      /** @description 手数料メガネ行 */
      feeGlassLines?: components["schemas"]["CalculateAmountFeeGlassLineReadDto"][];
      /** @description 税グループコード */
      taxGroupCode: string;
      /** @description 手数料の課税対象 */
      taxable: boolean;
    };
    /** @description 手数料情報 */
    CalculateAmountFeeLineWriteDto: {
      /** @description 手数料金額 */
      feeAmount: number;
      /** @description 手数料コード */
      feeCode: string;
      /** @description 手数料メガネ行 */
      feeGlassLines?: components["schemas"]["CalculateAmountFeeGlassLineWriteDto"][];
      /** @description 手数料の課税対象 */
      taxable: boolean;
    };
    /** @description メガネ行 */
    CalculateAmountGlassLinesReadDto: {
      /**
       * Format: int64
       * @description ケース商品ID
       */
      caseItemId?: number;
      /**
       * @description ケース定価
       * @example 123456789
       */
      caseListPrice?: number;
      /**
       * @description ケース販売価格
       * @example 123456789
       */
      caseSellingPrice?: number;
      /**
       * @description ケースに適用される税グループコード
       * @example TAX_GROUP_001
       */
      caseTaxGroupCode?: string;
      /**
       * Format: int64
       * @description フレーム商品ID
       * @example 123456789
       */
      frameItemId?: number;
      /**
       * @description フレーム定価
       * @example 123456789
       */
      frameListPrice?: number;
      /**
       * @description フレーム販売価格
       * @example 123456789
       */
      frameSellingPrice?: number;
      /**
       * @description フレームに適用される税グループコード
       * @example TAX_GROUP_001
       */
      frameTaxGroupCode?: string;
      /** @description メガネ行コード */
      glassLineCode: string;
      /**
       * Format: int64
       * @description レンズ交換分類商品ID
       */
      lensReplacementTypeItemId?: number;
      /** @description レンズ交換分類定価 */
      lensReplacementTypeListPrice?: number;
      /** @description レンズ交換分類販売価格 */
      lensReplacementTypeSellingPrice?: number;
      /** @description レンズ交換分類税グループコード */
      lensReplacementTypeTaxGroupCode?: string;
      /**
       * Format: int64
       * @description 焦点分類商品ID
       */
      lopFocusCategoryItemId?: number;
      /** @description 焦点分類定価 */
      lopFocusCategoryListPrice?: number;
      /** @description 焦点分類販売価格 */
      lopFocusCategorySellingPrice?: number;
      /** @description 焦点分類に適用される税グループコード */
      lopFocusCategoryTaxGroupCode?: string;
      /**
       * Format: int64
       * @description 累進分類商品ID
       */
      lopProgressiveCategoryItemId?: number;
      /** @description 累進分類定価 */
      lopProgressiveCategoryListPrice?: number;
      /** @description 累進分類販売価格 */
      lopProgressiveCategorySellingPrice?: number;
      /** @description 累進分類に適用される税グループコード */
      lopProgressiveCategoryTaxGroupCode?: string;
      /**
       * Format: int64
       * @description 屈折率商品ID
       */
      lopRefractiveIndexNameItemId?: number;
      /** @description 屈折率定価 */
      lopRefractiveIndexNameListPrice?: number;
      /** @description 屈折率販売価格 */
      lopRefractiveIndexNameSellingPrice?: number;
      /** @description 屈折率に適用される税グループコード */
      lopRefractiveIndexNameTaxGroupCode?: string;
      /**
       * Format: int64
       * @description リムレス仕上げ分類商品ID
       */
      lopRimlessFinishingCategoryItemId?: number;
      /** @description リムレス仕上げ分類定価 */
      lopRimlessFinishingCategoryListPrice?: number;
      /** @description リムレス仕上げ分類販売価格 */
      lopRimlessFinishingCategorySellingPrice?: number;
      /** @description リムレス仕上げ分類に適用される税グループコード */
      lopRimlessFinishingCategoryTaxGroupCode?: string;
      /**
       * Format: int64
       * @description 販売用カラー名称商品ID
       */
      lopSalesColorNameItemId?: number;
      /** @description 販売用カラー名称定価 */
      lopSalesColorNameListPrice?: number;
      /** @description 販売用カラー名称販売価格 */
      lopSalesColorNameSellingPrice?: number;
      /** @description 販売用カラー名称に適用される税グループコード */
      lopSalesColorNameTaxGroupCode?: string;
      /**
       * Format: int64
       * @description 販売用レンズ仕様商品ID
       */
      lopSalesLensSpecItemId?: number;
      /** @description 販売用レンズ仕様定価 */
      lopSalesLensSpecListPrice?: number;
      /** @description 販売用レンズ仕様販売価格 */
      lopSalesLensSpecSellingPrice?: number;
      /** @description 販売用レンズ仕様に適用される税グループコード */
      lopSalesLensSpecTaxGroupCode?: string;
      /** @description メガネ行金額小計(小計販売価格 + 小計税額) */
      subtotalAmount: number;
      /** @description メガネ行割引額小計 */
      subtotalDiscountAmount: number;
      /** @description メガネ行定価小計 */
      subtotalListAmount: number;
      /** @description メガネ行販売価格小計 */
      subtotalSellingAmount: number;
      /** @description メガネ行税額小計 */
      subtotalTaxAmount: number;
      /** @description 課税対象 */
      taxable: boolean;
    };
    /** @description メガネ行 */
    CalculateAmountGlassLinesWriteDto: {
      /**
       * Format: int64
       * @description ケース商品ID
       */
      caseItemId?: number;
      /**
       * Format: int64
       * @description フレーム商品ID
       * @example 123456789
       */
      frameItemId?: number;
      /** @description メガネ行コード */
      glassLineCode: string;
      /**
       * Format: int64
       * @description レンズ交換分類商品ID
       */
      lensReplacementTypeItemId?: number;
      /**
       * Format: int64
       * @description 焦点分類商品ID
       */
      lopFocusCategoryItemId?: number;
      /**
       * Format: int64
       * @description 累進分類商品ID
       */
      lopProgressiveCategoryItemId?: number;
      /**
       * Format: int64
       * @description 屈折率商品ID
       */
      lopRefractiveIndexNameItemId?: number;
      /**
       * Format: int64
       * @description リムレス仕上げ分類商品ID
       */
      lopRimlessFinishingCategoryItemId?: number;
      /**
       * Format: int64
       * @description 販売用カラー名称商品ID
       */
      lopSalesColorNameItemId?: number;
      /**
       * Format: int64
       * @description 販売用レンズ仕様商品ID
       */
      lopSalesLensSpecItemId?: number;
      /** @description 課税対象 */
      taxable: boolean;
    };
    CalculateAmountReadDto: {
      /**
       * Format: date
       * @description 価格計算基準日(ローカル日付)
       * @example 2024-11-08
       */
      calculationBaseDate: string;
      /** @description 価格計算パターンコード */
      calculationPatternCode: string;
      /**
       * @description 国名コード(ISO 3166-1 alpha-2)
       * @example US
       */
      countryCodeAlpha2: string;
      /** @description 通貨コード(ISO 4217) */
      currencyCode: string;
      /** @description 割引情報 */
      discountLines?: components["schemas"]["CalculateAmountDiscountLineReadDto"][];
      /** @description 手数料情報 */
      feeLines?: components["schemas"]["CalculateAmountFeeLineReadDto"][];
      /** @description メガネ行 */
      glassLines?: components["schemas"]["CalculateAmountGlassLinesReadDto"][];
      /** @description 税情報 */
      taxLines?: components["schemas"]["CalculateAmountTaxLineReadDto"][];
      /** @description 税込金額合計(販売金額合計 + 手数料合計 + 税額合計) */
      totalAmount: number;
      /** @description 割引額合計 */
      totalDiscountAmount: number;
      /** @description 手数料合計 */
      totalFeeAmount: number;
      /** @description 定価合計 */
      totalListAmount: number;
      /** @description 販売価格合計 */
      totalSellingAmount: number;
      /** @description 税額合計 */
      totalTaxAmount: number;
    };
    /** @description 販売用商品種別リスト */
    CalculateAmountSalesItemCategoryReadDto: {
      /** @description 販売用商品種別項目コード */
      salesItemCategoryCode: string;
      /** @description 販売用商品種別管理コード */
      salesItemCategoryMgmtCode: string;
    };
    /** @description 手数料税リスト */
    CalculateAmountTaxFeeLineReadDto: {
      /** @description 手数料行コード */
      feeLineCode: string;
      /** @description 税額 */
      taxAmount: number;
      /** @description 課税対象価格 */
      taxableAmount: number;
    };
    /** @description メガネ行商品税リスト */
    CalculateAmountTaxGlassLineItemReadDto: {
      /** @description メガネ行コード */
      glassLineCode: string;
      /** @description メガネ行商品ID */
      itemId: number;
      /** @description 税額 */
      taxAmount: number;
      /** @description 課税対象価格 */
      taxablePrice: number;
    };
    /** @description 税情報 */
    CalculateAmountTaxLineReadDto: {
      /** @description 税額 */
      taxAmount: number;
      /** @description 税コード */
      taxCode: string;
      /** @description 手数料税リスト */
      taxFeeLines?: components["schemas"]["CalculateAmountTaxFeeLineReadDto"][];
      /** @description メガネ行商品税リスト */
      taxGlassLineItems?: components["schemas"]["CalculateAmountTaxGlassLineItemReadDto"][];
      /** @description 税グループコード */
      taxGroupCode: string;
      /** @description 税率コード */
      taxRateCode: string;
      /** @description 税率% */
      taxRatePercentage: number;
      /** @description 課税対象金額 */
      taxableAmount: number;
    };
    CalculateAmountWriteDto: {
      /**
       * Format: date
       * @description 価格計算基準日(ローカル日付)
       * @example 2024-11-01
       */
      calculationBaseDate: string;
      /**
       * @description 価格計算パターンコード
       * @example US_L2-1
       */
      calculationPatternCode?: string;
      /**
       * @description 国名コード(ISO 3166-1 alpha-2)
       * @example US
       */
      countryCodeAlpha2: string;
      /**
       * 通貨コード(ISO 4217)
       * @description 文字列
       */
      currencyCode: string;
      /** @description 割引情報 */
      discountLines?: components["schemas"]["CalculateAmountDiscountLineWriteDto"][];
      /** @description 手数料情報 */
      feeLines?: components["schemas"]["CalculateAmountFeeLineWriteDto"][];
      /** @description メガネ行 */
      glassLines?: components["schemas"]["CalculateAmountGlassLinesWriteDto"][];
      /**
       * 店舗コード
       * @description 文字列
       */
      storeCode: string;
    };
    CancelGlassLineReadDto: {
      order?: components["schemas"]["OrderDetailReadDto"];
    };
    CancelOrderReadDto: {
      order?: components["schemas"]["OrderDetailReadDto"];
    };
    CancelOrderRequest: {
      /**
       * @description キャンセル日時 (YYYY-MM-DDThh:mm:ss 形式)
       * @example 2025-01-15T12:34:56
       */
      cancelDateTime?: string;
      /**
       * @description キャンセル理由コード
       * @example 01
       */
      cancelReasonCode: string;
      /**
       * @description デジタル基盤で在庫管理するか(true: 在庫管理する、 false: 在庫管理しない。 未指定時はtrue)
       * @example true
       */
      useInventory?: boolean;
      /**
       * 楽観ロック
       * Format: int64
       * @description 楽観ロックのための項目
       * @example 1
       */
      version: number;
    };
    DiscountGlassLineItemMixinReadDto: {
      discountAmount?: number;
      discountCode?: string;
      discountGlassLineItemCode?: string;
      discountablePrice?: number;
      glassLineCode?: string;
      glassLineItemCode?: string;
      itemCategoryCode?: string;
      itemCode?: string;
      /** Format: int64 */
      itemId?: number;
      orderCode?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      salesItemCategories?: components["schemas"]["DiscountGlassLineItemSalesItemCategoryMixinReadDto"][];
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    DiscountGlassLineItemSalesItemCategoryMixinReadDto: {
      discountCode?: string;
      discountGlassLineItemCode?: string;
      discountGlassLineItemSalesItemCategoryCode?: string;
      orderCode?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      salesItemCategoryCode?: string;
      salesItemCategoryMgmtCode?: string;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    DiscountLineMixinReadDto: {
      discountAmount?: number;
      discountCode?: string;
      discountGlassLineItems?: components["schemas"]["DiscountGlassLineItemMixinReadDto"][];
      discountRatePercentage?: number;
      discountReasonCode?: string;
      discountType?: string;
      discountableAmount?: number;
      orderCode?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    FeeGlassLineMixinReadDto: {
      feeGlassLineCode?: string;
      feeLineCode?: string;
      glassLineCode?: string;
      orderCode?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    FeeLineMixinReadDto: {
      feeAmount?: number;
      feeCode?: string;
      feeGlassLines?: components["schemas"]["FeeGlassLineMixinReadDto"][];
      feeLineCode?: string;
      orderCode?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      taxAmount?: number;
      taxGroupCode?: string;
      taxable?: boolean;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    GlassLineDeliveryMixinReadDto: {
      customerName?: string;
      deliveryBoxNumber?: string;
      /**
       * Format: date-time
       * @example 2024-11-30T11:59:59
       */
      deliveryDateTime?: string;
      deliveryMethodCode?: string;
      deliveryMethodName?: string;
      deliveryStatus?: string;
      deliveryStoreCode?: string;
      /** Format: int64 */
      deliveryStoreId?: number;
      deliveryStoreName?: string;
      glassLineCode?: string;
      glassLineDeliveryCode?: string;
      orderCode?: string;
      phoneNumber?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      shippingAddress1?: string;
      shippingAddress2?: string;
      shippingAddress3?: string;
      shippingAddress4?: string;
      shippingAddressZip?: string;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    GlassLineHorizontalMixinReadDto: {
      allocatedLocationCode?: string;
      callingNumber?: string;
      cancelDateTime?: string;
      cancelReasonCode?: string;
      caseItemCategoryCode?: string;
      caseItemCode?: string;
      /** Format: int64 */
      caseItemId?: number;
      caseItemName?: string;
      caseItemNameEnglish?: string;
      caseItemNameKana?: string;
      caseItemNameSimplified?: string;
      caseItemNameTraditional?: string;
      /** Format: int64 */
      caseLineItemId?: number;
      caseListPrice?: number;
      casePreparation1?: string;
      casePreparation2?: string;
      caseRegisterPrincipal?: string;
      /** Format: int64 */
      caseRegisterTimestamp?: number;
      caseSellingPrice?: number;
      caseTaxGroupCode?: string;
      caseUpdatePrincipal?: string;
      /** Format: int64 */
      caseUpdateTimestamp?: number;
      /** Format: int64 */
      caseVersion?: number;
      cerritoItemCategoryCode?: string;
      cerritoItemCode?: string;
      /** Format: int64 */
      cerritoItemId?: number;
      cerritoItemName?: string;
      cerritoItemNameEnglish?: string;
      cerritoItemNameKana?: string;
      cerritoItemNameSimplified?: string;
      cerritoItemNameTraditional?: string;
      /** Format: int64 */
      cerritoLineItemId?: number;
      cerritoListPrice?: number;
      cerritoPreparation1?: string;
      cerritoPreparation2?: string;
      cerritoRegisterPrincipal?: string;
      /** Format: int64 */
      cerritoRegisterTimestamp?: number;
      cerritoSellingPrice?: number;
      cerritoTaxGroupCode?: string;
      cerritoUpdatePrincipal?: string;
      /** Format: int64 */
      cerritoUpdateTimestamp?: number;
      /** Format: int64 */
      cerritoVersion?: number;
      delivery?: components["schemas"]["GlassLineDeliveryMixinReadDto"];
      frameItemCategoryCode?: string;
      frameItemCode?: string;
      /** Format: int64 */
      frameItemId?: number;
      frameItemName?: string;
      frameItemNameEnglish?: string;
      frameItemNameKana?: string;
      frameItemNameSimplified?: string;
      frameItemNameTraditional?: string;
      /** Format: int64 */
      frameLineItemId?: number;
      frameListPrice?: number;
      framePreparation1?: string;
      framePreparation2?: string;
      frameRegisterPrincipal?: string;
      /** Format: int64 */
      frameRegisterTimestamp?: number;
      frameSellingPrice?: number;
      frameTaxGroupCode?: string;
      frameUpdatePrincipal?: string;
      /** Format: int64 */
      frameUpdateTimestamp?: number;
      /** Format: int64 */
      frameVersion?: number;
      glassLineCode?: string;
      glassLineId?: string;
      itemGroupCode?: string;
      lensLeftItemCategoryCode?: string;
      lensLeftItemCode?: string;
      /** Format: int64 */
      lensLeftItemId?: number;
      lensLeftItemName?: string;
      lensLeftItemNameEnglish?: string;
      lensLeftItemNameKana?: string;
      lensLeftItemNameSimplified?: string;
      lensLeftItemNameTraditional?: string;
      /** Format: int64 */
      lensLeftLineItemId?: number;
      lensLeftPreparation1?: string;
      lensLeftPreparation2?: string;
      lensLeftRegisterPrincipal?: string;
      /** Format: int64 */
      lensLeftRegisterTimestamp?: number;
      lensLeftUpdatePrincipal?: string;
      /** Format: int64 */
      lensLeftUpdateTimestamp?: number;
      /** Format: int64 */
      lensLeftVersion?: number;
      lensPurchased?: boolean;
      lensReplacementTypeItemCategoryCode?: string;
      lensReplacementTypeItemCode?: string;
      /** Format: int64 */
      lensReplacementTypeItemId?: number;
      lensReplacementTypeItemName?: string;
      /** Format: int64 */
      lensReplacementTypeLineItemId?: number;
      lensReplacementTypeListPrice?: number;
      lensReplacementTypePreparation1?: string;
      lensReplacementTypePreparation2?: string;
      lensReplacementTypeRegisterPrincipal?: string;
      /** Format: int64 */
      lensReplacementTypeRegisterTimestamp?: number;
      lensReplacementTypeSellingPrice?: number;
      lensReplacementTypeTaxGroupCode?: string;
      lensReplacementTypeUpdatePrincipal?: string;
      /** Format: int64 */
      lensReplacementTypeUpdateTimestamp?: number;
      /** Format: int64 */
      lensReplacementTypeVersion?: number;
      lensRightItemCategoryCode?: string;
      lensRightItemCode?: string;
      /** Format: int64 */
      lensRightItemId?: number;
      lensRightItemName?: string;
      lensRightItemNameEnglish?: string;
      lensRightItemNameKana?: string;
      lensRightItemNameSimplified?: string;
      lensRightItemNameTraditional?: string;
      /** Format: int64 */
      lensRightLineItemId?: number;
      lensRightPreparation1?: string;
      lensRightPreparation2?: string;
      lensRightRegisterPrincipal?: string;
      /** Format: int64 */
      lensRightRegisterTimestamp?: number;
      lensRightUpdatePrincipal?: string;
      /** Format: int64 */
      lensRightUpdateTimestamp?: number;
      /** Format: int64 */
      lensRightVersion?: number;
      /** Format: int64 */
      lineItemGroupId?: number;
      lopFocusCategoryItemCategoryCode?: string;
      lopFocusCategoryItemCode?: string;
      /** Format: int64 */
      lopFocusCategoryItemId?: number;
      lopFocusCategoryItemName?: string;
      /** Format: int64 */
      lopFocusCategoryLineItemId?: number;
      lopFocusCategoryListPrice?: number;
      lopFocusCategoryPreparation1?: string;
      lopFocusCategoryPreparation2?: string;
      lopFocusCategoryRegisterPrincipal?: string;
      /** Format: int64 */
      lopFocusCategoryRegisterTimestamp?: number;
      lopFocusCategorySellingPrice?: number;
      lopFocusCategoryTaxGroupCode?: string;
      lopFocusCategoryUpdatePrincipal?: string;
      /** Format: int64 */
      lopFocusCategoryUpdateTimestamp?: number;
      /** Format: int64 */
      lopFocusCategoryVersion?: number;
      lopProgressiveCategoryItemCategoryCode?: string;
      lopProgressiveCategoryItemCode?: string;
      /** Format: int64 */
      lopProgressiveCategoryItemId?: number;
      lopProgressiveCategoryItemName?: string;
      /** Format: int64 */
      lopProgressiveCategoryLineItemId?: number;
      lopProgressiveCategoryListPrice?: number;
      lopProgressiveCategoryPreparation1?: string;
      lopProgressiveCategoryPreparation2?: string;
      lopProgressiveCategoryRegisterPrincipal?: string;
      /** Format: int64 */
      lopProgressiveCategoryRegisterTimestamp?: number;
      lopProgressiveCategorySellingPrice?: number;
      lopProgressiveCategoryTaxGroupCode?: string;
      lopProgressiveCategoryUpdatePrincipal?: string;
      /** Format: int64 */
      lopProgressiveCategoryUpdateTimestamp?: number;
      /** Format: int64 */
      lopProgressiveCategoryVersion?: number;
      lopRefractiveIndexNameItemCategoryCode?: string;
      lopRefractiveIndexNameItemCode?: string;
      /** Format: int64 */
      lopRefractiveIndexNameItemId?: number;
      lopRefractiveIndexNameItemName?: string;
      /** Format: int64 */
      lopRefractiveIndexNameLineItemId?: number;
      lopRefractiveIndexNameListPrice?: number;
      lopRefractiveIndexNamePreparation1?: string;
      lopRefractiveIndexNamePreparation2?: string;
      lopRefractiveIndexNameRegisterPrincipal?: string;
      /** Format: int64 */
      lopRefractiveIndexNameRegisterTimestamp?: number;
      lopRefractiveIndexNameSellingPrice?: number;
      lopRefractiveIndexNameTaxGroupCode?: string;
      lopRefractiveIndexNameUpdatePrincipal?: string;
      /** Format: int64 */
      lopRefractiveIndexNameUpdateTimestamp?: number;
      /** Format: int64 */
      lopRefractiveIndexNameVersion?: number;
      lopRimlessFinishingCategoryItemCategoryCode?: string;
      lopRimlessFinishingCategoryItemCode?: string;
      /** Format: int64 */
      lopRimlessFinishingCategoryItemId?: number;
      lopRimlessFinishingCategoryItemName?: string;
      /** Format: int64 */
      lopRimlessFinishingCategoryLineItemId?: number;
      lopRimlessFinishingCategoryListPrice?: number;
      lopRimlessFinishingCategoryPreparation1?: string;
      lopRimlessFinishingCategoryPreparation2?: string;
      lopRimlessFinishingCategoryRegisterPrincipal?: string;
      /** Format: int64 */
      lopRimlessFinishingCategoryRegisterTimestamp?: number;
      lopRimlessFinishingCategorySellingPrice?: number;
      lopRimlessFinishingCategoryTaxGroupCode?: string;
      lopRimlessFinishingCategoryUpdatePrincipal?: string;
      /** Format: int64 */
      lopRimlessFinishingCategoryUpdateTimestamp?: number;
      /** Format: int64 */
      lopRimlessFinishingCategoryVersion?: number;
      lopSalesColorNameItemCategoryCode?: string;
      lopSalesColorNameItemCode?: string;
      /** Format: int64 */
      lopSalesColorNameItemId?: number;
      lopSalesColorNameItemName?: string;
      /** Format: int64 */
      lopSalesColorNameLineItemId?: number;
      lopSalesColorNameListPrice?: number;
      lopSalesColorNamePreparation1?: string;
      lopSalesColorNamePreparation2?: string;
      lopSalesColorNameRegisterPrincipal?: string;
      /** Format: int64 */
      lopSalesColorNameRegisterTimestamp?: number;
      lopSalesColorNameSellingPrice?: number;
      lopSalesColorNameTaxGroupCode?: string;
      lopSalesColorNameUpdatePrincipal?: string;
      /** Format: int64 */
      lopSalesColorNameUpdateTimestamp?: number;
      /** Format: int64 */
      lopSalesColorNameVersion?: number;
      lopSalesLensSpecItemCategoryCode?: string;
      lopSalesLensSpecItemCode?: string;
      /** Format: int64 */
      lopSalesLensSpecItemId?: number;
      lopSalesLensSpecItemName?: string;
      /** Format: int64 */
      lopSalesLensSpecLineItemId?: number;
      lopSalesLensSpecListPrice?: number;
      lopSalesLensSpecPreparation1?: string;
      lopSalesLensSpecPreparation2?: string;
      lopSalesLensSpecRegisterPrincipal?: string;
      /** Format: int64 */
      lopSalesLensSpecRegisterTimestamp?: number;
      lopSalesLensSpecSellingPrice?: number;
      lopSalesLensSpecTaxGroupCode?: string;
      lopSalesLensSpecUpdatePrincipal?: string;
      /** Format: int64 */
      lopSalesLensSpecUpdateTimestamp?: number;
      /** Format: int64 */
      lopSalesLensSpecVersion?: number;
      needsPurchaseLens?: boolean;
      note?: string;
      orderCode?: string;
      orderType?: string;
      /** Format: int64 */
      powerId?: number;
      /** Format: int64 */
      prescriptionId?: number;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      subtotalAmount?: number;
      subtotalListAmount?: number;
      subtotalSellingAmount?: number;
      subtotalTaxAmount?: number;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
      warrantyExchangeItem?: string;
    };
    OrderDetailReadDto: {
      /** Format: int64 */
      cartId?: number;
      channel?: string;
      countryCodeAlpha2?: string;
      currencyCode?: string;
      customerId?: string;
      customerName?: string;
      discountLines?: components["schemas"]["DiscountLineMixinReadDto"][];
      feeLines?: components["schemas"]["FeeLineMixinReadDto"][];
      glassLines?: components["schemas"]["GlassLineHorizontalMixinReadDto"][];
      orderCode?: string;
      orderDate?: string;
      orderStatus?: string;
      payments?: components["schemas"]["PaymentMixinReadDto"][];
      phoneNumber?: string;
      receptionDateTime?: string;
      receptionNumber?: string;
      receptionStoreCode?: string;
      /** Format: int64 */
      receptionStoreId?: number;
      receptionStoreName?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      returns?: components["schemas"]["ReturnMixinReadDto"][];
      taxLines?: components["schemas"]["TaxLineMixinReadDto"][];
      totalAmount?: number;
      totalDiscountAmount?: number;
      totalFeeAmount?: number;
      totalListAmount?: number;
      totalSellingAmount?: number;
      totalTaxAmount?: number;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    /**
     * @description メガネ行毎の注文種類を指定する配列※未指定時は全メガネ行の注文種類が"PLAIN"として処理されます(※)
     * @example [
     *   {
     *     "itemGroupCode": "GLASS",
     *     "orderType": "PLAIN"
     *   }
     * ]
     */
    OrderType: {
      /**
       * @description カートのメガネ行の一意コード
       * @example GLASS
       */
      itemGroupCode: string;
      /**
       * @description 注文種類（"PLAIN"/"WARRANTY_EXCHANGE"/"LENSE_REPLACE"）※未指定時は"PLAIN"として処理されます(※)
       * @example PLAIN
       */
      orderType?: string;
    };
    PaymentMixinReadDto: {
      orderCode?: string;
      paymentAmount?: number;
      paymentCode?: string;
      /**
       * Format: date-time
       * @example 2024-11-30T11:59:59
       */
      paymentDateTime?: string;
      paymentMethod?: string;
      paymentStatus?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    PlaceOrderByCartReadDto: {
      order?: components["schemas"]["OrderDetailReadDto"];
    };
    PlaceOrderByCartWriteDto: {
      /**
       * Format: date
       * @description 価格計算基準日(ローカル日付)
       * @example 2024-11-01
       */
      calculationBaseDate: string;
      /**
       * @description チャネル
       * @example E
       */
      channel: string;
      /**
       * @description 国コード
       * @example US
       */
      countryCodeAlpha2: string;
      /**
       * @description 注文者名
       * @example example
       */
      customerName: string;
      /**
       * Format: date
       * @description 注文確定日
       * @example 2024-11-01
       */
      orderDate?: string;
      orderTypes?: components["schemas"]["OrderType"][];
      /**
       * @description 電話番号
       * @example 08012345678
       */
      phoneNumber: string;
      /**
       * @description デジタル基盤で在庫管理するか(true: 在庫管理する、 false: 在庫管理しない。 未指定時はtrue)
       * @example true
       */
      useInventory?: boolean;
      warrantyExchangeTerms?: components["schemas"]["WarrantyExchangeTerm"][];
    };
    ReturnMixinReadDto: {
      customerId?: string;
      customerName?: string;
      glassLineCode?: string;
      orderCode?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      returnCode?: string;
      /**
       * Format: date-time
       * @example 2024-11-30T11:59:59
       */
      returnDateTime?: string;
      returnReasonCode?: string;
      returnStoreCode?: string;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    ReturnOrderRequest: {
      /**
       * @description 会員ID
       * @example CUSTOMER001
       */
      customerId?: string;
      /**
       * @description 会員名
       * @example 山田 太郎
       */
      customerName?: string;
      /**
       * @description 注文メガネ行コード
       * @example GLASS001
       */
      glassLineCode: string;
      /**
       * @description 注文コード
       * @example ORDER001
       */
      orderCode: string;
      /**
       * @description 返品日時 (YYYY-MM-DDThh:mm:ss 形式) 未指定時はシステム日時が設定されます。
       * @example 2025-01-15T12:34:56
       */
      returnDateTime?: string;
      /**
       * @description 返品理由コード
       * @example 91
       */
      returnReasonCode: string;
      /**
       * @description 返品受付店舗コード
       * @example STORE001
       */
      returnStoreCode: string;
    };
    ReturnOrderResponse: {
      customerId?: string;
      customerName?: string;
      glassLineCode?: string;
      orderCode?: string;
      returnCode?: string;
      /**
       * Format: date-time
       * @example 2024-11-30T11:59:59
       */
      returnDateTime?: string;
      returnReasonCode?: string;
      returnStoreCode?: string;
    };
    TaxFeeLineMixinReadDto: {
      feeLineCode?: string;
      orderCode?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      taxAmount?: number;
      taxFeeLineCode?: string;
      taxRateCode?: string;
      taxableAmount?: number;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    TaxGlassLineItemMixinReadDto: {
      glassLineCode?: string;
      glassLineItemCode?: string;
      /** Format: int64 */
      itemId?: number;
      orderCode?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      taxAmount?: number;
      taxGlassLineItemCode?: string;
      taxRateCode?: string;
      taxablePrice?: number;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    TaxLineMixinReadDto: {
      orderCode?: string;
      registerPrincipal?: string;
      /** Format: int64 */
      registerTimestamp?: number;
      taxAmount?: number;
      taxCode?: string;
      taxFeeLines?: components["schemas"]["TaxFeeLineMixinReadDto"][];
      taxGlassLineItems?: components["schemas"]["TaxGlassLineItemMixinReadDto"][];
      taxGroupCode?: string;
      taxRateCode?: string;
      taxRatePercentage?: number;
      taxableAmount?: number;
      updatePrincipal?: string;
      /** Format: int64 */
      updateTimestamp?: number;
      /** Format: int64 */
      version?: number;
    };
    UpdateGlassLinesStatusWriteDto: {
      /**
       * @description バージョン
       * @example 1
       */
      version?: string;
    };
    UpdateOrderStatusReadDto: {
      order?: components["schemas"]["OrderDetailReadDto"];
    };
    UpdateOrderStatusWriteDto: {
      /**
       * Format: YYYY-MM-DDThh:mm:ss
       * @description 支払日時
       * @example 2025-01-01T12:45:00
       */
      paymentDateTime?: string;
      /**
       * @description バージョン
       * @example 1
       */
      version?: string;
    };
    /**
     * @description orderTypeで"WARRANTY_EXCHANGE"を指定した場合、保証交換条件を指定する配列
     * @example [
     *   {
     *     "itemGroupCode": "GLASS",
     *     "exchangeItem": "FRAME"
     *   }
     * ]
     */
    WarrantyExchangeTerm: {
      /**
       * @description 交換部位("FRAME"/"LENS"/"ALL")
       * @example FRAME
       */
      exchangeItem: string;
      /**
       * @description カートのメガネ行の一意コード
       * @example GLASS
       */
      itemGroupCode: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * 価格・税計算のAPIです。
   * @description 価格・税計算のAPI です。
   */
  calculateAmount: {
    parameters: {
      header: {
        /** @description Accept-Language ヘッダー */
        "Accept-Language": string;
        /** @description Jins-Trace-ID ヘッダー */
        "jins-trace-id": string;
        /** @description Jins-Trace-ID-Branch-No ヘッダー */
        "jins-trace-id-branch-no": string;
        /** @description Jins-User-ID ヘッダー */
        "jins-user-id": string;
        /** @description コンテンツタイプ。application/json を指定してください。 */
        "Content-Type": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalculateAmountWriteDto"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CalculateAmountReadDto"];
        };
      };
      /** @description 400系エラー */
      400: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * 注文メガネ行ステータス更新のAPIです。
   * @description 商品グループコードで注文メガネ行ステータスをお渡し完了に更新するAPIです。
   */
  updateGlassLinesStatusReadyForDelivery_1: {
    parameters: {
      header: {
        /** @description Jins-Trace-ID ヘッダー */
        "jins-trace-id": string;
        /** @description Jins-Trace-ID-Branch-No ヘッダー */
        "jins-trace-id-branch-no": string;
        /** @description Jins-User-ID ヘッダー */
        "jins-user-id": string;
        /** @description コンテンツタイプ。application/json を指定してください。 */
        "Content-Type": string;
      };
      path: {
        itemGroupCode: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateGlassLinesStatusWriteDto"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["UpdateOrderStatusReadDto"];
        };
      };
      /** @description 400(Bad Request) */
      400: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 404(Not Found) */
      404: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 409(Conflict) */
      409: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * 注文メガネ行ステータス更新のAPIです。
   * @description 商品グループコードで注文メガネ行ステータスをお渡し準備完了に更新するAPIです。
   */
  updateGlassLinesStatusReadyForDelivery: {
    parameters: {
      header: {
        /** @description Jins-Trace-ID ヘッダー */
        "jins-trace-id": string;
        /** @description Jins-Trace-ID-Branch-No ヘッダー */
        "jins-trace-id-branch-no": string;
        /** @description Jins-User-ID ヘッダー */
        "jins-user-id": string;
        /** @description コンテンツタイプ。application/json を指定してください。 */
        "Content-Type": string;
      };
      path: {
        itemGroupCode: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateGlassLinesStatusWriteDto"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["UpdateOrderStatusReadDto"];
        };
      };
      /** @description 400(Bad Request) */
      400: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 404(Not Found) */
      404: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 409(Conflict) */
      409: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * 注文ステータス更新のAPIです。
   * @description 受付番号で注文ステータスを支払い完了に更新するAPIです。
   */
  updateOrderStatusPaymentCompletedByReception: {
    parameters: {
      header: {
        /** @description Jins-Trace-ID ヘッダー */
        "jins-trace-id": string;
        /** @description Jins-Trace-ID-Branch-No ヘッダー */
        "jins-trace-id-branch-no": string;
        /** @description Jins-User-ID ヘッダー */
        "jins-user-id": string;
        /** @description コンテンツタイプ。application/json を指定してください。 */
        "Content-Type": string;
      };
      path: {
        receptionNumber: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateOrderStatusWriteDto"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["UpdateOrderStatusReadDto"];
        };
      };
      /** @description 400(Bad Request) */
      400: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 404(Not Found) */
      404: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 409(Conflict) */
      409: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * 注文確定API
   * @description カート内の商品の注文確定を行うAPIです。
   */
  placeOrderByCart: {
    parameters: {
      header: {
        /** @description Jins-Trace-ID ヘッダー */
        "jins-trace-id"?: string;
        /** @description Jins-Trace-ID-Branch-No ヘッダー */
        "jins-trace-id-branch-no": string;
        /** @description Jins-User-ID ヘッダー */
        "jins-user-id"?: string;
        /** @description Accept-Language ヘッダー */
        "Accept-Language"?: string;
      };
      path: {
        cartId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceOrderByCartWriteDto"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["PlaceOrderByCartReadDto"];
        };
      };
      /** @description 400系エラー */
      400: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * 注文キャンセルAPI
   * @description 注文のキャンセルを行うAPIです。
   */
  cancelOrder: {
    parameters: {
      header: {
        /** @description Jins-Trace-ID ヘッダー */
        "jins-trace-id": string;
        /** @description Jins-Trace-ID-Branch-No ヘッダー */
        "jins-trace-id-branch-no": string;
        /** @description Jins-User-ID ヘッダー */
        "jins-user-id": string;
      };
      path: {
        /** @description キャンセル対象の注文番号 */
        orderCode: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CancelOrderRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CancelOrderReadDto"];
        };
      };
      /** @description 400(Bad Request) */
      400: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 404(Not Found) */
      404: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 409(Conflict) */
      409: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * 注文ステータス更新のAPIです。
   * @description 注文番号で注文ステータスを支払い完了に更新するAPIです。
   */
  updateOrderStatusPaymentCompleted: {
    parameters: {
      header: {
        /** @description Jins-Trace-ID ヘッダー */
        "jins-trace-id": string;
        /** @description Jins-Trace-ID-Branch-No ヘッダー */
        "jins-trace-id-branch-no": string;
        /** @description Jins-User-ID ヘッダー */
        "jins-user-id": string;
        /** @description コンテンツタイプ。application/json を指定してください。 */
        "Content-Type": string;
      };
      path: {
        orderCode: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateOrderStatusWriteDto"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["UpdateOrderStatusReadDto"];
        };
      };
      /** @description 400(Bad Request) */
      400: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 404(Not Found) */
      404: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 409(Conflict) */
      409: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * 注文部分キャンセルAPI
   * @description 注文の部分キャンセルを行うAPIです。
   */
  cancelGlassLine: {
    parameters: {
      header: {
        /** @description Jins-Trace-ID ヘッダー */
        "jins-trace-id": string;
        /** @description Jins-Trace-ID-Branch-No ヘッダー */
        "jins-trace-id-branch-no": string;
        /** @description Jins-User-ID ヘッダー */
        "jins-user-id": string;
      };
      path: {
        /** @description キャンセル対象の注文番号 */
        orderCode: string;
        /** @description キャンセル対象の注文メガネ行コード */
        glassLineCode: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CancelOrderRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CancelGlassLineReadDto"];
        };
      };
      /** @description 400(Bad Request) */
      400: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 404(Not Found) */
      404: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 409(Conflict) */
      409: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * 注文返品API
   * @description 返品情報を登録します。
   */
  returnOrder: {
    parameters: {
      header: {
        /** @description Jins-Trace-ID ヘッダー */
        "jins-trace-id": string;
        /** @description Jins-Trace-ID-Branch-No ヘッダー */
        "jins-trace-id-branch-no"?: string;
        /** @description Jins-User-ID ヘッダー */
        "jins-user-id": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReturnOrderRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ReturnOrderResponse"];
        };
      };
      /** @description 400(Bad Request) */
      400: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description 404(Not Found) */
      404: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
