/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/status": {
    /** health check */
    get: operations["status"];
  };
  "/api/dummy": {
    /** dummy function to call external API */
    get: operations["dummy"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ApplicationError: {
      /**
       * Format: uuid
       * @description アプリケーションノード間のトレーサビリティを確保するためのID
       */
      "Jins-Trace-ID": string;
      /**
       * Format: date-time
       * @description エラー発生時刻
       */
      timestamp: string;
      /** @description エラーコード */
      code: string;
      /** @description システム名 */
      systemName: string;
      /** @description エラーメッセージ */
      message: string;
      /** @description エラー詳細 */
      details: string;
    };
    /**
     * @description 待ち状況取得APIレスポンス
     * @example {
     *   "waitTimeRange": {
     *     "earliest": 10,
     *     "latest": 15
     *   },
     *   "callTime": "2024-12-30T08:00:00Z",
     *   "waitPeople": 2,
     *   "waitingStatusCode": "001",
     *   "isReceptionClose": "falsez",
     *   "currentTime": "2024-02-21",
     *   "queuesData": {
     *     "callingNumber": {
     *       "callingNumber": "P1",
     *       "registeredDate": "2024-02-21T10:30:00Z",
     *       "updatedDatetime": "2024-02-21T10:30:00Z"
     *     },
     *     "calledList": [
     *       {
     *         "callingNumber": "P11",
     *         "registeredDate": "2024-02-21T10:30:00Z",
     *         "updatedDatetime": "2024-02-21T10:30:00Z"
     *       },
     *       {
     *         "callingNumber": "G21",
     *         "registeredDate": "2024-02-21T11:00:00Z",
     *         "updatedDatetime": "2024-02-21T10:30:00Z"
     *       }
     *     ],
     *     "waitingList": [
     *       {
     *         "callingNumber": "A12",
     *         "registeredDate": "2024-02-21T10:30:00Z",
     *         "updatedDatetime": "2024-02-21T10:30:00Z"
     *       },
     *       {
     *         "callingNumber": "A22",
     *         "registeredDate": "2024-02-21T11:00:00Z",
     *         "updatedDatetime": "2024-02-21T10:30:00Z"
     *       }
     *     ]
     *   }
     * }
     */
    RcptInfoResponse: {
      /** @description 受付待ち時間範囲 */
      waitTimeRange?: {
        /** @description 最小待ち時間（分） */
        earliest?: number;
        /** @description 最大待ち時間（分） */
        latest?: number;
      };
      /** @description 呼び出し時間 */
      callTime?: string | null;
      /** @description 修理待ち人数 */
      waitPeople?: number;
      /** @description 待ち状況ステータスコード */
      waitingStatusCode?: string | null;
      /** @description 受付終了フラグ */
      isReceptionClose?: boolean;
      /** @description 現在の日付 */
      currentTime?: string | null;
      /** @description キュー情報 */
      queuesData?: {
        /** @description 発信番号 */
        callingNumber?: {
          /** @description 発信番号 */
          callingNumber?: string;
          /** @description 登録日 */
          registeredDate?: string;
          /** @description 更新日時 */
          updatedDatetime?: string;
        } | null;
        /** @description 呼ばれる配列 */
        calledList?:
          | {
              /** @description 発信番号 */
              callingNumber?: string;
              /** @description 登録日 */
              registeredDate?: string;
              /** @description 更新日時 */
              updatedDatetime?: string;
            }[]
          | null;
        /** @description 待機配列 */
        waitingList?:
          | {
              /** @description 発信番号 */
              callingNumber?: string;
              /** @description 登録日 */
              registeredDate?: string;
              /** @description 更新日時 */
              updatedDatetime?: string;
            }[]
          | null;
      };
    };
    /**
     * @description Jins APIからのエラー
     * @example {
     *   "code": "DPFM_RCPT_0001",
     *   "message": "There are no records that match the store code.",
     *   "jinsTraceId": "2389c607-f5ed-4789-95a3-efd78be1e8d9",
     *   "details": null
     * }
     */
    RcptInfoErrorResponse: {
      /** @description エラーコード */
      code?: string;
      /** @description エラーメッセージ */
      message?: string;
      /** @description Jins-Trace-ID */
      jinsTraceId?: string;
      /** @description エラー詳細 */
      details?: string;
    };
    /** @description キュー属性 */
    queueAttribs: {
      /** @description 発信番号 */
      callingNumber?: string;
      /** @description 登録日 */
      registeredDate?: string;
      /** @description 更新日時 */
      updatedDatetime?: string;
      /** @description 登録日時 */
      registeredDatetime?: string;
    };
    /** @description 受付情報 */
    ReceptionInfoAllItems: {
      /** @description 登録日 */
      registeredDate?: string;
      /** @description 来店目的コード */
      visitingPurposeCode?: string;
      /** @description 困りごとコード */
      customerIssueCode?: string;
      /** @description 度数登録方法コード */
      prescriptionRegistCode?: string;
      /** @description 呼出番号 */
      callingNumber?: string;
      /** @description 受付番号 */
      receptionNumber?: string;
      /** @description ステータスコード */
      statusCode?: string;
      /** @description 呼出状態コード */
      callingStatusCode?: string;
      /** @description 国コード(alpha-2) */
      countryCodeAlpha2?: string;
      /** @description 店舗ID */
      storeId?: number;
      /** @description 注文者名 */
      customerName?: string;
      /** @description 電話番号 */
      phoneNumber?: string;
      /** @description JINSアカウントID */
      jinsAccountId?: string;
      /** @description 登録者ID */
      registeredUserId?: string;
      /** @description 登録プログラム */
      registeredProgram?: string;
      /**
       * Format: date-time
       * @description 登録日時
       */
      registeredDatetime?: string;
      /** @description 更新者ID */
      updatedUserId?: string;
      /** @description 更新プログラム */
      updatedProgram?: string;
      /**
       * Format: date-time
       * @description 更新日時
       */
      updatedDatetime?: string;
      /** @description カートにレンズが登録されているかどうかのフラグ */
      hasLensInCart?: boolean;
      /** @description カートにフレームが登録されているかどうかのフラグ */
      hasFrameInCart?: boolean;
    };
    /**
     * @description 受付情報検索APIレスポンス
     * @example {
     *   "ReceptionInfoAllItems": [
     *     {
     *       "registeredDate": "2025-03-28",
     *       "visitingPurposeCode": "010",
     *       "customerIssueCode": "001",
     *       "prescriptionRegistCode": "001",
     *       "callingNumber": "A44",
     *       "receptionNumber": "241230US00001",
     *       "statusCode": "100",
     *       "callingStatusCode": "001",
     *       "countryCodeAlpha2": "US",
     *       "storeId": 83005,
     *       "customerName": "John Doe",
     *       "phoneNumber": "07012345678",
     *       "jinsAccountId": null,
     *       "registeredUserId": "JINS0001",
     *       "registeredProgram": "Step2_test",
     *       "registeredDatetime": "2025-03-28T05:01:00",
     *       "updatedUserId": "JINS0001",
     *       "updatedProgram": "Step2_test",
     *       "updatedDatetime": "2025-03-28T05:01:00",
     *       "hasLensInCart": true,
     *       "hasFrameInCart": true
     *     },
     *     {
     *       "registeredDate": "2025-03-28",
     *       "visitingPurposeCode": "010",
     *       "customerIssueCode": "001",
     *       "prescriptionRegistCode": "002",
     *       "callingNumber": "A45",
     *       "receptionNumber": "241230US00002",
     *       "statusCode": "101",
     *       "callingStatusCode": "001",
     *       "countryCodeAlpha2": "US",
     *       "storeId": 83005,
     *       "customerName": "Smith",
     *       "phoneNumber": "07012345679",
     *       "jinsAccountId": null,
     *       "registeredUserId": "JINS0001",
     *       "registeredProgram": "Step2_test",
     *       "registeredDatetime": "2025-03-28T05:01:00",
     *       "updatedUserId": "JINS0001",
     *       "updatedProgram": "Step2_test",
     *       "updatedDatetime": "2025-03-28T05:01:00",
     *       "hasLensInCart": false,
     *       "hasFrameInCart": false
     *     }
     *   ]
     * }
     */
    ProcessesGetResponse: {
      ReceptionInfoAllItems?: components["schemas"]["ReceptionInfoAllItems"][];
    };
    /**
     * @description 呼出し管理情報
     * @example {
     *   "timeRequiredUntilCall": 200,
     *   "availableLines": 10,
     *   "receptionCloseTime": "08:00:00",
     *   "processingCloseTime": "20:00:00"
     * }
     */
    CallManagementInfo: {
      /** @description 案内時間 */
      timeRequiredUntilCall?: number;
      /** @description 視力測定ライン数 */
      availableLines?: number;
      /** @description 受付案内終了時間 */
      receptionCloseTime?: string;
      /** @description 加工終了時間 */
      processingCloseTime?: string;
    };
    /** @description 呼出し管理情報取得APIレスポンス */
    CallManagementGetResponse: {
      callManagementInfo?: components["schemas"]["CallManagementInfo"];
    };
    /** @description 受付情報 */
    ReceptionInfos: {
      /** @description 登録日 */
      registeredDate?: string;
      /** @description 来店目的コード */
      visitingPurposeCode?: string;
      /** @description 困りごとコード */
      customerIssueCode?: string;
      /** @description 度数登録方法コード */
      prescriptionRegistCode?: string;
      /** @description 呼出番号 */
      callingNumber?: string;
      /** @description 受付番号 */
      receptionNumber?: string;
      /** @description ステータスコード */
      statusCode?: string;
      /** @description 呼出状態コード */
      callingStatusCode?: string;
      /** @description 国コード(alpha-2) */
      countryCodeAlpha2?: string;
      /** @description 店舗ID */
      storeId?: number;
      /** @description 注文者名 */
      customerName?: string;
      /** @description 電話番号 */
      phoneNumber?: string;
      /** @description JINSアカウントID */
      jinsAccountId?: string;
      /** @description 登録日時 */
      registeredDatetime?: string;
      /** @description 更新日時 */
      updatedDatetime?: string;
    };
    /**
     * @description 待ち状況取得APIレスポンス
     * @example {
     *   "receptionInfos": [
     *     {
     *       "registeredDate": "2025-01-14",
     *       "visitingPurposeCode": "010",
     *       "customerIssueCode": "001",
     *       "prescriptionRegistCode": "001",
     *       "callingNumber": "A1",
     *       "receptionNumber": "250114US00001",
     *       "statusCode": "100",
     *       "callingStatusCode": "001",
     *       "countryCodeAlpha2": "US",
     *       "storeId": "1143416",
     *       "customerName": "John Doe",
     *       "phoneNumber": "07012345678",
     *       "jinsAccountId": null
     *     },
     *     {
     *       "registeredDate": "2025-01-14",
     *       "visitingPurposeCode": "010",
     *       "customerIssueCode": "001",
     *       "prescriptionRegistCode": "002",
     *       "callingNumber": "B1",
     *       "receptionNumber": "250114US00002",
     *       "statusCode": "101",
     *       "callingStatusCode": "001",
     *       "countryCodeAlpha2": "US",
     *       "storeId": "1143416",
     *       "customerName": "Smith",
     *       "phoneNumber": "07012345679",
     *       "jinsAccountId": null,
     *       "registeredDatetime": "2025-05-28T06:10:36.667781",
     *       "updatedDatetime": "2025-05-28T06:10:36.667781"
     *     }
     *   ]
     * }
     */
    ReceptionGetResponse: {
      receptionInfos?: components["schemas"]["ReceptionInfos"][];
    };
  };
  responses: {
    /** @description Bad Request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Not Found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Conflict */
    Conflict: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Too Many Requests */
    TooManyRequests: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["ApplicationError"];
      };
    };
  };
  parameters: {
    /** @description POST us/v1/jins/oauth/token で取得したOAuthのBearerトークン。<br>許可された値: Bearer {access_token} */
    Authorization: string;
    /** @description リソース・コンテンツのアプリケーション・メディアタイプ。<br>許可された値:application/json */
    "Content-Type": "application/json";
    /** @description リソース・コンテンツのアプリケーション・メディアタイプ。<br>許可された値:application/json */
    Accept: "application/json";
    /** @description 各アプリ・システムに対して環境ごとに払い出されたAPI認証キー */
    "X-API-KEY": string;
    /** @description 言語指定<br>デフォルト値:en<br>許可された値:en */
    "Accept-Language"?: "en";
    /** @description 取得開始位置<br>レスポンスヘッダで返却された X-Cursor の値を指定 */
    "X-Cursor"?: string;
    /**
     * @description アプリケーションノード間のトレーサビリティを確保するためのID
     * @example 2389c607-f5ed-4789-95a3-efd78be1e8d9
     */
    JinsTraceID: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** health check */
  status: {
    responses: {
      /** @description success */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description failure */
      400: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  /** dummy function to call external API */
  dummy: {
    responses: {
      /** @description success */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description failure */
      400: {
        content: {
          "application/json": string;
        };
      };
    };
  };
}
