/**
 * 正常系_受付番号発番API_困りごと度数登録方法指定あり_度数登録フレーム登録なし
*/

// 受付情報新規作成API
export const postReceptionInfoResponseCase1 = {
  ok: true,
  status: 200,
  data: {
    receptionNumber: "250123US000001",
    callingNumber: "F1",
  }
}

/**
 * 正常系_受付番号発番API_困りごと度数登録方法指定なし_フレーム登録なし
*/

// 受付情報新規作成API
export const postReceptionInfoResponseCase2 = {
  ok: true,
  status: 200,
  data: {
    "receptionNumber": "250123US000002",
    "callingNumber": "P1",
  }
}

/**
 * 正常系_受付番号発番API_フレーム登録あり
*/

// 受付情報新規作成API
export const postReceptionInfoResponseCase3 = {
  ok: true,
  status: 200,
  data: {
    "receptionNumber": "250123US000003",
    "callingNumber": "A1",
  }
}

/**
 * 異常系_カート新規作成_受付番号国コードエラー_受付番号発番API
*/

// 受付情報新規作成API
export const postReceptionInfoResponseCase4 = {
  ok: true,
  status: 200,
  data: {
    "receptionNumber": "250123XX000003",
    "callingNumber": "A1",
  }
}

// カート新規作成API
export const postCartInfoResponse = {
  ok: true,
  status: 200,
  data: {
    "cart": {
      "cartId": 1,
      "customerName": "John Smith",
      "phoneNumber": "4158726498",
      "discountPrice": 0,
      "subtotal": 0,
      "totalDiscountPrice": 0,
      "totalTaxPrice": 0,
      "totalSalesPrice": 0,
      "receptionNumber": "250123US000003",
      "deletedFlag": 0,
      "registeredUserId": "STAFF_A",
      "registeredProgram": "STAFF_A",
      "registeredDatetime": "yyyy-mm-ddThh:ms:ss",
      "updatedUserId": "STAFF_A",
      "updatedProgram": "STAFF_A",
      "updatedDatetime": "yyyy-mm-ddThh:ms:ss",
      "optimisticLockVerNo": 1,
      "receptionStoreId": 1143416,
      "receptionStoreCode": "83005",
      "itemGroups": [
        {
          "lineitemGroupId": 1,
          "itemGroupCode": "250123US000003-1",
          "statusCode": "101",
          "callingStatusCode": "001",
          "callingNumber": "A1",
          "prescriptionRegistCode": "002",
          "deliveryMethodCode": null,
          "deliveryDatetime": null,
          "deliveryStoreId": null,
          "customerName": null,
          "phoneNumber": null,
          "shippingAddressZip": null,
          "shippingAddress1": null,
          "shippingAddress2": null,
          "shippingAddress3": null,
          "shippingAddress4": null,
          "note": null,
          "discountPrice": 0,
          "subtotal": 0,
          "totalDiscountPrice": 0,
          "totalTaxPrice": 0,
          "salesPrice": 0,
          "deletedFlag": 0,
          "registeredUserId": "STAFF_A",
          "registeredProgram": "STAFF_A",
          "registeredDatetime": "yyyy-mm-ddThh:ms:ss",
          "updatedUserId": "STAFF_A",
          "updatedProgram": "STAFF_A",
          "updatedDatetime": "yyyy-mm-ddThh:ms:ss",
          "optimisticLockVerNo": 1,
          "deliveryStoreCode": null,
          "statusName": "Order New",
          "deliveryMethodName": null,
          "frameLineitemId": null,
          "frameItemId": null,
          "frameItemCategoryCode": null,
          "frameTaxClass": null,
          "frameListPrice": null,
          "frameDiscountPrice": null,
          "frameTaxPrice": null,
          "frameSalesPrice": null,
          "framePreparation1": null,
          "framePreparation2": null,
          "frameDeletedFlag": null,
          "frameRegisteredUserId": null,
          "frameRegisteredProgram": null,
          "frameRegisteredDatetime": null,
          "frameUpdatedUserId": null,
          "frameUpdatedProgram": null,
          "frameUpdatedDatetime": null,
          "frameOptimisticLockVerNo": null,
          "frameItemCode": null,
          "frameItemName": null,
          "frameItemNameKana": null,
          "frameItemNameEnglish": null,
          "frameItemNameSimplefied": null,
          "frameItemNameTraditional": null,
          "caseLineitemId": null,
          "caseItemId": null,
          "caseItemCategoryCode": null,
          "caseTaxClass": null,
          "caseListPrice": null,
          "caseDiscountPrice": null,
          "caseTaxPrice": null,
          "caseSalesPrice": null,
          "casePreparation1": null,
          "casePreparation2": null,
          "caseDeletedFlag": null,
          "caseRegisteredUserId": null,
          "caseRegisteredProgram": null,
          "caseRegisteredDatetime": null,
          "caseUpdatedUserId": null,
          "caseUpdatedProgram": null,
          "caseUpdatedDatetime": null,
          "caseOptimisticLockVerNo": null,
          "caseItemCode": null,
          "caseItemName": null,
          "caseItemNameKana": null,
          "caseItemNameEnglish": null,
          "caseItemNameSimplefied": null,
          "caseItemNameTraditional": null,
          "cerritoLineitemId": null,
          "cerritoItemId": null,
          "cerritoItemCategoryCode": null,
          "cerritoTaxClass": null,
          "cerritoListPrice": null,
          "cerritoDiscountPrice": null,
          "cerritoTaxPrice": null,
          "cerritoSalesPrice": null,
          "cerritoPreparation1": null,
          "cerritoPreparation2": null,
          "cerritoDeletedFlag": null,
          "cerritoRegisteredUserId": null,
          "cerritoRegisteredProgram": null,
          "cerritoRegisteredDatetime": null,
          "cerritoUpdatedUserId": null,
          "cerritoUpdatedProgram": null,
          "cerritoUpdatedDatetime": null,
          "cerritoOptimisticLockVerNo": null,
          "cerritoItemCode": null,
          "cerritoItemName": null,
          "cerritoItemNameKana": null,
          "cerritoItemNameEnglish": null,
          "cerritoItemNameSimplefied": null,
          "cerritoItemNameTraditional": null,
          "lensRightLineitemId": null,
          "lensRightItemId": null,
          "lensRightItemCategoryCode": null,
          "lensRightTaxClass": null,
          "lensRightListPrice": null,
          "lensRightDiscountPrice": null,
          "lensRightTaxPrice": null,
          "lensRightSalesPrice": null,
          "lensRightPreparation1": null,
          "lensRightPreparation2": null,
          "lensRightDeletedFlag": null,
          "lensRightRegisteredUserId": null,
          "lensRightRegisteredProgram": null,
          "lensRightRegisteredDatetime": null,
          "lensRightUpdatedUserId": null,
          "lensRightUpdatedProgram": null,
          "lensRightUpdatedDatetime": null,
          "lensRightOptimisticLockVerNo": null,
          "lensRightItemCode": null,
          "lensRightItemName": null,
          "lensRightItemNameKana": null,
          "lensRightItemNameEnglish": null,
          "lensRightItemNameSimplefied": null,
          "lensRightItemNameTraditional": null,
          "lensLeftLineitemId": null,
          "lensLeftItemId": null,
          "lensLeftItemCategoryCode": null,
          "lensLeftTaxClass": null,
          "lensLeftListPrice": null,
          "lensLeftDiscountPrice": null,
          "lensLeftTaxPrice": null,
          "lensLeftSalesPrice": null,
          "lensLeftPreparation1": null,
          "lensLeftPreparation2": null,
          "lensLeftDeletedFlag": null,
          "lensLeftRegisteredUserId": null,
          "lensLeftRegisteredProgram": null,
          "lensLeftRegisteredDatetime": null,
          "lensLeftUpdatedUserId": null,
          "lensLeftUpdatedProgram": null,
          "lensLeftUpdatedDatetime": null,
          "lensLeftOptimisticLockVerNo": null,
          "lensLeftItemCode": null,
          "lensLeftItemName": null,
          "lensLeftItemNameKana": null,
          "lensLeftItemNameEnglish": null,
          "lensLeftItemNameSimplefied": null,
          "lensLeftItemNameTraditional": null,
          "registeredLineitemId": null,
          "registeredItemId": null,
          "registeredItemCategoryCode": null,
          "registeredTaxClass": null,
          "registeredListPrice": null,
          "registeredDiscountPrice": null,
          "registeredTaxPrice": null,
          "registeredSalesPrice": null,
          "registeredPreparation1": null,
          "registeredPreparation2": null,
          "registeredDeletedFlag": null,
          "registeredRegisteredUserId": null,
          "registeredRegisteredProgram": null,
          "registeredRegisteredDatetime": null,
          "registeredUpdatedUserId": null,
          "registeredUpdatedProgram": null,
          "registeredUpdatedDatetime": null,
          "registeredOptimisticLockVerNo": null,
          "lopSalesColorNameLineitemId": null,
          "lopSalesColorNameItemId": null,
          "lopSalesColorNameItemCategoryCode": null,
          "lopSalesColorNameTaxClass": null,
          "lopSalesColorNameListPrice": null,
          "lopSalesColorNameDiscountPrice": null,
          "lopSalesColorNameTaxPrice": null,
          "lopSalesColorNameSalesPrice": null,
          "lopSalesColorNamePreparation1": null,
          "lopSalesColorNamePreparation2": null,
          "lopSalesColorNameDeletedFlag": null,
          "lopSalesColorNameRegisteredUserId": null,
          "lopSalesColorNameRegisteredProgram": null,
          "lopSalesColorNameRegisteredDatetime": null,
          "lopSalesColorNameUpdatedUserId": null,
          "lopSalesColorNameUpdatedProgram": null,
          "lopSalesColorNameUpdatedDatetime": null,
          "lopSalesColorNameOptimisticLockVerNo": null,
          "lopSalesColorNameLensOptionCode": null,
          "lopSalesColorNameLensOptionName": null,
          "lopSalesLensSpecLineitemId": null,
          "lopSalesLensSpecItemId": null,
          "lopSalesLensSpecItemCategoryCode": null,
          "lopSalesLensSpecTaxClass": null,
          "lopSalesLensSpecListPrice": null,
          "lopSalesLensSpecDiscountPrice": null,
          "lopSalesLensSpecTaxPrice": null,
          "lopSalesLensSpecSalesPrice": null,
          "lopSalesLensSpecPreparation1": null,
          "lopSalesLensSpecPreparation2": null,
          "lopSalesLensSpecDeletedFlag": null,
          "lopSalesLensSpecRegisteredUserId": null,
          "lopSalesLensSpecRegisteredProgram": null,
          "lopSalesLensSpecRegisteredDatetime": null,
          "lopSalesLensSpecUpdatedUserId": null,
          "lopSalesLensSpecUpdatedProgram": null,
          "lopSalesLensSpecUpdatedDatetime": null,
          "lopSalesLensSpecOptimisticLockVerNo": null,
          "lopSalesLensSpecLensOptionCode": null,
          "lopSalesLensSpecLensOptionName": null,
          "lopFocusCategoryLineitemId": null,
          "lopFocusCategoryItemId": null,
          "lopFocusCategoryItemCategoryCode": null,
          "lopFocusCategoryTaxClass": null,
          "lopFocusCategoryListPrice": null,
          "lopFocusCategoryDiscountPrice": null,
          "lopFocusCategoryTaxPrice": null,
          "lopFocusCategorySalesPrice": null,
          "lopFocusCategoryPreparation1": null,
          "lopFocusCategoryPreparation2": null,
          "lopFocusCategoryDeletedFlag": null,
          "lopFocusCategoryRegisteredUserId": null,
          "lopFocusCategoryRegisteredProgram": null,
          "lopFocusCategoryRegisteredDatetime": null,
          "lopFocusCategoryUpdatedUserId": null,
          "lopFocusCategoryUpdatedProgram": null,
          "lopFocusCategoryUpdatedDatetime": null,
          "lopFocusCategoryOptimisticLockVerNo": null,
          "lopFocusCategoryLensOptionCode": null,
          "lopFocusCategoryLensOptionName": null,
          "lopProgressiveCategoryLineitemId": null,
          "lopProgressiveCategoryItemId": null,
          "lopProgressiveCategoryItemCategoryCode": null,
          "lopProgressiveCategoryTaxClass": null,
          "lopProgressiveCategoryListPrice": null,
          "lopProgressiveCategoryDiscountPrice": null,
          "lopProgressiveCategoryTaxPrice": null,
          "lopProgressiveCategorySalesPrice": null,
          "lopProgressiveCategoryPreparation1": null,
          "lopProgressiveCategoryPreparation2": null,
          "lopProgressiveCategoryDeletedFlag": null,
          "lopProgressiveCategoryRegisteredUserId": null,
          "lopProgressiveCategoryRegisteredProgram": null,
          "lopProgressiveCategoryRegisteredDatetime": null,
          "lopProgressiveCategoryUpdatedUserId": null,
          "lopProgressiveCategoryUpdatedProgram": null,
          "lopProgressiveCategoryUpdatedDatetime": null,
          "lopProgressiveCategoryOptimisticLockVerNo": null,
          "lopProgressiveCategoryLensOptionCode": null,
          "lopProgressiveCategoryLensOptionName": null,
          "lopRefractiveIndexNameLineitemId": null,
          "lopRefractiveIndexNameItemId": null,
          "lopRefractiveIndexNameItemCategoryCode": null,
          "lopRefractiveIndexNameTaxClass": null,
          "lopRefractiveIndexNameListPrice": null,
          "lopRefractiveIndexNameDiscountPrice": null,
          "lopRefractiveIndexNameTaxPrice": null,
          "lopRefractiveIndexNameSalesPrice": null,
          "lopRefractiveIndexNamePreparation1": null,
          "lopRefractiveIndexNamePreparation2": null,
          "lopRefractiveIndexNameDeletedFlag": null,
          "lopRefractiveIndexNameRegisteredUserId": null,
          "lopRefractiveIndexNameRegisteredProgram": null,
          "lopRefractiveIndexNameRegisteredDatetime": null,
          "lopRefractiveIndexNameUpdatedUserId": null,
          "lopRefractiveIndexNameUpdatedProgram": null,
          "lopRefractiveIndexNameUpdatedDatetime": null,
          "lopRefractiveIndexNameOptimisticLockVerNo": null,
          "lopRefractiveIndexNameLensOptionCode": null,
          "lopRefractiveIndexNameLensOptionName": null,
          "lopRimlessFinishingCategoryLineitemId": null,
          "lopRimlessFinishingCategoryItemId": null,
          "lopRimlessFinishingCategoryItemCategoryCode": null,
          "lopRimlessFinishingCategoryTaxClass": null,
          "lopRimlessFinishingCategoryListPrice": null,
          "lopRimlessFinishingCategoryDiscountPrice": null,
          "lopRimlessFinishingCategoryTaxPrice": null,
          "lopRimlessFinishingCategorySalesPrice": null,
          "lopRimlessFinishingCategoryPreparation1": null,
          "lopRimlessFinishingCategoryPreparation2": null,
          "lopRimlessFinishingCategoryDeletedFlag": null,
          "lopRimlessFinishingCategoryRegisteredUserId": null,
          "lopRimlessFinishingCategoryRegisteredProgram": null,
          "lopRimlessFinishingCategoryRegisteredDatetime": null,
          "lopRimlessFinishingCategoryUpdatedUserId": null,
          "lopRimlessFinishingCategoryUpdatedProgram": null,
          "lopRimlessFinishingCategoryUpdatedDatetime": null,
          "lopRimlessFinishingCategoryOptimisticLockVerNo": null,
          "lopRimlessFinishingCategoryLensOptionCode": null,
          "lopRimlessFinishingCategoryLensOptionName": null
        }
      ]
    }
  }
}

// カート・カタログ取得API
export const getCartInfoResponse = {
  ok: true,
  status: 200,
  data: {
    "cart": {
      "cartId": 1,
      "customerName": "John Smith",
      "phoneNumber": "4158726498",
      "discountPrice": 0,
      "subtotal": 0,
      "totalDiscountPrice": 0,
      "totalTaxPrice": 0,
      "totalSalesPrice": 0,
      "receptionNumber": "250123US000003",
      "deletedFlag": 0,
      "registeredUserId": "STAFF_A",
      "registeredProgram": "STAFF_A",
      "registeredDatetime": "yyyy-mm-ddThh:ms:ss",
      "updatedUserId": "STAFF_A",
      "updatedProgram": "STAFF_A",
      "updatedDatetime": "yyyy-mm-ddThh:ms:ss",
      "optimisticLockVerNo": 1,
      "receptionStoreId": 1143416,
      "receptionStoreCode": "83005",
      "itemGroups": [
        {
          "lineitemGroupId": 1,
          "itemGroupCode": "250123US000003-1",
          "statusCode": "101",
          "callingStatusCode": "001",
          "callingNumber": "A1",
          "prescriptionRegistCode": "002",
          "deliveryMethodCode": null,
          "deliveryDatetime": null,
          "deliveryStoreId": null,
          "customerName": null,
          "phoneNumber": null,
          "shippingAddressZip": null,
          "shippingAddress1": null,
          "shippingAddress2": null,
          "shippingAddress3": null,
          "shippingAddress4": null,
          "note": null,
          "discountPrice": 0,
          "subtotal": 0,
          "totalDiscountPrice": 0,
          "totalTaxPrice": 0,
          "salesPrice": 0,
          "deletedFlag": 0,
          "registeredUserId": "STAFF_A",
          "registeredProgram": "STAFF_A",
          "registeredDatetime": "yyyy-mm-ddThh:ms:ss",
          "updatedUserId": "STAFF_A",
          "updatedProgram": "STAFF_A",
          "updatedDatetime": "yyyy-mm-ddThh:ms:ss",
          "optimisticLockVerNo": 1,
          "deliveryStoreCode": null,
          "statusName": "Order New",
          "deliveryMethodName": null,
          "frameLineitemId": null,
          "frameItemId": null,
          "frameItemCategoryCode": null,
          "frameTaxClass": null,
          "frameListPrice": null,
          "frameDiscountPrice": null,
          "frameTaxPrice": null,
          "frameSalesPrice": null,
          "framePreparation1": null,
          "framePreparation2": null,
          "frameDeletedFlag": null,
          "frameRegisteredUserId": null,
          "frameRegisteredProgram": null,
          "frameRegisteredDatetime": null,
          "frameUpdatedUserId": null,
          "frameUpdatedProgram": null,
          "frameUpdatedDatetime": null,
          "frameOptimisticLockVerNo": null,
          "frameItemCode": null,
          "frameItemName": null,
          "frameItemNameKana": null,
          "frameItemNameEnglish": null,
          "frameItemNameSimplefied": null,
          "frameItemNameTraditional": null,
          "caseLineitemId": null,
          "caseItemId": null,
          "caseItemCategoryCode": null,
          "caseTaxClass": null,
          "caseListPrice": null,
          "caseDiscountPrice": null,
          "caseTaxPrice": null,
          "caseSalesPrice": null,
          "casePreparation1": null,
          "casePreparation2": null,
          "caseDeletedFlag": null,
          "caseRegisteredUserId": null,
          "caseRegisteredProgram": null,
          "caseRegisteredDatetime": null,
          "caseUpdatedUserId": null,
          "caseUpdatedProgram": null,
          "caseUpdatedDatetime": null,
          "caseOptimisticLockVerNo": null,
          "caseItemCode": null,
          "caseItemName": null,
          "caseItemNameKana": null,
          "caseItemNameEnglish": null,
          "caseItemNameSimplefied": null,
          "caseItemNameTraditional": null,
          "cerritoLineitemId": null,
          "cerritoItemId": null,
          "cerritoItemCategoryCode": null,
          "cerritoTaxClass": null,
          "cerritoListPrice": null,
          "cerritoDiscountPrice": null,
          "cerritoTaxPrice": null,
          "cerritoSalesPrice": null,
          "cerritoPreparation1": null,
          "cerritoPreparation2": null,
          "cerritoDeletedFlag": null,
          "cerritoRegisteredUserId": null,
          "cerritoRegisteredProgram": null,
          "cerritoRegisteredDatetime": null,
          "cerritoUpdatedUserId": null,
          "cerritoUpdatedProgram": null,
          "cerritoUpdatedDatetime": null,
          "cerritoOptimisticLockVerNo": null,
          "cerritoItemCode": null,
          "cerritoItemName": null,
          "cerritoItemNameKana": null,
          "cerritoItemNameEnglish": null,
          "cerritoItemNameSimplefied": null,
          "cerritoItemNameTraditional": null,
          "lensRightLineitemId": null,
          "lensRightItemId": null,
          "lensRightItemCategoryCode": null,
          "lensRightTaxClass": null,
          "lensRightListPrice": null,
          "lensRightDiscountPrice": null,
          "lensRightTaxPrice": null,
          "lensRightSalesPrice": null,
          "lensRightPreparation1": null,
          "lensRightPreparation2": null,
          "lensRightDeletedFlag": null,
          "lensRightRegisteredUserId": null,
          "lensRightRegisteredProgram": null,
          "lensRightRegisteredDatetime": null,
          "lensRightUpdatedUserId": null,
          "lensRightUpdatedProgram": null,
          "lensRightUpdatedDatetime": null,
          "lensRightOptimisticLockVerNo": null,
          "lensRightItemCode": null,
          "lensRightItemName": null,
          "lensRightItemNameKana": null,
          "lensRightItemNameEnglish": null,
          "lensRightItemNameSimplefied": null,
          "lensRightItemNameTraditional": null,
          "lensLeftLineitemId": null,
          "lensLeftItemId": null,
          "lensLeftItemCategoryCode": null,
          "lensLeftTaxClass": null,
          "lensLeftListPrice": null,
          "lensLeftDiscountPrice": null,
          "lensLeftTaxPrice": null,
          "lensLeftSalesPrice": null,
          "lensLeftPreparation1": null,
          "lensLeftPreparation2": null,
          "lensLeftDeletedFlag": null,
          "lensLeftRegisteredUserId": null,
          "lensLeftRegisteredProgram": null,
          "lensLeftRegisteredDatetime": null,
          "lensLeftUpdatedUserId": null,
          "lensLeftUpdatedProgram": null,
          "lensLeftUpdatedDatetime": null,
          "lensLeftOptimisticLockVerNo": null,
          "lensLeftItemCode": null,
          "lensLeftItemName": null,
          "lensLeftItemNameKana": null,
          "lensLeftItemNameEnglish": null,
          "lensLeftItemNameSimplefied": null,
          "lensLeftItemNameTraditional": null,
          "registeredLineitemId": null,
          "registeredItemId": null,
          "registeredItemCategoryCode": null,
          "registeredTaxClass": null,
          "registeredListPrice": null,
          "registeredDiscountPrice": null,
          "registeredTaxPrice": null,
          "registeredSalesPrice": null,
          "registeredPreparation1": null,
          "registeredPreparation2": null,
          "registeredDeletedFlag": null,
          "registeredRegisteredUserId": null,
          "registeredRegisteredProgram": null,
          "registeredRegisteredDatetime": null,
          "registeredUpdatedUserId": null,
          "registeredUpdatedProgram": null,
          "registeredUpdatedDatetime": null,
          "registeredOptimisticLockVerNo": null,
          "lopSalesColorNameLineitemId": null,
          "lopSalesColorNameItemId": null,
          "lopSalesColorNameItemCategoryCode": null,
          "lopSalesColorNameTaxClass": null,
          "lopSalesColorNameListPrice": null,
          "lopSalesColorNameDiscountPrice": null,
          "lopSalesColorNameTaxPrice": null,
          "lopSalesColorNameSalesPrice": null,
          "lopSalesColorNamePreparation1": null,
          "lopSalesColorNamePreparation2": null,
          "lopSalesColorNameDeletedFlag": null,
          "lopSalesColorNameRegisteredUserId": null,
          "lopSalesColorNameRegisteredProgram": null,
          "lopSalesColorNameRegisteredDatetime": null,
          "lopSalesColorNameUpdatedUserId": null,
          "lopSalesColorNameUpdatedProgram": null,
          "lopSalesColorNameUpdatedDatetime": null,
          "lopSalesColorNameOptimisticLockVerNo": null,
          "lopSalesColorNameLensOptionCode": null,
          "lopSalesColorNameLensOptionName": null,
          "lopSalesLensSpecLineitemId": null,
          "lopSalesLensSpecItemId": null,
          "lopSalesLensSpecItemCategoryCode": null,
          "lopSalesLensSpecTaxClass": null,
          "lopSalesLensSpecListPrice": null,
          "lopSalesLensSpecDiscountPrice": null,
          "lopSalesLensSpecTaxPrice": null,
          "lopSalesLensSpecSalesPrice": null,
          "lopSalesLensSpecPreparation1": null,
          "lopSalesLensSpecPreparation2": null,
          "lopSalesLensSpecDeletedFlag": null,
          "lopSalesLensSpecRegisteredUserId": null,
          "lopSalesLensSpecRegisteredProgram": null,
          "lopSalesLensSpecRegisteredDatetime": null,
          "lopSalesLensSpecUpdatedUserId": null,
          "lopSalesLensSpecUpdatedProgram": null,
          "lopSalesLensSpecUpdatedDatetime": null,
          "lopSalesLensSpecOptimisticLockVerNo": null,
          "lopSalesLensSpecLensOptionCode": null,
          "lopSalesLensSpecLensOptionName": null,
          "lopFocusCategoryLineitemId": null,
          "lopFocusCategoryItemId": null,
          "lopFocusCategoryItemCategoryCode": null,
          "lopFocusCategoryTaxClass": null,
          "lopFocusCategoryListPrice": null,
          "lopFocusCategoryDiscountPrice": null,
          "lopFocusCategoryTaxPrice": null,
          "lopFocusCategorySalesPrice": null,
          "lopFocusCategoryPreparation1": null,
          "lopFocusCategoryPreparation2": null,
          "lopFocusCategoryDeletedFlag": null,
          "lopFocusCategoryRegisteredUserId": null,
          "lopFocusCategoryRegisteredProgram": null,
          "lopFocusCategoryRegisteredDatetime": null,
          "lopFocusCategoryUpdatedUserId": null,
          "lopFocusCategoryUpdatedProgram": null,
          "lopFocusCategoryUpdatedDatetime": null,
          "lopFocusCategoryOptimisticLockVerNo": null,
          "lopFocusCategoryLensOptionCode": null,
          "lopFocusCategoryLensOptionName": null,
          "lopProgressiveCategoryLineitemId": null,
          "lopProgressiveCategoryItemId": null,
          "lopProgressiveCategoryItemCategoryCode": null,
          "lopProgressiveCategoryTaxClass": null,
          "lopProgressiveCategoryListPrice": null,
          "lopProgressiveCategoryDiscountPrice": null,
          "lopProgressiveCategoryTaxPrice": null,
          "lopProgressiveCategorySalesPrice": null,
          "lopProgressiveCategoryPreparation1": null,
          "lopProgressiveCategoryPreparation2": null,
          "lopProgressiveCategoryDeletedFlag": null,
          "lopProgressiveCategoryRegisteredUserId": null,
          "lopProgressiveCategoryRegisteredProgram": null,
          "lopProgressiveCategoryRegisteredDatetime": null,
          "lopProgressiveCategoryUpdatedUserId": null,
          "lopProgressiveCategoryUpdatedProgram": null,
          "lopProgressiveCategoryUpdatedDatetime": null,
          "lopProgressiveCategoryOptimisticLockVerNo": null,
          "lopProgressiveCategoryLensOptionCode": null,
          "lopProgressiveCategoryLensOptionName": null,
          "lopRefractiveIndexNameLineitemId": null,
          "lopRefractiveIndexNameItemId": null,
          "lopRefractiveIndexNameItemCategoryCode": null,
          "lopRefractiveIndexNameTaxClass": null,
          "lopRefractiveIndexNameListPrice": null,
          "lopRefractiveIndexNameDiscountPrice": null,
          "lopRefractiveIndexNameTaxPrice": null,
          "lopRefractiveIndexNameSalesPrice": null,
          "lopRefractiveIndexNamePreparation1": null,
          "lopRefractiveIndexNamePreparation2": null,
          "lopRefractiveIndexNameDeletedFlag": null,
          "lopRefractiveIndexNameRegisteredUserId": null,
          "lopRefractiveIndexNameRegisteredProgram": null,
          "lopRefractiveIndexNameRegisteredDatetime": null,
          "lopRefractiveIndexNameUpdatedUserId": null,
          "lopRefractiveIndexNameUpdatedProgram": null,
          "lopRefractiveIndexNameUpdatedDatetime": null,
          "lopRefractiveIndexNameOptimisticLockVerNo": null,
          "lopRefractiveIndexNameLensOptionCode": null,
          "lopRefractiveIndexNameLensOptionName": null,
          "lopRimlessFinishingCategoryLineitemId": null,
          "lopRimlessFinishingCategoryItemId": null,
          "lopRimlessFinishingCategoryItemCategoryCode": null,
          "lopRimlessFinishingCategoryTaxClass": null,
          "lopRimlessFinishingCategoryListPrice": null,
          "lopRimlessFinishingCategoryDiscountPrice": null,
          "lopRimlessFinishingCategoryTaxPrice": null,
          "lopRimlessFinishingCategorySalesPrice": null,
          "lopRimlessFinishingCategoryPreparation1": null,
          "lopRimlessFinishingCategoryPreparation2": null,
          "lopRimlessFinishingCategoryDeletedFlag": null,
          "lopRimlessFinishingCategoryRegisteredUserId": null,
          "lopRimlessFinishingCategoryRegisteredProgram": null,
          "lopRimlessFinishingCategoryRegisteredDatetime": null,
          "lopRimlessFinishingCategoryUpdatedUserId": null,
          "lopRimlessFinishingCategoryUpdatedProgram": null,
          "lopRimlessFinishingCategoryUpdatedDatetime": null,
          "lopRimlessFinishingCategoryOptimisticLockVerNo": null,
          "lopRimlessFinishingCategoryLensOptionCode": null,
          "lopRimlessFinishingCategoryLensOptionName": null
        }
      ]
    }
  }
}

// 販売用レンズ検索項目検索API
export const getSalesLensSearchResponse = {
  ok: true,
  status: 200,
  data: {
    "offset": 0,
    "count": 1,
    "limit": 100000,
    "totalResults": 1,
    "hasMore": false,
    "records": [
      {
        "itemId": 1421060,
        "itemCode": "MRF-23A-011-128",
        "itemName": "Basic Matte",
        "itemNameKana": "MRF-23A-011-128",
        "itemNameEnglish": "Basic Matte",
        "itemNameSimplified": "Basic Matte",
        "itemNameTraditional": "Basic Matte",
        "itemDivision": "1",
        "standardPlanName": null,
        "gtin": null,
        "itemDeploymentStartDate": "2013-12-31T15:00:00",
        "itemDeploymentEndDate": "2099-12-31T00:00:00",
        "storeDisplayFlag": "0",
        "price": 6600.00,
        "priceUS": 90.00,
        "singleItemSalesFlag": 0,
        "ecSalesFlag": 1,
        "storeSalesFlag": 1,
        "salesItemName": "Basic Matte",
        "deletedFlag": 0,
        "updatedUserId": "Step2_test",
        "updatedDatetime": "2024-11-12T05:01:00",
        "frameModelColor": {
          "frameModelColorId": 6001,
          "frameModelColorCode": "MRF-23A-011-128",
          "frameModelColorName": "Basic Matte",
          "frameColorId": 1090,
          "frameColorCode": "128",
          "frameColorName": "128"
        },
        "frameModel": {
          "frameModelId": 7001,
          "frameModelCode": "MRF-23A-011",
          "lensModelId": 11001,
          "lensModelCode": "01",
          "lensModelName": "スクエア",
          "frameSizeNameId": 12002,
          "frameSizeNameCode": "02",
          "frameSizeName": "Medium",
          "templeMaterialId": 13008,
          "templeMaterialCode": "01",
          "templeMaterialName": "樹脂",
          "frontMaterialId": 13001,
          "frontMaterialCode": "01",
          "frontMaterialName": "樹脂",
          "nosePadMaterialId": 13015,
          "nosePadMaterialCode": "01",
          "nosePadMaterialName": "樹脂",
          "nosePadShapeId": 15002,
          "nosePadShapeCode": "02",
          "nosePadShapeName": "フレーム一体型",
          "weight": 16.00,
          "frontWidth": 124.00,
          "bridgeWidth": 16.00,
          "lensWidth": 54.00,
          "verticalWidth": 31.00,
          "templeLength": 149.00,
          "rimShapeId": 16001,
          "rimShapeCode": "01",
          "rimShapeName": "フルリム",
          "checkMarginByRimShapeId": 17001,
          "diameterShortageCheckMargin": 2.0
        },
        "frameName": {
          "frameNameId": 8001,
          "frameNameCode": "01",
          "frameName": "テストシリーズ",
          "targetGenderId": 9001,
          "targetGenderCode": "01",
          "targetGenderName": "MEN",
          "targetAgeId": 10003,
          "targetAgeCode": "03",
          "targetAgeName": "アダルト",
          "planYear": 23,
          "season": "AW"
        },
        "itemSalesByCountry": {
          "countryId": 1143430,
          "countryCodeAlpha2": "US",
          "countryCodeAlpha3": "USA",
          "countryName": "アメリカ合衆国"
        }
      }
    ]
  }
}

// 商品マスタ検索API
export const getItemsResponse = {
  ok: true,
  status: 200,
  data: {
    "offset": 0,
    "count": 1,
    "limit": 100000,
    "totalResults": 1,
    "hasMore": false,
    "records": [
      {
        "itemId": 1421060,
        "itemCode": "MRF-23A-011-128",
        "itemName": "Basic Matte",
        "itemNameKana": "MRF-23A-011-128",
        "itemNameEnglish": "Basic Matte",
        "itemNameSimplified": "Basic Matte",
        "itemNameTraditional": "Basic Matte",
        "itemDivision": "1",
        "standardPlanName": null,
        "gtin": null,
        "itemDeploymentStartDate": "2013-12-31T15:00:00",
        "itemDeploymentEndDate": "2099-12-31T00:00:00",
        "storeDisplayFlag": "0",
        "price": 6600.00,
        "priceUS": 90.00,
        "singleItemSalesFlag": 0,
        "ecSalesFlag": 1,
        "storeSalesFlag": 1,
        "salesItemName": "Basic Matte",
        "deletedFlag": 0,
        "updatedUserId": "Step2_test",
        "updatedDatetime": "2024-11-12T05:01:00",
        "itemSalesByCountries": [
          {
            "countryId": 1143430,
            "countryCodeAlpha2": "US",
            "countryCodeAlpha3": "USA",
            "countryName": "アメリカ合衆国"
          }
        ]
      }
    ]
  }
}

// 価格・税計算API
export const postCalculateAmount = {
  ok: true,
  status: 200,
  data: {
    "countryCodeAlpha2": "US",
    "calculationBaseDate": "2025-01-28",
    "glassLines": [
      {
        "frameItemId": 1421060,
        "frameListPrice": 140.00,
        "frameSellingPrice": 140.00,
        "frameTaxCode": "FRAME_TAX_001",
        "frameTaxAmount": 0,
        "caseTaxAmount": 0,
        "lopSalesColorNameTaxAmount": 0,
        "lopSalesLensSpecTaxAmount": 0,
        "lopFocusCategoryTaxAmount": 0,
        "lopProgressiveCategoryTaxAmount": 0,
        "lopRefractiveIndexNameTaxAmount": 0,
        "lopRimlessFinishingCategoryTaxAmount": 0,
        "subtotalListAmount": 140.00,
        "subtotalSellingAmount": 140.00,
        "subtotalTaxAmount": 0,
        "subtotalAmount": 140.00
      }
    ],
    "totalListAmount": 140.00,
    "totalSellingAmount": 140.00,
    "subtotalTaxLines": [],
    "totalTaxAmount": 0,
    "totalAmount": 140.00
  }
}

// カート情報登録API
export const postLineitems = {
  ok: true,
  status: 200,
}

// 受付履歴更新API
export const postReceptionEvents = {
  ok: true,
  status: 200,
}
