// 待ち状況取得APIレスポンス
const receptionInfoBase = {
  "registeredDate": "2025-03-28",
  "visitingPurposeCode": "010",
  "customerIssueCode": "001",
  "prescriptionRegistCode": "001",
  "callingNumber": "A44",
  "receptionNumber": "241230US00001",
  "statusCode": "101",
  "callingStatusCode": "001",
  "countryCodeAlpha2": "US",
  "storeId": 83005,
  "customerName": "John Doe",
  "phoneNumber": "07012345678",
  "jinsAccountId": null,
  "registeredUserId": "JINS0001",
  "registeredProgram": "Step2_test",
  "registeredDatetime": "2999-12-31T09:01:00",
  "updatedUserId": "JINS0001",
  "updatedProgram": "Step2_test",
  "updatedDatetime": "2025/03/28T05:01:00"
};

export const getReceptionsResponses = {
  // ケース１：正常系
  case1: {
    ok: true,
    status: 200,
    data: {
      "receptionInfos": [
        {
          ...receptionInfoBase,
          "callingNumber": "A44",
          "receptionNumber": "241230US00097",
          "statusCode": "101",
          "callingStatusCode": "001",
        },
        {
          ...receptionInfoBase,
          "callingNumber": "A44",
          "receptionNumber": "241230US00098",
          "statusCode": "101",
          "callingStatusCode": "002",
        },
        {
          ...receptionInfoBase,
          "callingNumber": "A44",
          "receptionNumber": "241230US00099",
          "statusCode": "101",
          "callingStatusCode": "001",
        },
        {
          ...receptionInfoBase,
          "callingNumber": "A44",
          "receptionNumber": "241230US00001",
          "statusCode": "101",
          "callingStatusCode": "001",
        },
        {
          ...receptionInfoBase,
          "callingNumber": "A45",
          "receptionNumber": "241230US00002",
          "statusCode": "101",
          "callingStatusCode": "001",
        }
      ]
    }
  },
  case2: {
    ok: false,
    status: 404,
    data: {
      "code":"COM_0002"
      ,"message":"Specified data not found."
      ,"jinsTraceId":"test-jins-trace-id"
      ,"details":null
    }
  },
  case3: {
    ok: true,
    status: 200,
    data: {
      "receptionInfos": [
        {
          ...receptionInfoBase,
          "callingNumber": "F44",
          "receptionNumber": "241230US00001",
          "statusCode": "101",
          "callingStatusCode": "001",
        }
      ]
    }
  },
  // ケース4：異常系ステータス５００
  case4: {
    ok: false,
    status: 500,
    data: {}
  },
  case5: {
    ok: true,
    status: 200,
    data: {
      "receptionInfos": [
        {
          ...receptionInfoBase,
          "callingNumber": "F44",
          "receptionNumber": "241230US00001",
          "statusCode": "101",
          "callingStatusCode": "001",
        }
      ]
    }
  },
  case6: {
    ok: true,
    status: 200,
    data: {
      "receptionInfos": [
        {
          ...receptionInfoBase,
          customerIssueCode: null,
          prescriptionRegistCode: null,
        }
      ]
    }
  },
}

// 呼出し管理情報取得APIレスポンス
export const getCallManagementResponses = {
  case1: {
    ok: true,
    status: 200,
    data: {
      "callManagementInfo": {
        "timeRequiredUntilCall": 200,
        "availableLines": 10,
        "receptionCloseTime": "08:00:00",
        "processingCloseTime": "20:00:00"
      }
    }
  },
  // ケース2：異常系ステータス５００
  case2: {
    ok: false,
    status: 500,
    data: {}
  },
  case3: {
    ok: true,
    status: 200,
    data: {
      "callManagementInfo": {
        "availableLines": 10,
      }
    }
  },
}

// カートカタログ取得APIレスポンス
export const cartInfoGetResponse = {
  // ケース１：正常系データ有
  case1 : {
    ok: true,
    status: 200,
    data: {
      cart: {
        cartId: 123,
        receptionNumber: "241031US000001",
        deletedFlag: 0,
        receptionStoreId: 111,
        receptionStoreCode: "83005",
        itemGroups: [
          {
            lineitemGroupId: 1111110,
            cartId: 123,
            itemGroupCode: "241031US000001-1",
            statusCode: "200",
            callingStatusCode: "000",
            callingNumber: "B1",
            prescriptionRegistCode: "002",
            deliveryMethodCode: null,
            deliveryDatetime: "2024-10-31T11:00:00.000",
            deliveryStoreCode: "80001",
            customerName: "John",
            phoneNumber: "09012341234",
            shippingAddressZip: "1111111",
            shippingAddress1: "Address1",
            shippingAddress2: "Address2",
            shippingAddress3: "Address3",
            shippingAddress4: "Address4",
            isExchangeLens: true,
            isWaitingLens: false,
            isDeliveryToday: false,
            note: "メガネ１のメモ欄",
            discountPrice: 0,
            subtotal: 220,
            totalDiscountPrice: 0,
            totalTaxPrice: 20,
            salesPrice: 200,
            deletedFlag: 0,
            jinsAccountId: null,
            registeredUserId: "STAFF_A",
            registeredProgram: "550e8400-e29b-41d4-a716-446655440000",
            registeredDatetime: "2024/10/31 18:48:12.000",
            updatedUserId: "STAFF_A",
            updatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            updatedDatetime: "2024/10/31 18:48:12.000",
            optimisticLockVerNo: 1,
            statusName: "Check-in",
            deliveryMethodName: "Hand over here",
            frameLineitemId: 1,
            frameItemId: 11111,
            frameItemCategoryCode: "01",
            frameTaxClass: "1",
            frameListPrice: 100,
            frameDiscountPrice: 1,
            frameTaxPrice: 2,
            frameSalesPrice: 101,
            framePreparation1: null,
            framePreparation2: null,
            frameDeletedFlag: 0,
            frameRegisteredUserId: "STAFF_A",
            frameRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            frameRegisteredDatetime: "2024/10/31 18:48:12.000",
            frameUpdatedUserId: "STAFF_A",
            frameUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            frameUpdatedDatetime: "2024/10/31 18:48:12.000",
            frameOptimisticLockVerNo: 1,
            frameItemCode: "MMF-24S-U019U-94",
            frameItemName: "Multi size metal - Browline U019 Medium Could Be Three Lines",
            frameItemNameKana: null,
            frameItemNameEnglish: "Multi size metal - Browline U019 Medium Could Be Three Lines",
            frameItemNameSimplefied: null,
            frameItemNameTraditional: null,
            caseLineitemId: 2,
            caseItemId: 144,
            caseItemCategoryCode: "03",
            caseTaxClass: "1",
            caseListPrice: 0,
            caseDiscountPrice: 0,
            caseTaxPrice: 0,
            caseSalesPrice: 100,
            casePreparation1: null,
            casePreparation2: null,
            caseDeletedFlag: 0,
            caseRegisteredUserId: "STAFF_A",
            caseRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            caseRegisteredDatetime: "2024/10/31 18:48:12.000",
            caseUpdatedUserId: "STAFF_A",
            caseUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            caseUpdatedDatetime: "2024/10/31 18:48:12.000",
            caseOptimisticLockVerNo: 1,
            caseItemCode: "SampleCode",
            caseItemName: "Education case",
            caseItemNameKana: null,
            caseItemNameEnglish: "Education case",
            caseItemNameSimplefied: null,
            caseItemNameTraditional: null,
            isCaseNone: false,
            cerritoLineitemId: 3,
            cerritoItemId: 12345,
            cerritoItemCategoryCode: "04",
            cerritoTaxClass: "1",
            cerritoListPrice: 0,
            cerritoDiscountPrice: 0,
            cerritoTaxPrice: 0,
            cerritoSalesPrice: 0,
            cerritoPreparation1: null,
            cerritoPreparation2: null,
            cerritoDeletedFlag: 0,
            cerritoRegisteredUserId: "STAFF_A",
            cerritoRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            cerritoRegisteredDatetime: "2024/10/31 18:48:12.000",
            cerritoUpdatedUserId: "STAFF_A",
            cerritoUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            cerritoUpdatedDatetime: "2024/10/31 18:48:12.000",
            cerritoOptimisticLockVerNo: 1,
            cerritoItemCode: null,
            cerritoItemName: "CerritoName",
            cerritoItemNameKana: null,
            cerritoItemNameEnglish: "CerritoName",
            cerritoItemNameSimplefied: null,
            cerritoItemNameTraditional: null,
            registeredLineitemId: 4,
            registeredItemId: null,
            registeredItemCategoryCode: "09",
            registeredTaxClass: "0",
            registeredListPrice: 0,
            registeredDiscountPrice: 0,
            registeredTaxPrice: 0,
            registeredSalesPrice: 0,
            registeredPreparation1: "{  \"prescriptionId\": null,  \"registrationMethodCode\": \"002\",  \"prescriptionInfo\": {    \"vision\": null,    \"perspectiveTypeCode\": \"004\",    \"eyepointRight\": 1.0,    \"eyepointLeft\": -1.0,    \"pdRight\": 40.00,    \"pdLeft\": 60.00,    \"sphRight\": 29.00,    \"sphLeft\": 26.75,    \"cylRight\": 8.75,    \"cylLeft\": -1.50,    \"axisRight\": 180,    \"axisLeft\": 170,    \"addRight\": 9.00,    \"addLeft\": 2.50,    \"prismFlag\": true,    \"prism01Right\": 1.00,    \"prism01Left\": 1.00,    \"baseHRight\": \"BO\",    \"baseHLeft\": \"BO\",    \"prism02Right\": 0.50,    \"prism02Left\": 0.50,    \"baseVRight\": \"BU\",    \"baseVLeft\": \"BD\"  },  \"prescriptionExpiration\": \"12/24/2025\" }",
            registeredPreparation2: "aaaaa",
            registeredDeletedFlag: 0,
            registeredRegisteredUserId: "STAFF_A",
            registeredRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            registeredRegisteredDatetime: "2024/10/31 18:48:12.000",
            registeredUpdatedUserId: "STAFF_A",
            registeredUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            registeredUpdatedDatetime: "2024/10/31 18:48:12.000",
            registeredOptimisticLockVerNo: 1,
            lensRightLineitemId: null,
            lensRightItemId: null,
            lensRightItemCategoryCode: null,
            lensRightTaxClass: "1",
            lensRightListPrice: 0,
            lensRightDiscountPrice: 0,
            lensRightTaxPrice: 0,
            lensRightSalesPrice: 0,
            lensRightPreparation1: null,
            lensRightPreparation2: null,
            lensRightDeletedFlag: 0,
            lensRightRegisteredUserId: "STAFF_A",
            lensRightRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            lensRightRegisteredDatetime: "2024/10/31 18:48:12.000",
            lensRightUpdatedUserId: "STAFF_A",
            lensRightUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            lensRightUpdatedDatetime: "2024/10/31 18:48:12.000",
            lensRightOptimisticLockVerNo: 1,
            lensRightItemCode: null,
            lensRightItemName: null,
            lensRightItemNameKana: null,
            lensRightItemNameEnglish: null,
            lensRightItemNameSimplefied: null,
            lensRightItemNameTraditional: null,
            lensLeftLineitemId: null,
            lensLeftItemId: null,
            lensLeftItemCategoryCode: null,
            lensLeftTaxClass: "1",
            lensLeftListPrice: 0,
            lensLeftDiscountPrice: 0,
            lensLeftTaxPrice: 0,
            lensLeftSalesPrice: 0,
            lensLeftPreparation1: null,
            lensLeftPreparation2: null,
            lensLeftDeletedFlag: 0,
            lensLeftRegisteredUserId: "STAFF_A",
            lensLeftRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            lensLeftRegisteredDatetime: "2024/10/31 18:48:12.000",
            lensLeftUpdatedUserId: "STAFF_A",
            lensLeftUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            lensLeftUpdatedDatetime: "2024/10/31 18:48:12.000",
            lensLeftOptimisticLockVerNo: 1,
            lensLeftItemCode: null,
            lensLeftItemName: null,
            lensLeftItemNameKana: null,
            lensLeftItemNameEnglish: null,
            lensLeftItemNameSimplefied: null,
            lensLeftItemNameTraditional: null,
            lopSalesColorNameLineitemId: null,
            lopSalesColorNameItemId: null,
            lopSalesColorNameItemCategoryCode: null,
            lopSalesColorNameTaxClass: "1",
            lopSalesColorNameListPrice: 0,
            lopSalesColorNameDiscountPrice: 0,
            lopSalesColorNameTaxPrice: 0,
            lopSalesColorNameSalesPrice: 0,
            lopSalesColorNamePreparation1: null,
            lopSalesColorNamePreparation2: null,
            lopSalesColorNameDeletedFlag: 0,
            lopSalesColorNameRegisteredUserId: "STAFF_A",
            lopSalesColorNameRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopSalesColorNameRegisteredDatetime: "2024/10/31 18:48:12.000",
            lopSalesColorNameUpdatedUserId: "STAFF_A",
            lopSalesColorNameUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopSalesColorNameUpdatedDatetime: "2024/10/31 18:48:12.000",
            lopSalesColorNameOptimisticLockVerNo: 1,
            lopSalesColorNameLensOptionCode: "Csample999",
            lopSalesColorNameLensOptionName: "Clear Lens",
            lopSalesLensSpecLineitemId: null,
            lopSalesLensSpecItemId: null,
            lopSalesLensSpecItemCategoryCode: null,
            lopSalesLensSpecTaxClass: "1",
            lopSalesLensSpecListPrice: 0,
            lopSalesLensSpecDiscountPrice: 0,
            lopSalesLensSpecTaxPrice: 0,
            lopSalesLensSpecSalesPrice: 0,
            lopSalesLensSpecPreparation1: null,
            lopSalesLensSpecPreparation2: null,
            lopSalesLensSpecDeletedFlag: 0,
            lopSalesLensSpecRegisteredUserId: "STAFF_A",
            lopSalesLensSpecRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopSalesLensSpecRegisteredDatetime: "2024/10/31 18:48:12.000",
            lopSalesLensSpecUpdatedUserId: "STAFF_A",
            lopSalesLensSpecUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopSalesLensSpecUpdatedDatetime: "2024/10/31 18:48:12.000",
            lopSalesLensSpecOptimisticLockVerNo: 1,
            lopSalesLensSpecLensOptionCode: "Ssample999",
            lopSalesLensSpecLensOptionName: "Standard",
            lopFocusCategoryLineitemId: null,
            lopFocusCategoryItemId: "241031US000001-1",
            lopFocusCategoryItemCategoryCode: null,
            lopFocusCategoryTaxClass: "1",
            lopFocusCategoryListPrice: 0,
            lopFocusCategoryDiscountPrice: 0,
            lopFocusCategoryTaxPrice: 0,
            lopFocusCategorySalesPrice: 0,
            lopFocusCategoryPreparation1: null,
            lopFocusCategoryPreparation2: null,
            lopFocusCategoryDeletedFlag: 0,
            lopFocusCategoryRegisteredUserId: "STAFF_A",
            lopFocusCategoryRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopFocusCategoryRegisteredDatetime: "2024/10/31 18:48:12.000",
            lopFocusCategoryUpdatedUserId: "STAFF_A",
            lopFocusCategoryUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopFocusCategoryUpdatedDatetime: "2024/10/31 18:48:12.000",
            lopFocusCategoryOptimisticLockVerNo: 1,
            lopFocusCategoryLensOptionCode: "Fsample999",
            lopFocusCategoryLensOptionName: "Standard",
            lopProgressiveCategoryLineitemId: null,
            lopProgressiveCategoryItemId: null,
            lopProgressiveCategoryItemCategoryCode: null,
            lopProgressiveCategoryTaxClass: "1",
            lopProgressiveCategoryListPrice: 0,
            lopProgressiveCategoryDiscountPrice: 0,
            lopProgressiveCategoryTaxPrice: 0,
            lopProgressiveCategorySalesPrice: 0,
            lopProgressiveCategoryPreparation1: null,
            lopProgressiveCategoryPreparation2: null,
            lopProgressiveCategoryDeletedFlag: 0,
            lopProgressiveCategoryRegisteredUserId: "STAFF_A",
            lopProgressiveCategoryRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopProgressiveCategoryRegisteredDatetime: "2024/10/31 18:48:12.000",
            lopProgressiveCategoryUpdatedUserId: "STAFF_A",
            lopProgressiveCategoryUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopProgressiveCategoryUpdatedDatetime: "2024/10/31 18:48:12.000",
            lopProgressiveCategoryOptimisticLockVerNo: 1,
            lopProgressiveCategoryLensOptionCode: "Psample999",
            lopProgressiveCategoryLensOptionName: "None",
            lopRefractiveIndexNameLineitemId: null,
            lopRefractiveIndexNameItemId: null,
            lopRefractiveIndexNameItemCategoryCode: null,
            lopRefractiveIndexNameTaxClass: "1",
            lopRefractiveIndexNameListPrice: 0,
            lopRefractiveIndexNameDiscountPrice: 0,
            lopRefractiveIndexNameTaxPrice: 0,
            lopRefractiveIndexNameSalesPrice: 0,
            lopRefractiveIndexNamePreparation1: null,
            lopRefractiveIndexNamePreparation2: null,
            lopRefractiveIndexNameDeletedFlag: 0,
            lopRefractiveIndexNameRegisteredUserId: "STAFF_A",
            lopRefractiveIndexNameRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopRefractiveIndexNameRegisteredDatetime: "2024/10/31 18:48:12.000",
            lopRefractiveIndexNameUpdatedUserId: "STAFF_A",
            lopRefractiveIndexNameUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopRefractiveIndexNameUpdatedDatetime: "2024/10/31 18:48:12.000",
            lopRefractiveIndexNameOptimisticLockVerNo: 1,
            lopRefractiveIndexNameLensOptionCode: "Rsample999",
            lopRefractiveIndexNameLensOptionName: "Ultra thin 1.74",
            lopRimlessFinishingCategoryLineitemId: null,
            lopRimlessFinishingCategoryItemId: null,
            lopRimlessFinishingCategoryItemCategoryCode: null,
            lopRimlessFinishingCategoryTaxClass: "1",
            lopRimlessFinishingCategoryListPrice: 0,
            lopRimlessFinishingCategoryDiscountPrice: 0,
            lopRimlessFinishingCategoryTaxPrice: 0,
            lopRimlessFinishingCategorySalesPrice: 0,
            lopRimlessFinishingCategoryPreparation1: null,
            lopRimlessFinishingCategoryPreparation2: null,
            lopRimlessFinishingCategoryDeletedFlag: 0,
            lopRimlessFinishingCategoryRegisteredUserId: "STAFF_A",
            lopRimlessFinishingCategoryRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopRimlessFinishingCategoryRegisteredDatetime: "2024/10/31 18:48:12.000",
            lopRimlessFinishingCategoryUpdatedUserId: "STAFF_A",
            lopRimlessFinishingCategoryUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            lopRimlessFinishingCategoryUpdatedDatetime: "2024/10/31 18:48:12.000",
            lopRimlessFinishingCategoryOptimisticLockVerNo: 1,
            lopRimlessFinishingCategoryLensOptionCode: "Rsample999",
            lopRimlessFinishingCategoryLensOptionName: "Sample",
            lensReplacementLineitemId: 4,
            lensReplacementItemId: 999999999999990000,
            lensReplacementItemCategoryCode: "14",
            lensReplacementTaxClass: 0,
            lensReplacementListPrice: 0,
            lensReplacementDiscountPrice: 0,
            lensReplacementTaxPrice: 0,
            lensReplacementSalesPrice: 0,
            lensReplacementPreparation1: null,
            lensReplacementPreparation2: null,
            lensReplacementDeletedFlag: 0,
            lensReplacementRegisteredUserId: "STAFF_A",
            lensReplacementRegisteredProgram: "550e8400-e29b-41d4-a716-446655440000",
            lensReplacementRegisteredDatetime: "2024/10/31 18:48:12.000",
            lensReplacementUpdatedUserId: "STAFF_A",
            lensReplacementUpdatedProgram: "550e8400-e29b-41d4-a716-446655440000",
            lensReplacementUpdatedDatetime: "2024/10/31 18:48:12.000",
            lensReplacementOptimisticLockVerNo: 1,
            lensReplacementTypeCode: "JINS-FRAME",
            lensReplacementTypeName: "JINS frame brought in",
            lensReplacementTypeNameKana: null,
            lensReplacementTypeNameEnglish: null,
            lensReplacementTypeNameSimplefied: null,
            lensReplacementTypeNameTraditional: null
          },
        ]
      }
    }
  },
  // ケース2：異常系（status:404）
  case2: {
    ok: false,
    status: 404,
    data: {
      code: "COM_0002",
      message: "Specified data not found."
    }
  },
  case3: {
    ok: true,
    status: 200,
    data: {
      cart:{
        phoneNumber: null,
        receptionStoreId: null,
        receptionStoreCode: null,
      }
    }
  },
}
  
