/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/diameter/check": {
    /** 径不足チェックAPI */
    post: operations["checkDiameter"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Format: int64
     * @description フレーム商品ID
     * @example 1137261
     */
    FrameItemId: number;
    /**
     * @description フレーム商品コード
     * @example LMN-18S-034-184
     */
    FrameItemCode: string;
    /**
     * @description SPH（球面度数）
     * @example 123.12
     */
    SphericalPower: number;
    /**
     * @description CYL（乱視度数）
     * @example 123.12
     */
    AstigmatismPrescription: number;
    /**
     * @description ADD（加入度数）
     * @example 1234.12
     */
    AddPower: number;
    /**
     * @description P.D（瞳孔間距離）
     * @example 123.12
     */
    PupillaryDistance: number;
    /**
     * @description E.P（目の位置）
     * @example 123.12
     */
    EyePoint: number;
    /**
     * @description 基準径
     * @example 1234
     */
    StandardDiameter: number;
    /**
     * @description レンズピント
     * @example 1
     */
    LensPint: string;
    /**
     * @description 屈折率
     * @example 1234.12
     */
    RefractiveIndex: number;
    /**
     * Format: int64
     * @description 販売用カラー名称ID
     * @example 123
     */
    SalesColorNameId: number;
    /**
     * Format: int64
     * @description 販売用レンズ仕様ID
     * @example 123
     */
    SalesLensSpecId: number;
    /**
     * Format: int64
     * @description 焦点分類ID
     * @example 123
     */
    FocusCategoryId: number;
    /**
     * Format: int64
     * @description 累進分類ID
     * @example 123
     */
    ProgressiveCategoryId: number;
    /**
     * Format: int64
     * @description 屈折率名称ID
     * @example 123
     */
    RefractiveIndexNameId: number;
    /**
     * @description 販売国コード(国コード(alpha-2))
     * @example US
     */
    CountryCodeAlpha2: string;
    DiameterPostRequest: {
      frameItemId?: components["schemas"]["FrameItemId"];
      frameItemCode?: components["schemas"]["FrameItemCode"];
      sphericalPowerLeft: components["schemas"]["SphericalPower"];
      astigmatismPrescriptionLeft: components["schemas"]["AstigmatismPrescription"];
      addPowerLeft?: components["schemas"]["AddPower"];
      pupillaryDistanceLeft: components["schemas"]["PupillaryDistance"];
      eyePointLeft?: components["schemas"]["EyePoint"];
      standardDiameterLeft?: components["schemas"]["StandardDiameter"];
      sphericalPowerRight: components["schemas"]["SphericalPower"];
      astigmatismPrescriptionRight: components["schemas"]["AstigmatismPrescription"];
      addPowerRight?: components["schemas"]["AddPower"];
      pupillaryDistanceRight: components["schemas"]["PupillaryDistance"];
      eyePointRight?: components["schemas"]["EyePoint"];
      standardDiameterRight?: components["schemas"]["StandardDiameter"];
      lensPint: components["schemas"]["LensPint"];
      refractiveIndex?: components["schemas"]["RefractiveIndex"];
      salesColorNameId: components["schemas"]["SalesColorNameId"];
      salesLensSpecId: components["schemas"]["SalesLensSpecId"];
      focusCategoryId: components["schemas"]["FocusCategoryId"];
      progressiveCategoryId: components["schemas"]["ProgressiveCategoryId"];
      refractiveIndexNameId: components["schemas"]["RefractiveIndexNameId"];
      countryCodeAlpha2: components["schemas"]["CountryCodeAlpha2"];
    };
    /** @description 径不足チェック対象商品のリクエストボディ */
    DiametersPostRequest: {
      records: components["schemas"]["DiameterPostRequest"][];
    };
    /** @description 商品リスト */
    DiametersPostResponse: ({
        /**
         * Format: int64
         * @description フレーム商品ID
         * @example 1137261
         */
        frameItemId?: number;
        /**
         * @description フレーム商品コード
         * @example LMN-18S-034-184
         */
        frameItemCode?: string;
        /**
         * @description 処理結果コード
         * @example 1
         */
        resCode?: number;
        /**
         * @description 処理結果メッセージ
         * @example The diameter is insufficient.
         */
        resMessage?: string | null;
        /**
         * @description レンズの取得件数
         * @example 1
         */
        resLensCount?: number;
        /** @description レンズリスト */
        lensLists?: ({
            /**
             * @description レンズ処理結果コード
             * @example 1
             */
            lensResCode?: number;
            /**
             * @description レンズ処理結果メッセージ
             * @example The diameter is insufficient.
             */
            lensResMessage?: string | null;
            /**
             * @description 左レンズ処理結果コード
             * @example 1
             */
            lensResCodeLeft?: number;
            /**
             * Format: int64
             * @description 左レンズ商品ID
             * @example 1234567890
             */
            lensItemIdLeft?: number | null;
            /**
             * @description 左レンズ商品コード
             * @example A1234567890
             */
            lensItemCodeLeft?: string | null;
            /**
             * @description 左レンズ不足mm幅
             * @example 1
             */
            lensShortageWidthLeft?: number | null;
            /**
             * @description 右レンズ処理結果コード
             * @example 1
             */
            lensResCodeRight?: number;
            /**
             * Format: int64
             * @description 右レンズ商品ID
             * @example 1234567890
             */
            lensItemIdRight?: number | null;
            /**
             * @description 右レンズ商品コード
             * @example A1234567890
             */
            lensItemCodeRight?: string | null;
            /**
             * @description 右レンズ不足mm幅
             * @example 1
             */
            lensShortageWidthRight?: number | null;
          })[];
      })[];
    CommonErrorResponse: {
      code: string;
      message: string;
      details?: Record<string, never>;
    };
  };
  responses: {
    /** @description Too Many Requests */
    TooManyRequests: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["CommonErrorResponse"];
      };
    };
  };
  parameters: {
    /**
     * @description <BFFシステムコード>_\<UUID>
     * @example bff_usgjpic_ab623ca6-b1e4-3796-a761-ca05605da64a
     */
    JinsTraceID: string;
    /**
     * @description UI側でユーザを識別できるIDを格納
     * @example U00001
     */
    UserID: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** 径不足チェックAPI */
  checkDiameter: {
    parameters: {
      header: {
        "jins-trace-id": components["parameters"]["JinsTraceID"];
        "jins-user-id": components["parameters"]["UserID"];
      };
    };
    /** @description 径不足チェックのリクエストボディ */
    requestBody: {
      content: {
        "application/json": components["schemas"]["DiametersPostRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["DiametersPostResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["CommonErrorResponse"];
        };
      };
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
